import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['chatdata'] };

export const chatdataDescription: INodeProperties[] = [
	{
		displayName: '操作',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnly },
		options: [
			{
				name: '[基础] 设置公钥',
				value: 'setPublicKey',
				action: '设置公钥',
				description: '设置专区公钥',
			},
			{
				name: '[基础] 获取授权存档成员列表',
				value: 'getAuthUserList',
				action: '获取授权存档成员列表',
				description: '获取授权存档成员列表',
			},
			{
				name: '[基础] 设置专区接收回调',
				value: 'setReceiveCallback',
				action: '设置专区接收回调',
				description: '设置专区接收回调',
			},
			{
				name: '[基础] 设置敏感信息隐藏',
				value: 'setHideSensitiveInfoConfig',
				action: '设置敏感信息隐藏',
				description: '设置敏感信息隐藏配置',
			},
			{
				name: '[基础] 获取敏感信息隐藏配置',
				value: 'getHideSensitiveInfoConfig',
				action: '获取敏感信息隐藏配置',
				description: '获取敏感信息隐藏配置',
			},
			{
				name: '[基础] 设置日志级别',
				value: 'setLogLevel',
				action: '设置日志级别',
				description: '设置日志级别',
			},
			{
				name: '[基础] 获取日志级别',
				value: 'getLogLevel',
				action: '获取日志级别',
				description: '获取日志级别',
			},
			{
				name: '[调用] 同步调用专区程序',
				value: 'syncCallProgram',
				action: '同步调用专区程序',
				description: '同步调用专区程序',
			},
			{
				name: '[调用] 创建异步调用任务',
				value: 'asyncProgramTask',
				action: '创建异步调用任务',
				description: '创建异步调用任务',
			},
			{
				name: '[调用] 获取异步任务结果',
				value: 'asyncProgramResult',
				action: '获取异步任务结果',
				description: '获取异步任务结果',
			},
			{
				name: '[调试] 开启调试模式',
				value: 'openDebugMode',
				action: '开启调试模式',
				description: '开启调试模式',
			},
			{
				name: '[调试] 关闭调试模式',
				value: 'closeDebugMode',
				action: '关闭调试模式',
				description: '关闭调试模式',
			},
			{
				name: '[调试] 获取调试模式状态',
				value: 'checkDebugMode',
				action: '获取调试模式状态',
				description: '获取调试模式状态',
			},
			{
				name: '[基础] 上传临时文件到专区',
				value: 'uploadMedia',
				action: '上传临时文件到专区',
				description: '上传临时文件到专区',
			},
		],
		default: 'getAuthUserList',
	},
	// setPublicKey
	{
		displayName: '公钥PEM',
		name: 'public_key',
		type: 'string',
		required: true,
		typeOptions: { rows: 6 },
		displayOptions: { show: { ...showOnly, operation: ['setPublicKey'] } },
		default: '',
		description:
			'RSA-2048 公钥 PEM。<a href="https://developer.work.weixin.qq.com/document/path/99845" target="_blank">官方文档</a>',
	},
	{
		displayName: '公钥版本号',
		name: 'public_key_ver',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['setPublicKey'] } },
		default: 1,
		typeOptions: { minValue: 1, maxValue: 4294967295, numberStepSize: 1 },
		description: 'public_key_ver，更换公钥时需大于旧版本号',
	},
	{
		displayName: '公钥轮换提示',
		name: 'publicKeyNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['setPublicKey'] } },
		default: '',
		description: '仅接受 RSA-2048 PUBLIC KEY PEM。更换公钥时版本号必须高于旧版本；请先安全保存对应私钥，私钥不要提交到此节点。',
	},
	// getAuthUserList
	{
		displayName: '游标',
		name: 'cursor',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['getAuthUserList'] } },
		default: '',
		description: '分页 cursor',
	},
	{
		displayName: '条数限制',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000, numberStepSize: 1 },
		displayOptions: { show: { ...showOnly, operation: ['getAuthUserList'] } },
		default: 200,
		description: '最大 1000，默认 200',
	},
	// program_id shared
	{
		displayName: '程序ID',
		name: 'program_id',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				...showOnly,
				operation: [
					'setReceiveCallback',
					'setLogLevel',
					'getLogLevel',
					'syncCallProgram',
					'asyncProgramTask',
					'openDebugMode',
					'closeDebugMode',
					'checkDebugMode',
				],
			},
		},
		default: '',
		typeOptions: { maxLength: 256 },
		description: '应用关联的 program_id',
	},
	{
		displayName: '回调切换提示',
		name: 'callbackNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['setReceiveCallback'] } },
		default: '',
		description: '同一应用只能设置一个接收程序；再次设置会把原接收程序切换为当前程序。',
	},
	// sensitive info
	{
		displayName: '成员UserID',
		name: 'userid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['setHideSensitiveInfoConfig'] } },
		default: '',
		typeOptions: { maxLength: 64 },
		description: '要设置会话组件隐藏规则的成员 UserID',
	},
	{
		displayName: '成员密文UserID',
		name: 'userid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['getHideSensitiveInfoConfig'] } },
		default: '',
		typeOptions: { maxLength: 64 },
		description: '官方接口要求填写成员的密文 UserID',
	},
	{
		displayName: '隐藏手机号',
		name: 'hide_mobile',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, operation: ['setHideSensitiveInfoConfig'] } },
		default: false,
	},
	{
		displayName: '隐藏身份证号',
		name: 'hide_idcard',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, operation: ['setHideSensitiveInfoConfig'] } },
		default: false,
	},
	{
		displayName: '隐藏银行卡号',
		name: 'hide_bankno',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, operation: ['setHideSensitiveInfoConfig'] } },
		default: false,
	},
	{
		displayName: '敏感信息显示提示',
		name: 'sensitiveInfoNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['setHideSensitiveInfoConfig'] } },
		default: '',
		description: '该配置会改变指定成员在会话组件中看到的手机号、身份证号和银行卡号显示方式。',
	},
	// log level
	{
		displayName: '日志级别',
		name: 'log_level',
		type: 'options',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['setLogLevel'] } },
		options: [
			{ name: 'ERR', value: 1 },
			{ name: 'INFO', value: 2 },
			{ name: 'DBG', value: 3 },
		],
		default: 2,
	},
	// call program
	{
		displayName: '能力ID',
		name: 'ability_id',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['syncCallProgram', 'asyncProgramTask'] },
		},
		default: '',
		typeOptions: { maxLength: 256 },
	},
	{
		displayName: '请求数据JSON',
		name: 'request_data',
		type: 'json',
		required: true,
		typeOptions: { rows: 6 },
		displayOptions: {
			show: { ...showOnly, operation: ['syncCallProgram', 'asyncProgramTask'] },
		},
		default: '{}',
		description: '必须是有效 JSON 对象；节点会序列化为 request_data 字符串并限制为 1MB',
	},
	{
		displayName: '通知ID',
		name: 'notify_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['syncCallProgram'] } },
		default: '',
		typeOptions: { maxLength: 256 },
		description: 'notify_id，可选，由专区通知应用返回',
	},
	{
		displayName: '任务ID',
		name: 'jobid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['asyncProgramResult'] } },
		default: '',
		typeOptions: { maxLength: 256 },
	},
	{
		displayName: '专区调用提示',
		name: 'programCallNotice',
		type: 'notice',
		displayOptions: {
			show: { ...showOnly, operation: ['syncCallProgram', 'asyncProgramTask'] },
		},
		default: '',
		description: '请求数据必须符合所选能力在管理端配置的输入协议；异步调用会创建任务，结果需用返回的 jobid 查询。',
	},
	// debug
	{
		displayName: '调试Token',
		name: 'debug_token',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['openDebugMode'] } },
		default: '',
	},
	{
		displayName: '调试模式提示',
		name: 'debugModeNotice',
		type: 'notice',
		displayOptions: {
			show: { ...showOnly, operation: ['openDebugMode', 'closeDebugMode'] },
		},
		default: '',
		description: '调试模式会改变专区程序的调试调用状态。调试 Token 属于敏感凭证，请勿写入输出或日志。',
	},
	{
		displayName: '二进制字段名',
		name: 'binaryProperty',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['uploadMedia'] } },
		default: 'data',
		description: '输入数据中的文件二进制字段名',
	},
	{
		displayName: '文件类型',
		name: 'mediaType',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['uploadMedia'] } },
		options: [{ name: 'file', value: 'file' }],
		default: 'file',
		description: '目前仅支持 file',
	},
	{
		displayName: '临时文件提示',
		name: 'uploadMediaNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['uploadMedia'] } },
		default: '',
		description: '文件大小必须为 6B–60MB。返回的 media_id 仅 3 天有效，且不能跨企业或跨应用使用。',
	},
];
