import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['agent'], operation: ['createMenu'] };
const eventTypes = [
	'click',
	'scancode_push',
	'scancode_waitmsg',
	'pic_sysphoto',
	'pic_photo_or_album',
	'pic_weixin',
	'location_select',
];
const actionTypeOptions = [
	{ name: '点击推事件', value: 'click' },
	{ name: '跳转网页', value: 'view' },
	{ name: '扫码推事件', value: 'scancode_push' },
	{ name: '扫码并显示接收提示', value: 'scancode_waitmsg' },
	{ name: '系统拍照发图', value: 'pic_sysphoto' },
	{ name: '拍照或相册发图', value: 'pic_photo_or_album' },
	{ name: '企业微信相册发图', value: 'pic_weixin' },
	{ name: '选择地理位置', value: 'location_select' },
	{ name: '跳转小程序', value: 'view_miniprogram' },
];

const subMenuFields: INodeProperties[] = [
	{
		displayName: '名称',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		description: '不能为空且不超过 40 个字节',
	},
	{
		displayName: '类型',
		name: 'type',
		type: 'options',
		required: true,
		options: actionTypeOptions,
		default: 'click',
	},
	{
		displayName: '事件 Key',
		name: 'key',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { type: eventTypes } },
		description: '不超过 128 个字节',
	},
	{
		displayName: '网页 URL',
		name: 'url',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { type: ['view'] } },
		description: 'HTTP(S) 链接，不超过 1024 个字节',
	},
	{
		displayName: '小程序 AppID',
		name: 'appid',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { type: ['view_miniprogram'] } },
	},
	{
		displayName: '小程序页面路径',
		name: 'pagepath',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { type: ['view_miniprogram'] } },
	},
];

const topMenuFields: INodeProperties[] = [
	{
		displayName: '菜单名称',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		description: '不能为空且不超过 16 个字节',
	},
	{
		displayName: '类型',
		name: 'type',
		type: 'options',
		required: true,
		options: [
			{ name: '包含子菜单', value: 'sub' },
			{ name: '点击推事件', value: 'click' },
			{ name: '跳转网页', value: 'view' },
			{ name: '扫码推事件', value: 'scancode_push' },
			{ name: '扫码并显示接收提示', value: 'scancode_waitmsg' },
			{ name: '系统拍照发图', value: 'pic_sysphoto' },
			{ name: '拍照或相册发图', value: 'pic_photo_or_album' },
			{ name: '企业微信相册发图', value: 'pic_weixin' },
			{ name: '选择地理位置', value: 'location_select' },
			{ name: '跳转小程序', value: 'view_miniprogram' },
		],
		default: 'click',
	},
	{
		displayName: '事件 Key',
		name: 'key',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { type: eventTypes } },
		description: '不超过 128 个字节',
	},
	{
		displayName: '网页 URL',
		name: 'url',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { type: ['view'] } },
		description: 'HTTP(S) 链接，不超过 1024 个字节',
	},
	{
		displayName: '小程序 AppID',
		name: 'appid',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { type: ['view_miniprogram'] } },
	},
	{
		displayName: '小程序页面路径',
		name: 'pagepath',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { type: ['view_miniprogram'] } },
	},
	{
		displayName: '子菜单',
		name: 'subButtonsCollection',
		type: 'fixedCollection',
		required: true,
		default: {},
		placeholder: '添加子菜单',
		typeOptions: { multipleValues: true },
		displayOptions: { show: { type: ['sub'] } },
		description: '添加 1–5 个二级菜单',
		options: [
			{
				displayName: '子菜单项',
				name: 'items',
				values: subMenuFields,
			},
		],
	},
];

export const createMenuDescription: INodeProperties[] = [
	{
		displayName: '应用 ID',
		name: 'agentid',
		type: 'number',
		required: true,
		default: 0,
		typeOptions: { minValue: 1, numberStepSize: 1 },
		displayOptions: { show: showOnly },
		description: '企业应用 ID',
	},
	{
		displayName: '菜单配置方式',
		name: 'menuConfigMode',
		type: 'options',
		options: [
			{ name: '表单', value: 'form' },
			{ name: 'JSON', value: 'json' },
		],
		default: 'form',
		displayOptions: { show: showOnly },
	},
	{
		displayName: '一级菜单',
		name: 'menuButtonCollection',
		type: 'fixedCollection',
		required: true,
		default: {},
		placeholder: '添加一级菜单',
		typeOptions: { multipleValues: true },
		displayOptions: { show: { ...showOnly, menuConfigMode: ['form'] } },
		description: '添加 1–3 个一级菜单',
		options: [
			{
				displayName: '菜单项',
				name: 'buttons',
				values: topMenuFields,
			},
		],
	},
	{
		displayName: '一级菜单 JSON',
		name: 'button',
		type: 'json',
		required: true,
		typeOptions: { rows: 10 },
		displayOptions: { show: { ...showOnly, menuConfigMode: ['json'] } },
		default: '[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC"}]',
		description: '企业微信 button 数组；会执行与表单相同的完整校验',
	},
];
