import type { INodeProperties } from 'n8n-workflow';

const showOnlyForUpdateRecurring = {
	resource: ['calendar'],
	operation: ['updateRecurringSchedule'],
};

export const updateRecurringScheduleDescription: INodeProperties[] = [
	{
		displayName: '日程ID',
		name: 'schedule_id',
		type: 'string',
		required: true,
		displayOptions: { show: showOnlyForUpdateRecurring },
		default: '',
	},
	{
		displayName: '主题',
		name: 'schedule_summary',
		type: 'string',
		displayOptions: { show: showOnlyForUpdateRecurring },
		default: '',
		description: 'schedule.summary',
	},
	{
		displayName: '描述',
		name: 'schedule_description',
		type: 'string',
		typeOptions: { rows: 2 },
		displayOptions: { show: showOnlyForUpdateRecurring },
		default: '',
		description: 'schedule.description',
	},
	{
		displayName: '开始时间',
		name: 'schedule_start_time',
		type: 'dateTime',
		displayOptions: { show: showOnlyForUpdateRecurring },
		default: '',
		description: 'start_time（Unix 秒）；空表示不改',
	},
	{
		displayName: '结束时间',
		name: 'schedule_end_time',
		type: 'dateTime',
		displayOptions: { show: showOnlyForUpdateRecurring },
		default: '',
		description: 'end_time（Unix 秒）；空表示不改',
	},
	{
		displayName: '地点',
		name: 'schedule_location',
		type: 'string',
		displayOptions: { show: showOnlyForUpdateRecurring },
		default: '',
		description: 'schedule.location',
	},
	{
		displayName: '是否全天日程',
		name: 'schedule_is_whole_day',
		type: 'boolean',
		displayOptions: { show: showOnlyForUpdateRecurring },
		default: false,
		description: 'schedule.is_whole_day；扩展 JSON 中显式设置时优先',
	},
	{
		displayName: '参与者UserID列表',
		name: 'attendee_userids',
		type: 'string',
		displayOptions: { show: showOnlyForUpdateRecurring },
		default: '',
		placeholder: 'zhangsan,lisi',
		description: '覆盖式更新参与者；与下方选择合并。skip_attendees 为 true 时忽略',
	},
	{
		displayName: '参与者(选择)',
		name: 'attendees',
		type: 'multiOptions',
		displayOptions: { show: showOnlyForUpdateRecurring },
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: [],
		description: '最多 1000 人；与上方 UserID 列表合并',
	},
	{
		displayName: '管理员UserID列表',
		name: 'admin_userids',
		type: 'string',
		displayOptions: { show: showOnlyForUpdateRecurring },
		default: '',
		placeholder: 'zhangsan',
		description: '最多 3 人；须在参与者中',
	},
	{
		displayName: '日程管理员(选择)',
		name: 'admins',
		type: 'multiOptions',
		displayOptions: { show: showOnlyForUpdateRecurring },
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: [],
		description: '最多 3 人；与上方 UserID 列表合并',
	},
	{
		displayName: '日程扩展JSON',
		name: 'schedule',
		type: 'json',
		displayOptions: { show: showOnlyForUpdateRecurring },
		default: '{}',
		description: '其余 schedule 字段与上方合并，JSON 优先',
	},
	{
		displayName: '跳过参与者更新',
		name: 'skip_attendees',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnlyForUpdateRecurring },
	},
	{
		displayName: '操作模式',
		name: 'op_mode',
		type: 'options',
		options: [
			{ name: '全部修改', value: 0 },
			{ name: '仅修改此日程', value: 1 },
			{ name: '修改将来的所有日程', value: 2 },
		],
		default: 1,
		displayOptions: { show: showOnlyForUpdateRecurring },
	},
	{
		displayName: '操作起始时间',
		name: 'op_start_time',
		type: 'dateTime',
		required: true,
		displayOptions: {
			show: {
				...showOnlyForUpdateRecurring,
				op_mode: [1, 2],
			},
		},
		default: '',
		description: 'op_mode 为 1 或 2 时有效',
	},
];
