import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['miniapppay'] };

export const miniapppayDescription: INodeProperties[] = [
	{
		displayName: '操作',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnly },
		options: [
			{
				name: '[支付] 小程序下单',
				value: 'createOrder',
				action: '小程序下单',
				description: '创建小程序支付订单',
			},
			{
				name: '[支付] 查询订单',
				value: 'getOrder',
				action: '查询订单',
				description: '查询支付订单',
			},
			{
				name: '[支付] 关闭订单',
				value: 'closeOrder',
				action: '关闭订单',
				description: '关闭支付订单',
			},
			{
				name: '[支付] 获取支付签名',
				value: 'getSign',
				action: '获取支付签名',
				description: '获取支付签名',
			},
			{
				name: '[退款] 申请退款',
				value: 'refund',
				action: '申请退款',
				description: '申请退款',
			},
			{
				name: '[退款] 查询退款',
				value: 'getRefundDetail',
				action: '查询退款',
				description: '查询退款详情',
			},
			{
				name: '[账单] 交易账单申请',
				value: 'getBill',
				action: '交易账单申请',
				description: '申请交易账单',
			},
			{
				name: '[账单] 下载账单文件',
				value: 'downloadBillFile',
				action: '下载账单文件',
				description: '使用账单申请返回的下载地址获取账单文件',
			},
			{
				name: '[进件] 提交创建对外收款账户申请',
				value: 'applyMch',
				action: '提交进件申请',
				description: '提交创建对外收款账户申请',
			},
			{
				name: '[进件] 查询申请单状态',
				value: 'getApplymentStatus',
				action: '查询进件状态',
				description: '查询进件申请单状态',
			},
			{
				name: '[进件] 提交图片',
				value: 'uploadImage',
				action: '提交进件图片',
				description: '上传进件所需图片',
			},
		],
		default: 'createOrder',
	},
	{
		displayName: '商户申请单号',
		name: 'out_request_no',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['applyMch', 'getApplymentStatus'] },
		},
		default: '',
		description: '业务申请编号，1–32 个字符，须唯一',
	},
	{
		displayName: '主体类型',
		name: 'organization_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		options: [
			{ name: '企业', value: 0 },
			{ name: '个体', value: 1 },
			{ name: '社会团体组织', value: 2 },
			{ name: '事业单位', value: 3 },
		],
		default: 1,
		description: 'organization_type',
	},
	{
		displayName: '商户简称',
		name: 'merchant_short_name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: 'merchant_short_name，支付完成页展示',
	},
	{
		displayName: '提现人员UserID',
		name: 'apply_userid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: 'userid，须实名且与超级管理员为同一人',
	},
	{
		displayName: '经营范围ID',
		name: 'business_id',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: 1,
		typeOptions: { minValue: 1, maxValue: 31, numberStepSize: 1 },
		description: 'business_id，见经营范围对照表',
	},
	{
		displayName: '法人是否为受益人',
		name: 'owner',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: true,
		description: 'owner，主体为企业时填写',
	},
	// 营业执照
	{
		displayName: '商户名称',
		name: 'merchant_name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: 'business_license_info.merchant_name',
	},
	{
		displayName: '法人姓名',
		name: 'legal_person',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: 'business_license_info.legal_person',
	},
	{
		displayName: '营业执照号',
		name: 'business_license_number',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: 'business_license_info.business_license_number',
	},
	{
		displayName: '营业执照图片MediaID',
		name: 'business_license_copy_media_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: 'business_license_copy_open_wx_pay_media_id，由提交图片接口获得',
	},
	{
		displayName: '注册地址',
		name: 'company_address',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: 'business_license_info.company_address',
	},
	{
		displayName: '营业期限开始',
		name: 'business_time_begin_time',
		type: 'dateTime',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		placeholder: '2010-01-01',
		description: 'YYYY-MM-DD',
	},
	{
		displayName: '营业期限结束',
		name: 'business_time_end_time',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		placeholder: '长期',
		description: 'YYYY-MM-DD 或「长期」',
	},
	{
		displayName: '登记证书类型',
		name: 'cert_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		options: [
			{ name: '不填(个体/企业/事业单位)', value: 0 },
			{ name: '统一社会信用代码证书 2389', value: 2389 },
			{ name: '社会团体法人登记证书 2394', value: 2394 },
			{ name: '民办非企业单位登记证书 2395', value: 2395 },
			{ name: '基金会法人登记证书 2396', value: 2396 },
			{ name: '宗教活动场所登记证 2399', value: 2399 },
			{ name: '其他有效证明文件 2400', value: 2400 },
			{ name: '执业许可证/执业证 2520', value: 2520 },
			{ name: '基层群众自治组织统一信用代码证 2521', value: 2521 },
			{ name: '农村集体经济组织登记证 2522', value: 2522 },
		],
		default: 0,
		description: 'cert_type，社会团体组织时填写',
	},
	// 法人证件
	{
		displayName: '证件类型',
		name: 'id_doc_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		options: [
			{ name: '身份证(默认 8)', value: 8 },
			{ name: '身份证 0', value: 0 },
			{ name: '护照', value: 1 },
			{ name: '香港来往内地通行证', value: 2 },
			{ name: '澳门来往内地通行证', value: 3 },
			{ name: '台湾来往大陆通行证', value: 4 },
			{ name: '外国人居留证', value: 5 },
			{ name: '港澳居民证', value: 6 },
			{ name: '台湾居民证', value: 7 },
		],
		default: 8,
		description: 'id_card_info.id_doc_type',
	},
	{
		displayName: '证件姓名',
		name: 'id_card_name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: 'id_card_info.id_card_name',
	},
	{
		displayName: '证件号码',
		name: 'id_card_number',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
	},
	{
		displayName: '证件居住地址',
		name: 'id_card_address',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: '主体为企业时需要',
	},
	{
		displayName: '证件有效期开始',
		name: 'id_card_valid_time_begin',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		placeholder: '2010-01-01',
	},
	{
		displayName: '证件有效期结束',
		name: 'id_card_valid_time',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		placeholder: '长期',
	},
	{
		displayName: '身份证人像面MediaID',
		name: 'id_card_copy_media_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: 'id_card_copy_open_wx_pay_media_id',
	},
	{
		displayName: '身份证国徽面MediaID',
		name: 'id_card_national_media_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: 'id_card_national_open_wx_pay_media_id',
	},
	// 超级管理员
	{
		displayName: '超级管理员类型',
		name: 'contact_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		options: [
			{ name: '经营者/法人 65', value: '65' },
			{ name: '经办人 66', value: '66' },
		],
		default: '65',
		description: 'contact_info.contact_type',
	},
	{
		displayName: '管理员姓名',
		name: 'contact_name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: 'contact_info.contact_info.id_card_name；法人时须与法人一致',
	},
	{
		displayName: '管理员证件号',
		name: 'contact_id_number',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
	},
	{
		displayName: '管理员手机',
		name: 'contact_mobile_phone',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
	},
	{
		displayName: '管理员邮箱',
		name: 'contact_email',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
	},
	// 结算账户
	{
		displayName: '账户类型',
		name: 'bank_account_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		options: [
			{ name: '不指定', value: 0 },
			{ name: '对公账户 74', value: 74 },
			{ name: '对私账户 75', value: 75 },
		],
		default: 0,
		description: '个体主体时填写',
	},
	{
		displayName: '开户银行',
		name: 'account_bank',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		placeholder: '中国银行',
	},
	{
		displayName: '开户名称',
		name: 'account_name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
	},
	{
		displayName: '银行账号',
		name: 'account_number',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
	},
	{
		displayName: '开户省市编码',
		name: 'bank_address_code',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: '至少精确到市的 6 位编码',
	},
	{
		displayName: '开户银行全称(含支行)',
		name: 'bank_name',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
		description: '非直连银行需要填写',
	},
	// 经营场景
	{
		displayName: '经营场景',
		name: 'sales_scene_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		options: [
			{ name: '线下门店', value: 1 },
			{ name: '线上店铺', value: 2 },
		],
		default: 2,
		description: 'sales_scene_info.type',
	},
	{
		displayName: '线上店铺URL',
		name: 'store_url',
		type: 'string',
		displayOptions: {
			show: { ...showOnly, operation: ['applyMch'], sales_scene_type: [2] },
		},
		default: '',
		description: '最长 1024 个 UTF-8 字节；与线上店铺二维码 MediaID 至少填写一项',
	},
	{
		displayName: '线上店铺二维码MediaID',
		name: 'store_pic_media_id',
		type: 'string',
		displayOptions: {
			show: { ...showOnly, operation: ['applyMch'], sales_scene_type: [2] },
		},
		default: '',
		description: '与线上店铺 URL 至少填写一项',
	},
	{
		displayName: '线下场所省市区编码',
		name: 'offline_address_code',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['applyMch'], sales_scene_type: [1] },
		},
		default: '',
	},
	{
		displayName: '线下场所详细地址',
		name: 'offline_address',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['applyMch'], sales_scene_type: [1] },
		},
		default: '',
	},
	{
		displayName: '门头照片MediaID',
		name: 'entrance_pic_media_id',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['applyMch'], sales_scene_type: [1] },
		},
		default: '',
	},
	{
		displayName: '店内照片MediaID',
		name: 'indoor_pic_media_id',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['applyMch'], sales_scene_type: [1] },
		},
		default: '',
	},
	{
		displayName: '进件申请其余字段JSON',
		name: 'applyMchJson',
		type: 'json',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '{}',
		description:
			'ubo_info、finance_institution_info、补充材料等深层嵌套，与上方合并；合并后仍会校验官方必填对象与经营场景条件',
	},
	{
		displayName: '主体、证件、超级管理员、结算账户和经营场景资料将提交微信支付审核。企业法人不是受益人、金融机构或经办人场景，请在高级 JSON 中补齐对应官方字段。',
		name: 'applyMchNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '',
	},
	// 公共商户字段
	{
		displayName: '商户号',
		name: 'mchid',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				...showOnly,
				operation: ['createOrder', 'getOrder', 'closeOrder', 'refund', 'getRefundDetail', 'getBill'],
			},
		},
		default: '',
		description: '二级商户号 mchid',
	},
	{
		displayName: 'AppID',
		name: 'appid',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['createOrder', 'getSign', 'refund'] },
		},
		default: '',
		description: '二级商户申请的公众号/小程序 appid',
	},
	// createOrder
	{
		displayName: '商户订单号',
		name: 'out_trade_no',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				...showOnly,
				operation: ['createOrder', 'getOrder', 'closeOrder', 'refund'],
			},
		},
		default: '',
		description: '商户系统内部订单号 out_trade_no',
	},
	{
		displayName: '商品描述',
		name: 'description',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
	},
	{
		displayName: '订单金额(分)',
		name: 'amount_total',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: 1,
		typeOptions: { minValue: 1, numberStepSize: 1 },
		description: '原订单金额，单位：分',
	},
	{
		displayName: '货币类型',
		name: 'amount_currency',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['createOrder', 'refund'] } },
		default: 'CNY',
	},
	{
		displayName: '支付者OpenID',
		name: 'payer_openid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
		description: '支付者在小程序下的 OpenID',
	},
	{
		displayName: '支付结果通知URL',
		name: 'notify_url',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
		description: '支付结果回调通知地址',
	},
	{
		displayName: '下单场景Key',
		name: 'scenekey',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
		description: 'scenekey，可选，用于成员业绩统计',
	},
	{
		displayName: '附加数据',
		name: 'attach',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
		description: 'attach，支付通知原样返回',
	},
	{
		displayName: '订单优惠标记',
		name: 'goods_tag',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
		description: 'goods_tag，代金券或立减优惠标记',
	},
	{
		displayName: '交易结束时间',
		name: 'time_expire',
		type: 'dateTime',
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
		placeholder: '2018-06-08T10:34:56+08:00',
		description: 'time_expire，RFC3339 格式',
	},
	{
		displayName: '用户终端IP',
		name: 'payer_client_ip',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '127.0.0.1',
		description: '用户终端的 IP 地址',
	},
	{
		displayName: '门店编号',
		name: 'store_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
	},
	{
		displayName: '优惠详情JSON',
		name: 'detail_json',
		type: 'json',
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '{}',
		description: 'detail 优惠功能字段，见微信支付优惠说明',
	},
	{
		displayName: '高级下单JSON',
		name: 'advancedJson',
		type: 'json',
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '{}',
		description: '可选，合并进请求体的扩展字段；核心订单身份、金额、支付者与门店字段以表单为准',
	},
	{
		displayName: '订单关闭后不能继续支付。请确认商户号与订单号无误后执行。',
		name: 'closeOrderNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['closeOrder'] } },
		default: '',
	},
	// getSign
	{
		displayName: '预支付ID',
		name: 'prepay_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['getSign'] } },
		default: '',
		description: 'create_order 返回的 prepay_id',
	},
	{
		displayName: '随机字符串',
		name: 'nonce',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['getSign'] } },
		default: '',
		description: 'nonce，不长于 32 位',
	},
	{
		displayName: '时间戳',
		name: 'timestamp',
		type: 'dateTime',
		displayOptions: { show: { ...showOnly, operation: ['getSign'] } },
		default: '',
		description: '签名时间（Unix 秒）；留空表示使用当前时间',
	},
	{
		displayName: '签名类型',
		name: 'sign_type',
		type: 'options',
		options: [{ name: 'RSA', value: 'RSA' }],
		displayOptions: { show: { ...showOnly, operation: ['getSign'] } },
		default: 'RSA',
	},
	// refund
	{
		displayName: '商户退款单号',
		name: 'out_refund_no',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['refund', 'getRefundDetail'] },
		},
		default: '',
	},
	{
		displayName: '退款金额(分)',
		name: 'refund_amount',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['refund'] } },
		default: 1,
		typeOptions: { minValue: 1, numberStepSize: 1 },
		description: '退款金额，单位：分',
	},
	{
		displayName: '原订单金额(分)',
		name: 'total_amount',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['refund'] } },
		default: 1,
		typeOptions: { minValue: 1, numberStepSize: 1 },
		description: '原订单金额，单位：分',
	},
	{
		displayName: '退款原因',
		name: 'reason',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['refund'] } },
		default: '',
	},
	{
		displayName: '资金账户',
		name: 'funds_account',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['refund'] } },
		options: [
			{ name: '不指定', value: '' },
			{ name: '可用余额 AVAILABLE', value: 'AVAILABLE' },
		],
		default: '',
		description: '待分账状态订单可填 AVAILABLE，从二级商户余额退款',
	},
	{
		displayName: '退款金额不能超过原订单金额；同一商户退款单号重复请求只会退款一笔。单笔订单申请退款频率上限为每分钟 1 次。',
		name: 'refundNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['refund'] } },
		default: '',
	},
	// getBill
	{
		displayName: '账单日期',
		name: 'bill_date',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['getBill'] } },
		default: '',
		placeholder: '2019-06-11',
		description: '将转换为 yyyy-MM-dd，仅支持今天至最近三个月内的账单',
	},
	{
		displayName: '账单类型',
		name: 'bill_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['getBill'] } },
		options: [
			{ name: 'ALL', value: 'ALL' },
			{ name: 'SUCCESS', value: 'SUCCESS' },
			{ name: 'REFUND', value: 'REFUND' },
		],
		default: 'ALL',
	},
	{
		displayName: '压缩类型',
		name: 'tar_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['getBill'] } },
		options: [
			{ name: '不压缩', value: '' },
			{ name: 'GZIP', value: 'GZIP' },
		],
		default: '',
	},
	// downloadBillFile
	{
		displayName: '账单下载地址',
		name: 'download_url',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['downloadBillFile'] } },
		default: '',
		description:
			'交易账单申请返回的 download_url（约 30 秒有效，形如 https://api.mch.weixin.qq.com/v3/billdownload/file?token=...）',
	},
	{
		displayName: '下载地址约 30 秒有效。节点仅允许访问 api.mch.weixin.qq.com 的官方 HTTPS 账单下载路径。',
		name: 'downloadBillNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['downloadBillFile'] } },
		default: '',
	},
	{
		displayName: 'Authorization 头',
		name: 'auth_header',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['downloadBillFile'] } },
		default: '',
		description:
			'账单申请返回的 auth（如有）。可填完整 “Authorization: xxx”，或仅填 token 值',
	},
	{
		displayName: '输出二进制字段名',
		name: 'binaryPropertyOut',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['downloadBillFile'] } },
		default: 'data',
		description: '账单文件写入的二进制字段名',
	},
	{
		displayName: '二进制字段名',
		name: 'binaryProperty',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['uploadImage'] } },
		default: 'data',
		description: '输入数据中的图片二进制字段名，支持 JPG/PNG/BMP',
	},
	{
		displayName: '仅支持 JPG/JPEG、PNG、BMP。上传所得图片 ID 最长 30 天有效，相关申请全部完成后可能立即失效。',
		name: 'uploadImageNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['uploadImage'] } },
		default: '',
	},
];
