import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['miniapppay'] };

export const miniapppayDescription: INodeProperties[] = [
	{
		displayName: '操作',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnly },
		options: [
			{
				name: '[支付] 小程序下单',
				value: 'createOrder',
				action: '小程序下单',
				description: '创建小程序支付订单',
			},
			{
				name: '[支付] 查询订单',
				value: 'getOrder',
				action: '查询订单',
				description: '查询支付订单',
			},
			{
				name: '[支付] 关闭订单',
				value: 'closeOrder',
				action: '关闭订单',
				description: '关闭支付订单',
			},
			{
				name: '[支付] 获取支付签名',
				value: 'getSign',
				action: '获取支付签名',
				description: '获取支付签名',
			},
			{
				name: '[退款] 申请退款',
				value: 'refund',
				action: '申请退款',
				description: '申请退款',
			},
			{
				name: '[退款] 查询退款',
				value: 'getRefundDetail',
				action: '查询退款',
				description: '查询退款详情',
			},
			{
				name: '[账单] 交易账单申请',
				value: 'getBill',
				action: '交易账单申请',
				description: '申请交易账单',
			},
			{
				name: '[进件] 提交创建对外收款账户申请',
				value: 'applyMch',
				action: '提交进件申请',
				description: '提交创建对外收款账户申请',
			},
			{
				name: '[进件] 查询申请单状态',
				value: 'getApplymentStatus',
				action: '查询进件状态',
				description: '查询进件申请单状态',
			},
			{
				name: '[进件] 提交图片',
				value: 'uploadImage',
				action: '提交进件图片',
				description: '上传进件所需图片',
			},
		],
		default: 'createOrder',
	},
	{
		displayName: '进件申请JSON',
		name: 'applyMchJson',
		type: 'json',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['applyMch'] } },
		default: '{}',
		description:
			'apply_mch 完整请求体，字段见官方「提交创建对外收款账户的申请单」。<a href="https://developer.work.weixin.qq.com/document/path/98973" target="_blank">官方文档</a>',
	},
	{
		displayName: '商户申请单号',
		name: 'out_request_no',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['getApplymentStatus'] } },
		default: '',
		description: 'out_request_no，进件时填写的业务申请编号',
	},
	// 公共商户字段
	{
		displayName: '商户号',
		name: 'mchid',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				...showOnly,
				operation: ['createOrder', 'getOrder', 'closeOrder', 'refund', 'getRefundDetail', 'getBill'],
			},
		},
		default: '',
		description: '二级商户号 mchid',
	},
	{
		displayName: 'AppID',
		name: 'appid',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['createOrder', 'getSign', 'refund'] },
		},
		default: '',
		description: '二级商户申请的公众号/小程序 appid',
	},
	// createOrder
	{
		displayName: '商户订单号',
		name: 'out_trade_no',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				...showOnly,
				operation: ['createOrder', 'getOrder', 'closeOrder', 'refund'],
			},
		},
		default: '',
		description: '商户系统内部订单号 out_trade_no',
	},
	{
		displayName: '商品描述',
		name: 'description',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
	},
	{
		displayName: '订单金额(分)',
		name: 'amount_total',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: 1,
		description: '原订单金额，单位：分',
	},
	{
		displayName: '货币类型',
		name: 'amount_currency',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['createOrder', 'refund'] } },
		default: 'CNY',
	},
	{
		displayName: '支付者OpenID',
		name: 'payer_openid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
		description: '支付者在小程序下的 OpenID',
	},
	{
		displayName: '下单场景Key',
		name: 'scenekey',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
		description: 'scenekey，可选，用于成员业绩统计',
	},
	{
		displayName: '附加数据',
		name: 'attach',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
	},
	{
		displayName: '用户终端IP',
		name: 'payer_client_ip',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '127.0.0.1',
		description: '用户终端的 IP 地址',
	},
	{
		displayName: '门店编号',
		name: 'store_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '',
	},
	{
		displayName: '高级下单JSON',
		name: 'advancedJson',
		type: 'json',
		displayOptions: { show: { ...showOnly, operation: ['createOrder'] } },
		default: '{}',
		description: '可选，合并进请求体的扩展字段（detail/time_expire/goods_tag 等）',
	},
	// getSign
	{
		displayName: '预支付ID',
		name: 'prepay_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['getSign'] } },
		default: '',
		description: 'create_order 返回的 prepay_id',
	},
	{
		displayName: '随机字符串',
		name: 'nonce',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['getSign'] } },
		default: '',
		description: 'nonce，不长于 32 位',
	},
	{
		displayName: '时间戳',
		name: 'timestamp',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['getSign'] } },
		default: 0,
		description: '秒级时间戳；0 表示使用当前时间',
	},
	{
		displayName: '签名类型',
		name: 'sign_type',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['getSign'] } },
		default: 'RSA',
	},
	// refund
	{
		displayName: '商户退款单号',
		name: 'out_refund_no',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['refund', 'getRefundDetail'] },
		},
		default: '',
	},
	{
		displayName: '退款金额(分)',
		name: 'refund_amount',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['refund'] } },
		default: 1,
		description: '退款金额，单位：分',
	},
	{
		displayName: '原订单金额(分)',
		name: 'total_amount',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['refund'] } },
		default: 1,
		description: '原订单金额，单位：分',
	},
	{
		displayName: '退款原因',
		name: 'reason',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['refund'] } },
		default: '',
	},
	// getBill
	{
		displayName: '账单日期',
		name: 'bill_date',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['getBill'] } },
		default: '',
		placeholder: '2019-06-11',
		description: 'yyyy-MM-dd，仅支持三个月内',
	},
	{
		displayName: '账单类型',
		name: 'bill_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['getBill'] } },
		options: [
			{ name: 'ALL', value: 'ALL' },
			{ name: 'SUCCESS', value: 'SUCCESS' },
			{ name: 'REFUND', value: 'REFUND' },
		],
		default: 'ALL',
	},
	{
		displayName: '压缩类型',
		name: 'tar_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['getBill'] } },
		options: [
			{ name: '不压缩', value: '' },
			{ name: 'GZIP', value: 'GZIP' },
		],
		default: '',
	},
	{
		displayName: '二进制字段名',
		name: 'binaryProperty',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['uploadImage'] } },
		default: 'data',
		description: '输入数据中的图片二进制字段名，支持 JPG/PNG/BMP',
	},
];
