import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['live'], operation: ['createLiving'] };

export const createLivingDescription: INodeProperties[] = [
	{
		displayName: '主播UserID',
		name: 'anchor_userid',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description:
			'直播发起者的 UserID；可与下方选择二选一。<a href="https://developer.work.weixin.qq.com/document/path/93637" target="_blank">官方文档</a>',
		placeholder: 'zhangsan',
	},
	{
		displayName: '主播(选择)',
		name: 'anchor_userid_selected',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: showOnly },
		default: '',
		description: '与上方字符串二选一；均填写时以字符串为准',
	},
	{
		displayName: '直播主题',
		name: 'theme',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: '直播标题，最多 20 个 UTF-8 字符',
	},
	{
		displayName: '直播开始时间',
		name: 'living_start',
		type: 'dateTime',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: '预约开始时间，必须晚于当前时间',
	},
	{
		displayName: '直播持续时长(秒)',
		name: 'living_duration',
		type: 'number',
		required: true,
		displayOptions: { show: showOnly },
		default: 3600,
		typeOptions: { minValue: 1, maxValue: 86400 },
		description: '最长 86400 秒',
	},
	{
		displayName: '直播类型',
		name: 'type',
		type: 'options',
		required: true,
		displayOptions: { show: showOnly },
		options: [
			{ name: '通用直播', value: 0 },
			{ name: '小班课', value: 1 },
			{ name: '大班课', value: 2 },
			{ name: '企业培训', value: 3 },
			{ name: '活动直播', value: 4 },
		],
		default: 0,
		description: '小班课和大班课仅部分行业可发起',
	},
	{
		displayName: '直播简介',
		name: 'description',
		type: 'string',
		displayOptions: { show: { ...showOnly, type: [0, 1, 2, 3] } },
		default: '',
		typeOptions: { rows: 2 },
		description: '最多 100 个 UTF-8 字符；活动直播请填写下方活动详情',
	},
	{
		displayName: '开播提醒提前秒数',
		name: 'remind_time',
		type: 'number',
		displayOptions: { show: showOnly },
		default: 0,
		typeOptions: { minValue: 0 },
		description: '相对于开始时间提前提醒；0 表示不提醒',
	},
	{
		displayName: '直播封面MediaID',
		name: 'activity_cover_mediaid',
		type: 'string',
		displayOptions: { show: { ...showOnly, type: [4] } },
		default: '',
		description: '活动直播间封面图的临时素材 MediaID',
	},
	{
		displayName: '直播分享封面MediaID',
		name: 'activity_share_mediaid',
		type: 'string',
		displayOptions: { show: { ...showOnly, type: [4] } },
		default: '',
		description: '活动直播分享卡片图的临时素材 MediaID',
	},
	{
		displayName: '活动详情文字',
		name: 'activity_detail_description',
		type: 'string',
		displayOptions: { show: { ...showOnly, type: [4] } },
		default: '',
		typeOptions: { rows: 2 },
		description: '活动直播简介，最多 300 个 UTF-8 字符',
	},
	{
		displayName: '活动详情图片MediaID列表',
		name: 'activity_detail_image_list',
		type: 'string',
		displayOptions: { show: { ...showOnly, type: [4] } },
		default: '',
		placeholder: 'MEDIA_ID_1,MEDIA_ID_2',
		description: '最多 5 个，支持逗号、中文逗号、竖线或换行分隔',
	},
	{
		displayName: '应用AgentId',
		name: 'agentid',
		type: 'number',
		displayOptions: { show: showOnly },
		default: 0,
		typeOptions: { minValue: 0 },
		description: '仅旧第三方多应用套件需要；0 表示不传',
	},
];
