import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['live'], operation: ['createLiving'] };

export const createLivingDescription: INodeProperties[] = [
	{
		displayName: '主播UserID',
		name: 'anchor_userid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description:
			'主播员工的 UserID。<a href="https://developer.work.weixin.qq.com/document/path/93637" target="_blank">官方文档</a>',
		placeholder: 'zhangsan',
	},
	{
		displayName: '直播主题',
		name: 'theme',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: 'theme，最多支持 60 个汉字',
		placeholder: '企业微信产品介绍',
	},
	{
		displayName: '直播开始时间',
		name: 'living_start',
		type: 'dateTime',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: 'living_start，Unix 秒级时间戳',
	},
	{
		displayName: '直播持续时长(秒)',
		name: 'living_duration',
		type: 'number',
		required: true,
		displayOptions: { show: showOnly },
		default: 3600,
		description: 'living_duration，最长不超过 86400 秒',
		typeOptions: { minValue: 1, maxValue: 86400 },
	},
	{
		displayName: '直播简介',
		name: 'description',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		typeOptions: { rows: 2 },
		description: 'description，最多支持 300 个汉字',
	},
	{
		displayName: '直播类型',
		name: 'type',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '通用直播', value: 0 },
			{ name: '小班课', value: 1 },
		],
		default: 0,
		description: 'type',
	},
	{
		displayName: '开播提醒时间',
		name: 'remind_time',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '不提醒', value: 0 },
			{ name: '提前1分钟', value: 60 },
		],
		default: 60,
		description: 'remind_time，开播前多久提醒（秒）',
	},
	{
		displayName: '直播封面MediaID',
		name: 'activity_cover_mediaid',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: 'activity_cover_mediaid，临时素材 mediaid',
	},
	{
		displayName: '直播分享封面MediaID',
		name: 'activity_share_mediaid',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: 'activity_share_mediaid',
	},
	{
		displayName: '活动详情文字',
		name: 'activity_detail_description',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		typeOptions: { rows: 2 },
		description: 'activity_detail.description，最多 300 汉字',
	},
	{
		displayName: '活动详情图片URL列表',
		name: 'activity_detail_image_list',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: 'http://url1,http://url2',
		description: 'activity_detail.image_list，逗号分隔，最多 3 张',
	},
	{
		displayName: '应用AgentId',
		name: 'agentid',
		type: 'number',
		displayOptions: { show: showOnly },
		default: 0,
		description: 'agentid，仅旧第三方多应用套件需要；0 不传',
		typeOptions: { minValue: 0 },
	},
	{
		displayName: '可选参数(兼容旧版)',
		name: 'additionalFields',
		type: 'collection',
		placeholder: '添加可选参数',
		default: {},
		displayOptions: { show: showOnly },
		description: '兼容旧工作流；优先使用上方独立字段',
		options: [
			{
				displayName: '活动详情图片URL列表',
				name: 'activity_detail_image_list',
				type: 'string',
				default: '',
			},
			{
				displayName: '活动详情文字',
				name: 'activity_detail_description',
				type: 'string',
				default: '',
			},
			{
				displayName: '开播提醒时间',
				name: 'remind_time',
				type: 'options',
				options: [
					{ name: '不提醒', value: 0 },
					{ name: '提前1分钟', value: 60 },
				],
				default: 60,
			},
			{
				displayName: '应用AgentId',
				name: 'agentid',
				type: 'number',
				default: 0,
			},
			{
				displayName: '直播分享封面MediaID',
				name: 'activity_share_mediaid',
				type: 'string',
				default: '',
			},
			{
				displayName: '直播封面MediaID',
				name: 'activity_cover_mediaid',
				type: 'string',
				default: '',
			},
			{
				displayName: '直播简介',
				name: 'description',
				type: 'string',
				default: '',
			},
			{
				displayName: '直播类型',
				name: 'type',
				type: 'options',
				options: [
					{ name: '通用直播', value: 0 },
					{ name: '小班课', value: 1 },
				],
				default: 0,
			},
		],
	},
];
