import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['live'], operation: ['modifyLiving'] };

export const modifyLivingDescription: INodeProperties[] = [
	{
		displayName: '直播ID',
		name: 'livingid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		placeholder: 'livingid',
		description:
			'livingid。<a href="https://developer.work.weixin.qq.com/document/path/93640" target="_blank">官方文档</a>',
	},
	{
		displayName: '直播主题',
		name: 'theme',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: 'theme，空表示不修改',
	},
	{
		displayName: '直播开始时间',
		name: 'living_start',
		type: 'dateTime',
		displayOptions: { show: showOnly },
		default: '',
		description: 'living_start；空表示不修改',
	},
	{
		displayName: '直播持续时长(秒)',
		name: 'living_duration',
		type: 'number',
		displayOptions: { show: showOnly },
		default: 0,
		description: 'living_duration；0 表示不修改',
		typeOptions: { minValue: 0, maxValue: 86400 },
	},
	{
		displayName: '直播简介',
		name: 'description',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		typeOptions: { rows: 2 },
	},
	{
		displayName: '直播类型',
		name: 'type',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '不修改', value: -1 },
			{ name: '通用直播', value: 0 },
			{ name: '小班课', value: 1 },
		],
		default: -1,
		description: 'type；选「不修改」则不传',
	},
	{
		displayName: '开播提醒时间',
		name: 'remind_time',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '不修改', value: -1 },
			{ name: '不提醒', value: 0 },
			{ name: '提前1分钟', value: 60 },
		],
		default: -1,
		description: 'remind_time',
	},
	{
		displayName: '直播封面MediaID',
		name: 'activity_cover_mediaid',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
	},
	{
		displayName: '直播分享封面MediaID',
		name: 'activity_share_mediaid',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
	},
	{
		displayName: '活动详情文字',
		name: 'activity_detail_description',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		typeOptions: { rows: 2 },
	},
	{
		displayName: '活动详情图片URL列表',
		name: 'activity_detail_image_list',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: 'http://url1,http://url2',
		description: '逗号分隔，最多 3 张',
	},
	{
		displayName: '可选参数(兼容旧版)',
		name: 'additionalFields',
		type: 'collection',
		placeholder: '添加可选参数',
		default: {},
		displayOptions: { show: showOnly },
		description: '兼容旧工作流；优先使用上方独立字段',
		options: [
			{
				displayName: '活动详情图片URL列表',
				name: 'activity_detail_image_list',
				type: 'string',
				default: '',
			},
			{
				displayName: '活动详情文字',
				name: 'activity_detail_description',
				type: 'string',
				default: '',
			},
			{
				displayName: '开播提醒时间',
				name: 'remind_time',
				type: 'options',
				options: [
					{ name: '不提醒', value: 0 },
					{ name: '提前1分钟', value: 60 },
				],
				default: 60,
			},
			{
				displayName: '直播持续时长',
				name: 'living_duration',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 1, maxValue: 86400 },
			},
			{
				displayName: '直播分享封面MediaID',
				name: 'activity_share_mediaid',
				type: 'string',
				default: '',
			},
			{
				displayName: '直播封面MediaID',
				name: 'activity_cover_mediaid',
				type: 'string',
				default: '',
			},
			{
				displayName: '直播简介',
				name: 'description',
				type: 'string',
				default: '',
			},
			{
				displayName: '直播开始时间',
				name: 'living_start',
				type: 'number',
				default: 0,
				description: 'Unix 时间戳秒（旧字段）',
			},
			{
				displayName: '直播类型',
				name: 'type',
				type: 'options',
				options: [
					{ name: '通用直播', value: 0 },
					{ name: '小班课', value: 1 },
				],
				default: 0,
			},
			{
				displayName: '直播主题',
				name: 'theme',
				type: 'string',
				default: '',
			},
		],
	},
];
