import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['live'], operation: ['modifyLiving'] };

export const modifyLivingDescription: INodeProperties[] = [
	{
		displayName: '直播ID',
		name: 'livingid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description:
			'仅允许修改预约状态的直播。<a href="https://developer.work.weixin.qq.com/document/path/93640" target="_blank">官方文档</a>',
	},
	{
		displayName: '修改直播主题',
		name: 'update_theme',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
	},
	{
		displayName: '直播主题',
		name: 'theme',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, update_theme: [true] } },
		default: '',
		description: '最多 60 字节',
	},
	{
		displayName: '修改直播开始时间',
		name: 'update_living_start',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
	},
	{
		displayName: '直播开始时间',
		name: 'living_start',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { ...showOnly, update_living_start: [true] } },
		default: '',
		description: '修改后的开始时间必须晚于当前时间',
	},
	{
		displayName: '修改直播持续时长',
		name: 'update_living_duration',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
	},
	{
		displayName: '直播持续时长(秒)',
		name: 'living_duration',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, update_living_duration: [true] } },
		default: 3600,
		typeOptions: { minValue: 1, maxValue: 86400 },
	},
	{
		displayName: '修改直播简介',
		name: 'update_description',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后允许将简介清空',
	},
	{
		displayName: '直播简介',
		name: 'description',
		type: 'string',
		displayOptions: { show: { ...showOnly, update_description: [true] } },
		default: '',
		typeOptions: { rows: 2 },
		description: '最多 300 字节；留空可清除',
	},
	{
		displayName: '修改直播类型',
		name: 'update_type',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
	},
	{
		displayName: '直播类型',
		name: 'type',
		type: 'options',
		required: true,
		displayOptions: { show: { ...showOnly, update_type: [true] } },
		options: [
			{ name: '通用直播', value: 0 },
			{ name: '小班课', value: 1 },
			{ name: '大班课', value: 2 },
			{ name: '企业培训', value: 3 },
			{ name: '活动直播', value: 4 },
		],
		default: 0,
	},
	{
		displayName: '修改开播提醒',
		name: 'update_remind_time',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
	},
	{
		displayName: '开播提醒提前秒数',
		name: 'remind_time',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, update_remind_time: [true] } },
		default: 0,
		typeOptions: { minValue: 0 },
		description: '0 表示不提醒',
	},
];
