/**
 * Auto-generated catalog of HTTP APIs not yet bound as first-class named ops elsewhere.
 * Source: docs/001-企业内部开发 path diff vs nodes/WeCom (excluding openApi itself).
 * Resource: 开放接口(全量) — catalog option or callCgiBin custom path.
 * Regenerated: 2026-08-11 | count: 130
 *
 * Method default: POST (WeCom majority). Known OAuth/ticket list endpoints forced GET.
 * Excludes: mch XML pay, chatdata SDK-only, bare prefix paths, sandbox/demo.
 */
export type OpenApiEntry = { id: string; name: string; path: string; method: 'GET' | 'POST' };

export const OPEN_API_CATALOG: OpenApiEntry[] = [
	{ id: 'advanced_feature_get_apply_id_list', name: '[advanced_feature] get_apply_id_list', path: '/cgi-bin/advanced_feature/get_apply_id_list', method: 'POST' },
	{ id: 'advanced_feature_set_approval_detail', name: '[advanced_feature] set_approval_detail', path: '/cgi-bin/advanced_feature/set_approval_detail', method: 'POST' },
	{ id: 'aibot_response', name: '[aibot] response', path: '/cgi-bin/aibot/response', method: 'POST' },
	{ id: 'auth_get_tfa_info', name: '[auth] get_tfa_info', path: '/cgi-bin/auth/get_tfa_info', method: 'GET' },
	{ id: 'auth_getuserdetail', name: '[auth] getuserdetail', path: '/cgi-bin/auth/getuserdetail', method: 'GET' },
	{ id: 'auth_getuserinfo', name: '[auth] getuserinfo', path: '/cgi-bin/auth/getuserinfo', method: 'GET' },
	{ id: 'chatdata_upload_media', name: '[chatdata] upload_media', path: '/cgi-bin/chatdata/upload_media', method: 'POST' },
	{ id: 'checkin_clear_checkin_option_array_field', name: '[checkin] clear_checkin_option_array_field', path: '/cgi-bin/checkin/clear_checkin_option_array_field', method: 'POST' },
	{ id: 'corp_getapprovaldata', name: '[corp] getapprovaldata', path: '/cgi-bin/corp/getapprovaldata', method: 'POST' },
	{ id: 'corpgroup_corp_get_chain_corpinfo', name: '[corpgroup] corp/get_chain_corpinfo', path: '/cgi-bin/corpgroup/corp/get_chain_corpinfo', method: 'POST' },
	{ id: 'corpgroup_corp_get_chain_group', name: '[corpgroup] corp/get_chain_group', path: '/cgi-bin/corpgroup/corp/get_chain_group', method: 'POST' },
	{ id: 'corpgroup_unionid_to_pending_id', name: '[corpgroup] unionid_to_pending_id', path: '/cgi-bin/corpgroup/unionid_to_pending_id', method: 'POST' },
	{ id: 'crm_add_msg_template', name: '[crm] add_msg_template', path: '/cgi-bin/crm/add_msg_template', method: 'POST' },
	{ id: 'crm_get_customer_contacts', name: '[crm] get_customer_contacts', path: '/cgi-bin/crm/get_customer_contacts', method: 'POST' },
	{ id: 'crm_get_external_contact', name: '[crm] get_external_contact', path: '/cgi-bin/crm/get_external_contact', method: 'POST' },
	{ id: 'crm_get_external_contact_list', name: '[crm] get_external_contact_list', path: '/cgi-bin/crm/get_external_contact_list', method: 'POST' },
	{ id: 'crm_get_group_msg_result', name: '[crm] get_group_msg_result', path: '/cgi-bin/crm/get_group_msg_result', method: 'POST' },
	{ id: 'crm_get_unassigned_list', name: '[crm] get_unassigned_list', path: '/cgi-bin/crm/get_unassigned_list', method: 'POST' },
	{ id: 'crm_get_user_behavior_data', name: '[crm] get_user_behavior_data', path: '/cgi-bin/crm/get_user_behavior_data', method: 'POST' },
	{ id: 'crm_transfer_external_contact', name: '[crm] transfer_external_contact', path: '/cgi-bin/crm/transfer_external_contact', method: 'POST' },
	{ id: 'externalcontact_add_strategy_tag', name: '[externalcontact] add_strategy_tag', path: '/cgi-bin/externalcontact/add_strategy_tag', method: 'POST' },
	{ id: 'externalcontact_convert_to_openid', name: '[externalcontact] convert_to_openid', path: '/cgi-bin/externalcontact/convert_to_openid', method: 'POST' },
	{ id: 'externalcontact_customer_strategy_create', name: '[externalcontact] customer_strategy/create', path: '/cgi-bin/externalcontact/customer_strategy/create', method: 'POST' },
	{ id: 'externalcontact_customer_strategy_del', name: '[externalcontact] customer_strategy/del', path: '/cgi-bin/externalcontact/customer_strategy/del', method: 'POST' },
	{ id: 'externalcontact_customer_strategy_edit', name: '[externalcontact] customer_strategy/edit', path: '/cgi-bin/externalcontact/customer_strategy/edit', method: 'POST' },
	{ id: 'externalcontact_customer_strategy_get', name: '[externalcontact] customer_strategy/get', path: '/cgi-bin/externalcontact/customer_strategy/get', method: 'POST' },
	{ id: 'externalcontact_customer_strategy_get_range', name: '[externalcontact] customer_strategy/get_range', path: '/cgi-bin/externalcontact/customer_strategy/get_range', method: 'POST' },
	{ id: 'externalcontact_customer_strategy_list', name: '[externalcontact] customer_strategy/list', path: '/cgi-bin/externalcontact/customer_strategy/list', method: 'POST' },
	{ id: 'externalcontact_del_strategy_tag', name: '[externalcontact] del_strategy_tag', path: '/cgi-bin/externalcontact/del_strategy_tag', method: 'POST' },
	{ id: 'externalcontact_edit_strategy_tag', name: '[externalcontact] edit_strategy_tag', path: '/cgi-bin/externalcontact/edit_strategy_tag', method: 'POST' },
	{ id: 'externalcontact_get_group_msg_result', name: '[externalcontact] get_group_msg_result', path: '/cgi-bin/externalcontact/get_group_msg_result', method: 'POST' },
	{ id: 'externalcontact_get_strategy_tag_list', name: '[externalcontact] get_strategy_tag_list', path: '/cgi-bin/externalcontact/get_strategy_tag_list', method: 'POST' },
	{ id: 'externalcontact_get_subscribe_mode', name: '[externalcontact] get_subscribe_mode', path: '/cgi-bin/externalcontact/get_subscribe_mode', method: 'POST' },
	{ id: 'externalcontact_get_subscribe_qr_code', name: '[externalcontact] get_subscribe_qr_code', path: '/cgi-bin/externalcontact/get_subscribe_qr_code', method: 'POST' },
	{ id: 'externalcontact_set_subscribe_mode', name: '[externalcontact] set_subscribe_mode', path: '/cgi-bin/externalcontact/set_subscribe_mode', method: 'POST' },
	{ id: 'externalcontact_transfer', name: '[externalcontact] transfer', path: '/cgi-bin/externalcontact/transfer', method: 'POST' },
	{ id: 'get_jsapi_ticket', name: '[get_jsapi_ticket] get_jsapi_ticket', path: '/cgi-bin/get_jsapi_ticket', method: 'GET' },
	{ id: 'get_launch_code', name: '[get_launch_code] get_launch_code', path: '/cgi-bin/get_launch_code', method: 'POST' },
	{ id: 'meeting_advanced_layout_add', name: '[meeting] advanced_layout/add', path: '/cgi-bin/meeting/advanced_layout/add', method: 'POST' },
	{ id: 'meeting_advanced_layout_apply', name: '[meeting] advanced_layout/apply', path: '/cgi-bin/meeting/advanced_layout/apply', method: 'POST' },
	{ id: 'meeting_advanced_layout_batch_delete', name: '[meeting] advanced_layout/batch_delete', path: '/cgi-bin/meeting/advanced_layout/batch_delete', method: 'POST' },
	{ id: 'meeting_advanced_layout_get_user_layout', name: '[meeting] advanced_layout/get_user_layout', path: '/cgi-bin/meeting/advanced_layout/get_user_layout', method: 'POST' },
	{ id: 'meeting_advanced_layout_list', name: '[meeting] advanced_layout/list', path: '/cgi-bin/meeting/advanced_layout/list', method: 'POST' },
	{ id: 'meeting_advanced_layout_update', name: '[meeting] advanced_layout/update', path: '/cgi-bin/meeting/advanced_layout/update', method: 'POST' },
	{ id: 'meeting_check_device_in_meeting', name: '[meeting] check_device_in_meeting', path: '/cgi-bin/meeting/check_device_in_meeting', method: 'POST' },
	{ id: 'meeting_create_customer_short_url', name: '[meeting] create_customer_short_url', path: '/cgi-bin/meeting/create_customer_short_url', method: 'POST' },
	{ id: 'meeting_enroll_delete', name: '[meeting] enroll/delete', path: '/cgi-bin/meeting/enroll/delete', method: 'POST' },
	{ id: 'meeting_enroll_import', name: '[meeting] enroll/import', path: '/cgi-bin/meeting/enroll/import', method: 'POST' },
	{ id: 'meeting_enroll_query_by_tmp_openid', name: '[meeting] enroll/query_by_tmp_openid', path: '/cgi-bin/meeting/enroll/query_by_tmp_openid', method: 'POST' },
	{ id: 'meeting_get_customer_short_url', name: '[meeting] get_customer_short_url', path: '/cgi-bin/meeting/get_customer_short_url', method: 'POST' },
	{ id: 'meeting_get_guests', name: '[meeting] get_guests', path: '/cgi-bin/meeting/get_guests', method: 'POST' },
	{ id: 'meeting_get_quality', name: '[meeting] get_quality', path: '/cgi-bin/meeting/get_quality', method: 'POST' },
	{ id: 'meeting_layout_add', name: '[meeting] layout/add', path: '/cgi-bin/meeting/layout/add', method: 'POST' },
	{ id: 'meeting_layout_add_background', name: '[meeting] layout/add_background', path: '/cgi-bin/meeting/layout/add_background', method: 'POST' },
	{ id: 'meeting_layout_batch_delete_background', name: '[meeting] layout/batch_delete_background', path: '/cgi-bin/meeting/layout/batch_delete_background', method: 'POST' },
	{ id: 'meeting_layout_delete_background', name: '[meeting] layout/delete_background', path: '/cgi-bin/meeting/layout/delete_background', method: 'POST' },
	{ id: 'meeting_layout_list_background', name: '[meeting] layout/list_background', path: '/cgi-bin/meeting/layout/list_background', method: 'POST' },
	{ id: 'meeting_layout_set_default_background', name: '[meeting] layout/set_default_background', path: '/cgi-bin/meeting/layout/set_default_background', method: 'POST' },
	{ id: 'meeting_layout_update', name: '[meeting] layout/update', path: '/cgi-bin/meeting/layout/update', method: 'POST' },
	{ id: 'meeting_mra_hangup', name: '[meeting] mra/hangup', path: '/cgi-bin/meeting/mra/hangup', method: 'POST' },
	{ id: 'meeting_mra_query_status', name: '[meeting] mra/query_status', path: '/cgi-bin/meeting/mra/query_status', method: 'POST' },
	{ id: 'meeting_mra_set_default_layout', name: '[meeting] mra/set_default_layout', path: '/cgi-bin/meeting/mra/set_default_layout', method: 'POST' },
	{ id: 'meeting_mra_set_raise_hand', name: '[meeting] mra/set_raise_hand', path: '/cgi-bin/meeting/mra/set_raise_hand', method: 'POST' },
	{ id: 'meeting_phone_get_tmp_openid', name: '[meeting] phone/get_tmp_openid', path: '/cgi-bin/meeting/phone/get_tmp_openid', method: 'POST' },
	{ id: 'meeting_poll_create_theme', name: '[meeting] poll/create_theme', path: '/cgi-bin/meeting/poll/create_theme', method: 'POST' },
	{ id: 'meeting_poll_delete', name: '[meeting] poll/delete', path: '/cgi-bin/meeting/poll/delete', method: 'POST' },
	{ id: 'meeting_poll_finish', name: '[meeting] poll/finish', path: '/cgi-bin/meeting/poll/finish', method: 'POST' },
	{ id: 'meeting_poll_get_theme_info', name: '[meeting] poll/get_theme_info', path: '/cgi-bin/meeting/poll/get_theme_info', method: 'POST' },
	{ id: 'meeting_poll_start', name: '[meeting] poll/start', path: '/cgi-bin/meeting/poll/start', method: 'POST' },
	{ id: 'meeting_poll_update_theme', name: '[meeting] poll/update_theme', path: '/cgi-bin/meeting/poll/update_theme', method: 'POST' },
	{ id: 'meeting_realcontrol_close_screen_share', name: '[meeting] realcontrol/close_screen_share', path: '/cgi-bin/meeting/realcontrol/close_screen_share', method: 'POST' },
	{ id: 'meeting_realcontrol_manage_waiting_room_users', name: '[meeting] realcontrol/manage_waiting_room_users', path: '/cgi-bin/meeting/realcontrol/manage_waiting_room_users', method: 'POST' },
	{ id: 'meeting_realcontrol_set_nicknames', name: '[meeting] realcontrol/set_nicknames', path: '/cgi-bin/meeting/realcontrol/set_nicknames', method: 'POST' },
	{ id: 'meeting_realcontrol_switch_user_video', name: '[meeting] realcontrol/switch_user_video', path: '/cgi-bin/meeting/realcontrol/switch_user_video', method: 'POST' },
	{ id: 'meeting_record_delete', name: '[meeting] record/delete', path: '/cgi-bin/meeting/record/delete', method: 'POST' },
	{ id: 'meeting_record_delete_file', name: '[meeting] record/delete_file', path: '/cgi-bin/meeting/record/delete_file', method: 'POST' },
	{ id: 'meeting_record_get_file_list', name: '[meeting] record/get_file_list', path: '/cgi-bin/meeting/record/get_file_list', method: 'POST' },
	{ id: 'meeting_record_get_statistics', name: '[meeting] record/get_statistics', path: '/cgi-bin/meeting/record/get_statistics', method: 'POST' },
	{ id: 'meeting_record_transcript_get_detail', name: '[meeting] record/transcript/get_detail', path: '/cgi-bin/meeting/record/transcript/get_detail', method: 'POST' },
	{ id: 'meeting_record_transcript_get_paragraph_list', name: '[meeting] record/transcript/get_paragraph_list', path: '/cgi-bin/meeting/record/transcript/get_paragraph_list', method: 'POST' },
	{ id: 'meeting_record_transcript_search', name: '[meeting] record/transcript/search', path: '/cgi-bin/meeting/record/transcript/search', method: 'POST' },
	{ id: 'meeting_record_update_sharing_config', name: '[meeting] record/update_sharing_config', path: '/cgi-bin/meeting/record/update_sharing_config', method: 'POST' },
	{ id: 'meeting_rooms_call', name: '[meeting] rooms/call', path: '/cgi-bin/meeting/rooms/call', method: 'POST' },
	{ id: 'meeting_rooms_cancel_call', name: '[meeting] rooms/cancel_call', path: '/cgi-bin/meeting/rooms/cancel_call', method: 'POST' },
	{ id: 'meeting_rooms_get_config', name: '[meeting] rooms/get_config', path: '/cgi-bin/meeting/rooms/get_config', method: 'POST' },
	{ id: 'meeting_rooms_get_inventory', name: '[meeting] rooms/get_inventory', path: '/cgi-bin/meeting/rooms/get_inventory', method: 'POST' },
	{ id: 'meeting_rooms_get_response_status', name: '[meeting] rooms/get_response_status', path: '/cgi-bin/meeting/rooms/get_response_status', method: 'POST' },
	{ id: 'meeting_rooms_list_controllers', name: '[meeting] rooms/list_controllers', path: '/cgi-bin/meeting/rooms/list_controllers', method: 'POST' },
	{ id: 'meeting_rooms_list_devices', name: '[meeting] rooms/list_devices', path: '/cgi-bin/meeting/rooms/list_devices', method: 'POST' },
	{ id: 'meeting_rooms_list_meetings', name: '[meeting] rooms/list_meetings', path: '/cgi-bin/meeting/rooms/list_meetings', method: 'POST' },
	{ id: 'meeting_set_guests', name: '[meeting] set_guests', path: '/cgi-bin/meeting/set_guests', method: 'POST' },
	{ id: 'meeting_set_invitees', name: '[meeting] set_invitees', path: '/cgi-bin/meeting/set_invitees', method: 'POST' },
	{ id: 'meeting_vip_batch_del_job_result', name: '[meeting] vip/batch_del_job_result', path: '/cgi-bin/meeting/vip/batch_del_job_result', method: 'POST' },
	{ id: 'meeting_waitingroom_get_current_user_list', name: '[meeting] waitingroom/get_current_user_list', path: '/cgi-bin/meeting/waitingroom/get_current_user_list', method: 'POST' },
	{ id: 'meeting_waitingroom_get_user_list', name: '[meeting] waitingroom/get_user_list', path: '/cgi-bin/meeting/waitingroom/get_user_list', method: 'POST' },
	{ id: 'meeting_webinar_cancel', name: '[meeting] webinar/cancel', path: '/cgi-bin/meeting/webinar/cancel', method: 'POST' },
	{ id: 'meeting_webinar_create', name: '[meeting] webinar/create', path: '/cgi-bin/meeting/webinar/create', method: 'POST' },
	{ id: 'meeting_webinar_enroll_approve', name: '[meeting] webinar/enroll/approve', path: '/cgi-bin/meeting/webinar/enroll/approve', method: 'POST' },
	{ id: 'meeting_webinar_enroll_delete', name: '[meeting] webinar/enroll/delete', path: '/cgi-bin/meeting/webinar/enroll/delete', method: 'POST' },
	{ id: 'meeting_webinar_enroll_get_config', name: '[meeting] webinar/enroll/get_config', path: '/cgi-bin/meeting/webinar/enroll/get_config', method: 'POST' },
	{ id: 'meeting_webinar_enroll_import', name: '[meeting] webinar/enroll/import', path: '/cgi-bin/meeting/webinar/enroll/import', method: 'POST' },
	{ id: 'meeting_webinar_enroll_list', name: '[meeting] webinar/enroll/list', path: '/cgi-bin/meeting/webinar/enroll/list', method: 'POST' },
	{ id: 'meeting_webinar_enroll_query_by_tmp_openid', name: '[meeting] webinar/enroll/query_by_tmp_openid', path: '/cgi-bin/meeting/webinar/enroll/query_by_tmp_openid', method: 'POST' },
	{ id: 'meeting_webinar_enroll_set_config', name: '[meeting] webinar/enroll/set_config', path: '/cgi-bin/meeting/webinar/enroll/set_config', method: 'POST' },
	{ id: 'meeting_webinar_get', name: '[meeting] webinar/get', path: '/cgi-bin/meeting/webinar/get', method: 'POST' },
	{ id: 'meeting_webinar_list_guest', name: '[meeting] webinar/list_guest', path: '/cgi-bin/meeting/webinar/list_guest', method: 'POST' },
	{ id: 'meeting_webinar_update', name: '[meeting] webinar/update', path: '/cgi-bin/meeting/webinar/update', method: 'POST' },
	{ id: 'meeting_webinar_update_guest_list', name: '[meeting] webinar/update_guest_list', path: '/cgi-bin/meeting/webinar/update_guest_list', method: 'POST' },
	{ id: 'meeting_webinar_update_warm_up', name: '[meeting] webinar/update_warm_up', path: '/cgi-bin/meeting/webinar/update_warm_up', method: 'POST' },
	{ id: 'miniapppay_upload_image', name: '[miniapppay] upload_image', path: '/cgi-bin/miniapppay/upload_image', method: 'POST' },
	{ id: 'miniprogram_jscode2session', name: '[miniprogram] jscode2session', path: '/cgi-bin/miniprogram/jscode2session', method: 'GET' },
	{ id: 'school_department_create', name: '[school] department/create', path: '/cgi-bin/school/department/create', method: 'POST' },
	{ id: 'school_department_delete', name: '[school] department/delete', path: '/cgi-bin/school/department/delete', method: 'POST' },
	{ id: 'school_department_list', name: '[school] department/list', path: '/cgi-bin/school/department/list', method: 'GET' },
	{ id: 'school_department_update', name: '[school] department/update', path: '/cgi-bin/school/department/update', method: 'POST' },
	{ id: 'school_get_chat_create_mode', name: '[school] get_chat_create_mode', path: '/cgi-bin/school/get_chat_create_mode', method: 'POST' },
	{ id: 'school_getuserinfo', name: '[school] getuserinfo', path: '/cgi-bin/school/getuserinfo', method: 'GET' },
	{ id: 'school_living_get_living_info', name: '[school] living/get_living_info', path: '/cgi-bin/school/living/get_living_info', method: 'POST' },
	{ id: 'school_living_get_unwatch_stat', name: '[school] living/get_unwatch_stat', path: '/cgi-bin/school/living/get_unwatch_stat', method: 'POST' },
	{ id: 'school_living_get_watch_stat', name: '[school] living/get_watch_stat', path: '/cgi-bin/school/living/get_watch_stat', method: 'POST' },
	{ id: 'school_set_arch_sync_mode', name: '[school] set_arch_sync_mode', path: '/cgi-bin/school/set_arch_sync_mode', method: 'POST' },
	{ id: 'school_set_chat_create_mode', name: '[school] set_chat_create_mode', path: '/cgi-bin/school/set_chat_create_mode', method: 'POST' },
	{ id: 'school_set_upgrade_info', name: '[school] set_upgrade_info', path: '/cgi-bin/school/set_upgrade_info', method: 'POST' },
	{ id: 'school_user_list', name: '[school] user/list', path: '/cgi-bin/school/user/list', method: 'GET' },
	{ id: 'school_user_list_parent', name: '[school] user/list_parent', path: '/cgi-bin/school/user/list_parent', method: 'GET' },
	{ id: 'ticket_get', name: '[ticket] get', path: '/cgi-bin/ticket/get', method: 'GET' },
	{ id: 'user_getuserinfo', name: '[user] getuserinfo', path: '/cgi-bin/user/getuserinfo', method: 'GET' },
	{ id: 'user_tfa_succ', name: '[user] tfa_succ', path: '/cgi-bin/user/tfa_succ', method: 'POST' },
	{ id: 'webhook_send', name: '[webhook] send', path: '/cgi-bin/webhook/send', method: 'POST' },
	{ id: 'wedrive_get_file_permission', name: '[wedrive] get_file_permission', path: '/cgi-bin/wedrive/get_file_permission', method: 'POST' },
];

export const OPEN_API_BY_ID: Record<string, OpenApiEntry> = Object.fromEntries(
	OPEN_API_CATALOG.map((e) => [e.id, e]),
);
