import type { INodeProperties } from 'n8n-workflow';

const showOnly = {
	resource: ['mail'],
	operation: ['createPublicMailbox'],
};

export const createPublicMailboxDescription: INodeProperties[] = [
	{
		displayName: '公共邮箱地址',
		name: 'email',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		placeholder: 'apitest@gzdev.com',
		description:
			'公共邮箱地址 email。<a href="https://developer.work.weixin.qq.com/document/path/95511" target="_blank">官方文档</a>',
	},
	{
		displayName: '公共邮箱名称',
		name: 'name',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		placeholder: '客户服务',
		description: '公共邮箱名称，换算长度最多 64（英文计 1，汉字计 2）',
	},
	{
		displayName: '成员UserID列表',
		name: 'userid_list',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: 'zhangsan,lisi',
		description: '有权限使用的成员 UserID；与下方选择合并。三类使用范围不能同时为空',
	},
	{
		displayName: '成员(选择)',
		name: 'userid_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: showOnly },
		default: [],
		description: '与上方列表合并去重',
	},
	{
		displayName: '成员列表 JSON',
		name: 'useridListJson',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '部门ID列表',
		name: 'department_list',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: '1,2',
		description: '有权限使用的部门 ID；与下方选择合并',
	},
	{
		displayName: '部门(选择)',
		name: 'department_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getDepartments' },
		displayOptions: { show: showOnly },
		default: [],
		description: '与上方列表合并去重',
	},
	{
		displayName: '标签ID列表',
		name: 'tag_list',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: '1,2',
		description: '有权限使用的标签 ID；与下方选择合并；支持逗号、中文逗号、竖线或换行分隔',
	},
	{
		displayName: '标签(选择)',
		name: 'tag_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getTags' },
		displayOptions: { show: showOnly },
		default: [],
		description: '与上方标签列表合并去重',
	},
	{
		displayName: '创建客户端专用密码',
		name: 'create_auth_code',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '否', value: 0 },
			{ name: '是', value: 1 },
		],
		default: 0,
		description: '是否同时创建客户端专用密码 create_auth_code',
	},
	{
		displayName: '专用密码备注',
		name: 'auth_code_remark',
		type: 'string',
		displayOptions: { show: { ...showOnly, create_auth_code: [1] } },
		default: '',
		description: '客户端专用密码的备注说明，最长 128 字节',
	},
];
