import type { INodeProperties } from 'n8n-workflow';

const showOnlyForCreate = {
	resource: ['contact'],
	operation: ['createUser'],
};

export const createUserDescription: INodeProperties[] = [
	{
		displayName: 'UserID',
		name: 'userid',
		type: 'string',
		required: true,
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: 'zhangsan',
		description: '成员 UserID，企业内必须唯一。长度为1~64个字节，只能由数字、字母和"_-@."四种字符组成，且第一个字符必须是字母或数字。如：zhangsan。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '姓名',
		name: 'name',
		type: 'string',
		required: true,
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: '张三',
		description: '成员名称，长度为1~64个utf8字符。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '手机号',
		name: 'mobile',
		type: 'string',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: '13800138000',
		description: '可选。手机号码，企业内必须唯一，mobile/email 二者不能同时为空。11位手机号码。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '所属部门',
		name: 'department',
		type: 'string',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: '1,2,3',
		description: '可选。成员所属部门 ID 列表，不超过 100 个。多个部门用逗号分隔；不填写或填写 0 时，成员会放入「其他（待设置部门）」。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '职务信息',
		name: 'position',
		type: 'string',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: '产品经理',
		description: '可选。职务信息，长度为0~128个字符。成员的职位/岗位名称。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '性别',
		name: 'gender',
		type: 'options',
		displayOptions: {
			show: showOnlyForCreate,
		},
		options: [
			{
				name: '未指定',
				value: '',
			},
			{
				name: '男',
				value: '1',
			},
			{
				name: '女',
				value: '2',
			},
		],
		default: '',
		description: '可选。性别。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '邮箱',
		name: 'email',
		type: 'string',
		placeholder: 'zhangsan@example.com',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		description: '可选。邮箱地址，长度6~64个字节，且为有效的 email 格式。企业内必须唯一，mobile/email 二者不能同时为空。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '企业邮箱',
		name: 'biz_mail',
		type: 'string',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: 'zhangsan@company.com',
		description: '可选。企业邮箱，仅对开通企业邮箱的企业有效。长度6~64个字节，且为有效的企业邮箱格式。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '地址',
		name: 'address',
		type: 'string',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: '北京市海淀区...',
		description: '可选。地址，长度最大128个字符。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '别名',
		name: 'alias',
		type: 'string',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: 'jackzhang',
		description: '可选。成员别名，长度1~64个utf8字符。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '座机',
		name: 'telephone',
		type: 'string',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: '010-12345678',
		description: '可选。座机号码，32字节以内，由纯数字、"-"、"+" 或 "," 组成。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '启用状态',
		name: 'enable',
		type: 'options',
		displayOptions: {
			show: showOnlyForCreate,
		},
		options: [
			{
				name: '启用',
				value: 1,
			},
			{
				name: '禁用',
				value: 0,
			},
		],
		default: 1,
		description: '是否启用成员。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '头像MediaID',
		name: 'avatar_mediaid',
		type: 'string',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: '请输入头像的 media_id...',
		description: '可选。成员头像的 mediaid，通过素材管理接口上传图片获得。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '对外企业简称',
		name: 'external_corp_name',
		type: 'string',
		displayOptions: { show: showOnlyForCreate },
		default: '',
		description: 'external_profile.external_corp_name',
	},
	{
		displayName: '视频号昵称',
		name: 'wechat_channels_nickname',
		type: 'string',
		displayOptions: { show: showOnlyForCreate },
		default: '',
		description: 'external_profile.wechat_channels.nickname',
	},
	{
		displayName: '对外扩展属性',
		name: 'externalAttrCollection',
		type: 'fixedCollection',
		displayOptions: { show: showOnlyForCreate },
		default: {},
		placeholder: '添加对外属性',
		typeOptions: { multipleValues: true },
		description: 'external_profile.external_attr',
		options: [
			{
				displayName: '属性',
				name: 'attrs',
				values: [
					{
						displayName: '类型',
						name: 'type',
						type: 'options',
						options: [
							{ name: '文本', value: 0 },
							{ name: '网页', value: 1 },
							{ name: '小程序', value: 2 },
						],
						default: 0,
					},
					{ displayName: '属性名称', name: 'name', type: 'string', default: '' },
					{
						displayName: '文本值',
						name: 'text_value',
						type: 'string',
						displayOptions: { show: { type: [0] } },
						default: '',
					},
					{
						displayName: '网页标题',
						name: 'web_title',
						type: 'string',
						displayOptions: { show: { type: [1] } },
						default: '',
					},
					{
						displayName: '网页URL',
						name: 'web_url',
						type: 'string',
						displayOptions: { show: { type: [1] } },
						default: '',
					},
					{
						displayName: '小程序AppID',
						name: 'miniprogram_appid',
						type: 'string',
						displayOptions: { show: { type: [2] } },
						default: '',
					},
					{
						displayName: '小程序页面',
						name: 'miniprogram_pagepath',
						type: 'string',
						displayOptions: { show: { type: [2] } },
						default: '',
					},
					{
						displayName: '小程序标题',
						name: 'miniprogram_title',
						type: 'string',
						displayOptions: { show: { type: [2] } },
						default: '',
					},
				],
			},
		],
	},
	{
		displayName: '成员对外属性扩展JSON',
		name: 'external_profile',
		type: 'json',
		displayOptions: { show: showOnlyForCreate },
		default: '{}',
		description: '与上方字段合并，JSON 优先',
	},
	{
		displayName: '是否邀请该成员使用企业微信',
		name: 'to_invite',
		type: 'boolean',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: true,
		description: '默认值为 true。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '部门排序值',
		name: 'order',
		type: 'string',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: '10,40',
		description: '可选。部门内的排序值，默认为0，成员次序以创建时间从小到大排列。个数必须和参数department的个数一致，数值越大排序越前面。有效的值范围是[0, 2^32)。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '是否为部门负责人',
		name: 'is_leader_in_dept',
		type: 'string',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: '1,0',
		description: '可选。个数必须和参数department的个数一致，表示在所在的部门内是否为部门负责人。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '直属上级UserID',
		name: 'direct_leader',
		type: 'string',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: 'lisi',
		description: '可选。直属上级UserID，设置范围为企业内成员，可以设置最多1个上级。多个值用逗号分隔，但API仅支持最多1个上级。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '主部门',
		name: 'main_department',
		type: 'number',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: 0,
		description: '可选。主部门。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
	{
		displayName: '扩展属性',
		name: 'extattrCollection',
		type: 'fixedCollection',
		displayOptions: { show: showOnlyForCreate },
		default: {},
		placeholder: '添加扩展属性',
		typeOptions: { multipleValues: true },
		description: 'extattr.attrs，需先在管理端配置同名属性',
		options: [
			{
				displayName: '属性',
				name: 'attrs',
				values: [
					{
						displayName: '类型',
						name: 'type',
						type: 'options',
						options: [
							{ name: '文本', value: 0 },
							{ name: '网页', value: 1 },
						],
						default: 0,
					},
					{ displayName: '属性名称', name: 'name', type: 'string', default: '' },
					{
						displayName: '文本值',
						name: 'text_value',
						type: 'string',
						displayOptions: { show: { type: [0] } },
						default: '',
					},
					{
						displayName: '网页标题',
						name: 'web_title',
						type: 'string',
						displayOptions: { show: { type: [1] } },
						default: '',
					},
					{
						displayName: '网页URL',
						name: 'web_url',
						type: 'string',
						displayOptions: { show: { type: [1] } },
						default: '',
					},
				],
			},
		],
	},
	{
		displayName: '扩展属性扩展JSON',
		name: 'extattr',
		type: 'json',
		displayOptions: { show: showOnlyForCreate },
		default: '{}',
		description: '与上方合并，JSON 优先',
	},
	{
		displayName: '对外职务',
		name: 'external_position',
		type: 'string',
		displayOptions: {
			show: showOnlyForCreate,
		},
		default: '',
		placeholder: '高级产品经理',
		description: '可选。对外职务，如果设置了该值，则以此作为对外展示的职务，否则以position来展示。长度12个汉字内。<a href="https://developer.work.weixin.qq.com/document/path/90195" target="_blank">官方文档</a>',
	},
];
