import type { INodeProperties } from 'n8n-workflow';

const showOnlyForUpdate = {
	resource: ['contact'],
	operation: ['updateUser'],
};

export const updateUserDescription: INodeProperties[] = [
	{
		displayName: 'UserID',
		name: 'userid',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: 'zhangsan',
		description: '成员 UserID，企业内必须唯一。不区分大小写，长度为1~64个字节。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>；可与下方选择二选一',
	},
	{
		displayName: '成员(选择)',
		name: 'userid_selected',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: '',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		description: '与上方字符串二选一；均填写时以字符串为准',
	},
	{
		displayName: '姓名',
		name: 'name',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: '张三',
		description: '可选。成员名称，长度为1~64个utf8字符。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '手机号',
		name: 'mobile',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: '13800138000',
		description: '可选。手机号码，企业内必须唯一。若成员已激活企业微信，则需成员自行修改（此情况下该参数被忽略，但不会报错）。中国大陆手机号码可省略"+86"，其他国家或地区必须要带上国际码。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '所属部门',
		name: 'department',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: '1,2,3',
		description: '可选。成员所属部门 ID 列表，不超过100个。多个部门用逗号分隔。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '职务信息',
		name: 'position',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: '产品经理',
		description: '可选。职务信息，长度为0~128个字符。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '性别',
		name: 'gender',
		type: 'options',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		options: [
			{
				name: '不修改',
				value: '',
			},
			{
				name: '男',
				value: '1',
			},
			{
				name: '女',
				value: '2',
			},
		],
		default: '',
		description: '可选。性别。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '邮箱',
		name: 'email',
		type: 'string',
		placeholder: 'zhangsan@example.com',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		description: '可选。邮箱地址，长度6~64个字节，且为有效的 email 格式。企业内必须唯一。可填写企业已有的邮箱账号，方便同事获取成员的邮箱账号以发邮件。境外成员可用此邮箱登录企业微信。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '企业邮箱',
		name: 'biz_mail',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: 'zhangsan@company.com',
		description: '可选。如果企业已开通腾讯企业邮（企业微信邮箱），设置该值可创建企业邮箱账号。长度6~63个字节，且为有效的企业邮箱格式。企业内必须唯一。未填写则系统会为用户生成默认企业邮箱（由系统生成的邮箱可修改一次）。如果创建时「企业邮箱」为系统默认分配的，则仅允许修改一次。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '地址',
		name: 'address',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: '北京市海淀区...',
		description: '可选。地址，长度最大128个字符。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '别名',
		name: 'alias',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: 'jackzhang',
		description: '可选。成员别名，长度1~64个utf8字符。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '座机',
		name: 'telephone',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: '010-12345678',
		description: '可选。座机号码，32字节以内，由纯数字、"-"、"+" 或 "," 组成。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '启用状态',
		name: 'enable',
		type: 'options',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		options: [
			{
				name: '不修改',
				value: -1,
			},
			{
				name: '启用',
				value: 1,
			},
			{
				name: '禁用',
				value: 0,
			},
		],
		default: -1,
		description: '是否启用成员。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '头像MediaID',
		name: 'avatar_mediaid',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: '请输入头像的 media_id...',
		description: '可选。成员头像的 mediaid，通过素材管理接口上传图片获得。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '对外企业简称',
		name: 'external_corp_name',
		type: 'string',
		displayOptions: { show: showOnlyForUpdate },
		default: '',
	},
	{
		displayName: '视频号昵称',
		name: 'wechat_channels_nickname',
		type: 'string',
		displayOptions: { show: showOnlyForUpdate },
		default: '',
	},
	{
		displayName: '对外扩展属性',
		name: 'externalAttrCollection',
		type: 'fixedCollection',
		displayOptions: { show: showOnlyForUpdate },
		default: {},
		placeholder: '添加对外属性',
		typeOptions: { multipleValues: true },
		options: [
			{
				displayName: '属性',
				name: 'attrs',
				values: [
					{
						displayName: '类型',
						name: 'type',
						type: 'options',
						options: [
							{ name: '文本', value: 0 },
							{ name: '网页', value: 1 },
							{ name: '小程序', value: 2 },
						],
						default: 0,
					},
					{ displayName: '属性名称', name: 'name', type: 'string', default: '' },
					{
						displayName: '文本值',
						name: 'text_value',
						type: 'string',
						displayOptions: { show: { type: [0] } },
						default: '',
					},
					{
						displayName: '网页标题',
						name: 'web_title',
						type: 'string',
						displayOptions: { show: { type: [1] } },
						default: '',
					},
					{
						displayName: '网页URL',
						name: 'web_url',
						type: 'string',
						displayOptions: { show: { type: [1] } },
						default: '',
					},
					{
						displayName: '小程序AppID',
						name: 'miniprogram_appid',
						type: 'string',
						displayOptions: { show: { type: [2] } },
						default: '',
					},
					{
						displayName: '小程序页面',
						name: 'miniprogram_pagepath',
						type: 'string',
						displayOptions: { show: { type: [2] } },
						default: '',
					},
					{
						displayName: '小程序标题',
						name: 'miniprogram_title',
						type: 'string',
						displayOptions: { show: { type: [2] } },
						default: '',
					},
				],
			},
		],
	},
	{
		displayName: '成员对外属性扩展JSON',
		name: 'external_profile',
		type: 'json',
		displayOptions: { show: showOnlyForUpdate },
		default: '{}',
		description: '与上方合并，JSON 优先',
	},
	{
		displayName: '部门排序值',
		name: 'order',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: '10,40',
		description: '可选。部门内的排序值，默认为0。当有传入department时有效。数量必须和department一致，数值越大排序越前面。有效的值范围是[0, 2^32)。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '是否为部门负责人',
		name: 'is_leader_in_dept',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: '1,0',
		description: '可选。部门负责人字段，个数必须和department一致，表示在所在的部门内是否为负责人。0-否，1-是。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '直属上级UserID',
		name: 'direct_leader',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: 'lisi',
		description: '可选。直属上级，可以设置企业范围内成员为直属上级，最多设置1个。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '主部门',
		name: 'main_department',
		type: 'number',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: 0,
		description: '可选。主部门。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
	{
		displayName: '扩展属性',
		name: 'extattrCollection',
		type: 'fixedCollection',
		displayOptions: { show: showOnlyForUpdate },
		default: {},
		placeholder: '添加扩展属性',
		typeOptions: { multipleValues: true },
		options: [
			{
				displayName: '属性',
				name: 'attrs',
				values: [
					{
						displayName: '类型',
						name: 'type',
						type: 'options',
						options: [
							{ name: '文本', value: 0 },
							{ name: '网页', value: 1 },
						],
						default: 0,
					},
					{ displayName: '属性名称', name: 'name', type: 'string', default: '' },
					{
						displayName: '文本值',
						name: 'text_value',
						type: 'string',
						displayOptions: { show: { type: [0] } },
						default: '',
					},
					{
						displayName: '网页标题',
						name: 'web_title',
						type: 'string',
						displayOptions: { show: { type: [1] } },
						default: '',
					},
					{
						displayName: '网页URL',
						name: 'web_url',
						type: 'string',
						displayOptions: { show: { type: [1] } },
						default: '',
					},
				],
			},
		],
	},
	{
		displayName: '扩展属性扩展JSON',
		name: 'extattr',
		type: 'json',
		displayOptions: { show: showOnlyForUpdate },
		default: '{}',
		description: '与上方合并，JSON 优先',
	},
	{
		displayName: '对外职务',
		name: 'external_position',
		type: 'string',
		displayOptions: { show: showOnlyForUpdate },
		default: '',
		description: '不超过 12 个汉字',
	},
	{
		displayName: '企业邮箱别名',
		name: 'biz_mail_alias_list',
		type: 'string',
		displayOptions: { show: showOnlyForUpdate },
		default: '',
		placeholder: 'a@corp.com,b@corp.com',
		description: '逗号分隔，最多 5 个；清空请用扩展 JSON 传空数组',
	},
	{
		displayName: '企业邮箱别名扩展JSON',
		name: 'biz_mail_alias',
		type: 'json',
		displayOptions: { show: showOnlyForUpdate },
		default: '{}',
		description: '如 {"item":["a@corp.com"]}，优先于上方列表',
	},
	{
		displayName: '新UserID',
		name: 'new_userid',
		type: 'string',
		displayOptions: {
			show: showOnlyForUpdate,
		},
		default: '',
		placeholder: 'new_zhangsan',
		description: '可选。如果userid由系统自动生成，则仅允许修改一次。新值可由new_userid字段指定。<a href="https://developer.work.weixin.qq.com/document/path/90197" target="_blank">官方文档</a>',
	},
];
