import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['wedoc'], operation: ['modDocShareScope'] };

const authOptions = [
	{ name: '只读', value: 1, description: '成员仅可查看内容' },
	{ name: '可编辑', value: 2, description: '成员可编辑内容，数据可被接口获取' },
];

export const modDocShareScopeDescription: INodeProperties[] = [
	{
		displayName: '文档ID',
		name: 'docid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: '操作的 docid，可用于文档、表格、智能表格',
	},
	{
		displayName: '更新企业内成员加入规则',
		name: 'updateInternalJoinRule',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后覆盖企业内成员的加入规则',
	},
	{
		displayName: '允许企业内成员浏览',
		name: 'enable_corp_internal',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, updateInternalJoinRule: [true] } },
		default: true,
		description: '企业内成员主动查看文档后是否允许加入',
	},
	{
		displayName: '企业内成员加入后权限',
		name: 'corp_internal_auth',
		type: 'options',
		displayOptions: { show: { ...showOnly, updateInternalJoinRule: [true] } },
		default: 2,
		options: authOptions,
		description: '企业内成员主动查看后获得的权限',
	},
	{
		displayName: '企业内成员仅管理员审批',
		name: 'corp_internal_approve_only_by_admin',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, updateInternalJoinRule: [true] } },
		default: false,
		description: '是否要求企业内成员加入时必须由管理员审批',
	},
	{
		displayName: '更新企业外成员加入规则',
		name: 'updateExternalJoinRule',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后覆盖企业外成员的加入规则',
	},
	{
		displayName: '允许企业外成员浏览',
		name: 'enable_corp_external',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, updateExternalJoinRule: [true] } },
		default: false,
		description: '企业外成员主动查看文档后是否允许加入',
	},
	{
		displayName: '企业外成员加入后权限',
		name: 'corp_external_auth',
		type: 'options',
		displayOptions: { show: { ...showOnly, updateExternalJoinRule: [true] } },
		default: 1,
		options: authOptions,
		description: '企业外成员主动查看后获得的权限',
	},
	{
		displayName: '企业外成员仅管理员审批',
		name: 'corp_external_approve_only_by_admin',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, updateExternalJoinRule: [true] } },
		default: true,
		description: '是否要求企业外成员加入时必须由管理员审批',
	},
	{
		displayName: '更新禁止对外分享设置',
		name: 'updateBanShareExternal',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后覆盖是否允许分享给企业外部人员',
	},
	{
		displayName: '禁止对外分享',
		name: 'ban_share_external',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, updateBanShareExternal: [true] } },
		default: false,
		description: '是否禁止文档分享到企业外',
	},
	{
		displayName: '更新特定部门加入权限',
		name: 'update_co_auth_list',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后覆盖特定部门列表，留空列表时清空',
	},
	{
		displayName: '特定部门列表',
		name: 'coAuthCollection',
		type: 'fixedCollection',
		displayOptions: { show: { ...showOnly, update_co_auth_list: [true] } },
		default: {},
		placeholder: '添加部门',
		typeOptions: { multipleValues: true },
		description: '指定文档查看权限的部门列表，留空表示清空；下方 JSON 非空时覆盖表单',
		options: [
			{
				displayName: '部门',
				name: 'departments',
				values: [
					{
						displayName: '部门ID',
						name: 'departmentid',
						type: 'number',
						default: 0,
						description: '可与下方选择二选一',
					},
					{
						displayName: '部门(选择)',
						name: 'departmentid_selected',
						type: 'options',
						typeOptions: { loadOptionsMethod: 'getDepartments' },
						default: '',
						description: '与上方部门 ID 二选一；均填写时以数字字段为准',
					},
					{
						displayName: '权限',
						name: 'auth',
						type: 'options',
						default: 1,
						options: authOptions,
						description: '部门加入后获得的权限',
					},
				],
			},
		],
	},
	{
		displayName: '特定部门列表 JSON',
		name: 'coAuthListJson',
		type: 'json',
		displayOptions: { show: { ...showOnly, update_co_auth_list: [true] } },
		default: '[]',
		description:
			'可选。非空数组时覆盖上方部门表单。支持 [{"departmentid":1,"auth":1}]',
	},
];
