import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['wedoc'], operation: ['modForm'] };

export const modFormDescription: INodeProperties[] = [
	{
		displayName: '收集表ID',
		name: 'formid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
	},
	{
		displayName: '修改类型',
		name: 'formOper',
		type: 'options',
		required: true,
		displayOptions: { show: showOnly },
		options: [
			{ name: '全量修改问题', value: 1 },
			{ name: '全量修改设置', value: 2 },
		],
		default: 1,
		description: '对应官方 oper 字段；两类内容需分开调用',
	},
	{
		displayName: '收集表标题',
		name: 'form_title',
		type: 'string',
		displayOptions: { show: { ...showOnly, formOper: [1] } },
		default: '',
	},
	{
		displayName: '收集表描述',
		name: 'form_description',
		type: 'string',
		displayOptions: { show: { ...showOnly, formOper: [1] } },
		default: '',
	},
	{
		displayName: '收集表头图',
		name: 'form_header',
		type: 'string',
		displayOptions: { show: { ...showOnly, formOper: [1] } },
		default: '',
		description: '收集表表头背景图链接',
	},
	{
		displayName: '收集表设置',
		name: 'formSetting',
		type: 'collection',
		displayOptions: { show: { ...showOnly, formOper: [2] } },
		default: {},
		placeholder: '添加设置',
		description: '全量修改设置时使用；可与下方 JSON 合并，JSON 优先',
		options: [
			{
				displayName: '填写权限',
				name: 'fill_out_auth',
				type: 'options',
				default: 0,
				options: [
					{ name: '所有人', value: 0 },
					{ name: '企业内指定人/部门', value: 1 },
					{ name: '家校所有范围', value: 4 },
				],
			},
			{
				displayName: '指定填写人员UserID列表',
				name: 'fill_in_range_userids_text',
				type: 'string',
				default: '',
				placeholder: 'zhangsan,lisi',
				displayOptions: { show: { fill_out_auth: [1] } },
				description: '逗号分隔；与下方选择合并',
			},
			{
				displayName: '指定填写人员(选择)',
				name: 'fill_in_range_userids',
				type: 'multiOptions',
				typeOptions: { loadOptionsMethod: 'getAllUsers' },
				default: [],
				displayOptions: { show: { fill_out_auth: [1] } },
				description: '与上方列表合并',
			},
			{
				displayName: '指定填写人员 JSON',
				name: 'fill_in_range_userids_json',
				type: 'json',
				default: '[]',
				displayOptions: { show: { fill_out_auth: [1] } },
				description:
					'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
			},
			{
				displayName: '指定填写部门ID列表',
				name: 'fill_in_range_departmentids_text',
				type: 'string',
				default: '',
				placeholder: '1,2',
				displayOptions: { show: { fill_out_auth: [1] } },
				description: '逗号分隔；与下方选择合并',
			},
			{
				displayName: '指定填写部门(选择)',
				name: 'fill_in_range_departmentids',
				type: 'multiOptions',
				typeOptions: { loadOptionsMethod: 'getDepartments' },
				default: [],
				displayOptions: { show: { fill_out_auth: [1] } },
				description: '与上方列表合并',
			},
			{
				displayName: '收集表管理员UserID列表',
				name: 'setting_manager_range_text',
				type: 'string',
				default: '',
				placeholder: 'zhangsan,lisi',
				description: '逗号分隔；与下方选择合并',
			},
			{
				displayName: '收集表管理员(选择)',
				name: 'setting_manager_range',
				type: 'multiOptions',
				typeOptions: { loadOptionsMethod: 'getAllUsers' },
				default: [],
				description: '与上方列表合并',
			},
			{
				displayName: '定时关闭',
				name: 'timed_finish',
				type: 'dateTime',
				default: '',
				description: '定时关闭时间；与定时重复互斥，都填时优先定时重复',
			},
			{
				displayName: '是否允许每人提交多份',
				name: 'allow_multi_fill',
				type: 'boolean',
				default: false,
			},
			{
				displayName: '是否允许匿名填写',
				name: 'can_anonymous',
				type: 'boolean',
				default: false,
			},
			{
				displayName: '是否有回复时提醒',
				name: 'can_notify_submit',
				type: 'boolean',
				default: false,
			},
			{
				displayName: '启用定时重复',
				name: 'timed_repeat_enable',
				type: 'boolean',
				default: false,
			},
			{
				displayName: '重复类型',
				name: 'timed_repeat_type',
				type: 'options',
				displayOptions: { show: { timed_repeat_enable: [true] } },
				options: [
					{ name: '每天', value: 1 },
					{ name: '每周', value: 2 },
					{ name: '每月', value: 3 },
					{ name: '每年', value: 4 },
					{ name: '工作日', value: 5 },
				],
				default: 1,
			},
			{
				displayName: '首次提醒时间',
				name: 'timed_repeat_remind_time',
				type: 'dateTime',
				displayOptions: { show: { timed_repeat_enable: [true] } },
				default: '',
				description: 'remind_time；留空表示不指定',
			},
			{
				displayName: '定时重复扩展JSON',
				name: 'timed_repeat_info',
				type: 'json',
				default: '{}',
				description: '与上方合并，JSON 优先',
			},
		],
	},
	{
		displayName: '完整Form Info JSON',
		name: 'formInfoJson',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '{}',
		description:
			'oper=1 时填写 form_question 等；oper=2 时填写 form_setting 或与上方设置表单合并（JSON 优先）。非空对象时与表单字段合并',
	},
];
