import type { INodeProperties } from 'n8n-workflow';

const show = (ops: string[]) => ({
	show: { resource: ['wedoc'], operation: ops },
});

/** 智能表格 content_priv + 字段编组 */
export const smartsheetExtraOpsDescription: INodeProperties[] = [
	{
		displayName: '文档ID',
		name: 'docid',
		type: 'string',
		required: true,
		displayOptions: show([
			'getSheetPriv',
			'createPrivRule',
			'deletePrivRule',
			'modPrivRuleMember',
			'addFieldGroup',
			'updateFieldGroup',
			'deleteFieldGroups',
			'getFieldGroups',
		]),
		default: '',
	},
	{
		displayName: '权限类型',
		name: 'priv_type',
		type: 'options',
		required: true,
		displayOptions: show(['getSheetPriv']),
		options: [
			{ name: '全员权限', value: 1 },
			{ name: '额外权限', value: 2 },
		],
		default: 1,
		description: 'type：1 全员，2 额外',
	},
	{
		displayName: '规则ID列表',
		name: 'rule_id_list',
		type: 'string',
		displayOptions: show(['getSheetPriv', 'deletePrivRule']),
		default: '',
		description: '逗号分隔 rule_id，查询额外权限或删除时使用',
	},
	{
		displayName: '规则名称',
		name: 'rule_name',
		type: 'string',
		displayOptions: show(['createPrivRule']),
		default: '',
		description: 'create_rule 的 name，不可重复',
	},
	{
		displayName: '规则ID',
		name: 'priv_rule_id',
		type: 'number',
		displayOptions: show(['modPrivRuleMember', 'updateSheetPrivFull']),
		default: 0,
		description: 'rule_id',
	},
	{
		displayName: '添加成员UserID',
		name: 'add_member_userids',
		type: 'string',
		displayOptions: show(['modPrivRuleMember']),
		default: '',
		placeholder: 'userid1,userid2',
		description: 'add_member_range.userid_list，逗号分隔，最多 50',
	},
	{
		displayName: '删除成员UserID',
		name: 'del_member_userids',
		type: 'string',
		displayOptions: show(['modPrivRuleMember']),
		default: '',
		placeholder: 'userid3',
		description: 'del_member_range.userid_list',
	},
	{
		displayName: '规则扩展JSON',
		name: 'privRuleJson',
		type: 'json',
		displayOptions: show(['createPrivRule', 'modPrivRuleMember', 'updateSheetPrivFull']),
		default: '{}',
		description: '其余字段（如 priv_list）与上方合并，JSON 优先',
	},
	{
		displayName: '子表ID',
		name: 'sheet_id',
		type: 'string',
		required: true,
		displayOptions: show(['addFieldGroup', 'updateFieldGroup', 'deleteFieldGroups', 'getFieldGroups']),
		default: '',
	},
	{
		displayName: '编组名称',
		name: 'group_name',
		type: 'string',
		displayOptions: show(['addFieldGroup', 'updateFieldGroup']),
		default: '',
	},
	{
		displayName: '编组ID',
		name: 'group_id',
		type: 'string',
		displayOptions: show(['updateFieldGroup', 'deleteFieldGroups']),
		default: '',
		description: 'update 时必填；delete 可填多个逗号分隔',
	},
	{
		displayName: '字段ID列表',
		name: 'field_ids',
		type: 'string',
		displayOptions: show(['addFieldGroup', 'updateFieldGroup']),
		default: '',
		description: 'children.field_id，逗号分隔',
	},
];
