import type { INodeProperties } from 'n8n-workflow';

const show = (ops: string[]) => ({
	show: { resource: ['wedoc'], operation: ops },
});

/** 智能表格 content_priv + 字段编组 */
export const smartsheetExtraOpsDescription: INodeProperties[] = [
	{
		displayName: '文档ID',
		name: 'docid',
		type: 'string',
		required: true,
		displayOptions: show([
			'getSheetPriv',
			'createPrivRule',
			'deletePrivRule',
			'modPrivRuleMember',
			'updateSheetPrivFull',
			'addFieldGroup',
			'updateFieldGroup',
			'deleteFieldGroups',
			'getFieldGroups',
		]),
		default: '',
	},
	{
		displayName: '权限类型',
		name: 'priv_type',
		type: 'options',
		required: true,
		displayOptions: show(['getSheetPriv']),
		options: [
			{ name: '全员权限', value: 1 },
			{ name: '额外权限', value: 2 },
		],
		default: 1,
		description: 'type：1 全员，2 额外',
	},
	{
		displayName: '规则ID列表',
		name: 'rule_id_list',
		type: 'string',
		displayOptions: show(['getSheetPriv', 'deletePrivRule']),
		default: '',
		description: '逗号分隔 rule_id；与下方 JSON 合并；查询额外权限或删除时使用',
	},
	{
		displayName: '规则ID列表 JSON',
		name: 'ruleIdListJson',
		type: 'json',
		displayOptions: show(['getSheetPriv', 'deletePrivRule']),
		default: '[]',
		description:
			'可选。非空数组时与上方列表合并去重。支持 [1,2] 或 [{"rule_id":1}]',
	},
	{
		displayName: '规则名称',
		name: 'rule_name',
		type: 'string',
		displayOptions: show(['createPrivRule']),
		default: '',
		description: 'create_rule 的 name，不可重复',
	},
	{
		displayName: '规则ID',
		name: 'priv_rule_id',
		type: 'number',
		displayOptions: show(['modPrivRuleMember', 'updateSheetPrivFull']),
		default: 0,
		description: 'rule_id',
	},
	{
		displayName: '添加成员UserID',
		name: 'add_member_userids',
		type: 'string',
		displayOptions: show(['modPrivRuleMember']),
		default: '',
		placeholder: 'userid1,userid2',
		description: 'add_member_range.userid_list，逗号分隔；与下方选择合并，最多 50',
	},
	{
		displayName: '添加成员(选择)',
		name: 'add_member_userids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: show(['modPrivRuleMember']),
		default: [],
		description: '与上方添加列表合并去重',
	},
	{
		displayName: '添加成员 JSON',
		name: 'addMemberUseridsJson',
		type: 'json',
		displayOptions: show(['modPrivRuleMember']),
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '删除成员UserID',
		name: 'del_member_userids',
		type: 'string',
		displayOptions: show(['modPrivRuleMember']),
		default: '',
		placeholder: 'userid3',
		description: 'del_member_range.userid_list；与下方选择合并',
	},
	{
		displayName: '删除成员(选择)',
		name: 'del_member_userids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: show(['modPrivRuleMember']),
		default: [],
		description: '与上方删除列表合并去重',
	},
	{
		displayName: '删除成员 JSON',
		name: 'delMemberUseridsJson',
		type: 'json',
		displayOptions: show(['modPrivRuleMember']),
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '权限规则类型',
		name: 'update_priv_type',
		type: 'options',
		displayOptions: show(['updateSheetPrivFull']),
		options: [
			{ name: '全员权限', value: 1 },
			{ name: '额外权限', value: 2 },
		],
		default: 2,
		description: 'type：1 全员，2 额外',
	},
	{
		displayName: '权限规则名称',
		name: 'update_priv_name',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['wedoc'],
				operation: ['updateSheetPrivFull'],
				update_priv_type: [2],
			},
		},
		default: '',
		description: '仅额外权限可更新名称',
	},
	{
		displayName: '子表权限列表',
		name: 'privListCollection',
		type: 'fixedCollection',
		displayOptions: show(['updateSheetPrivFull']),
		default: {},
		placeholder: '添加子表权限',
		typeOptions: { multipleValues: true },
		description: 'priv_list 简易配置；字段级规则请用扩展 JSON',
		options: [
			{
				displayName: '子表权限',
				name: 'items',
				values: [
					{
						displayName: '子表ID',
						name: 'sheet_id',
						type: 'string',
						default: '',
					},
					{
						displayName: '子表权限',
						name: 'priv',
						type: 'options',
						options: [
							{ name: '全部权限', value: 1 },
							{ name: '可编辑', value: 2 },
							{ name: '仅浏览', value: 3 },
							{ name: '无权限', value: 4 },
						],
						default: 2,
					},
					{
						displayName: '可新增记录',
						name: 'can_insert_record',
						type: 'boolean',
						default: true,
					},
					{
						displayName: '可删除记录',
						name: 'can_delete_record',
						type: 'boolean',
						default: true,
					},
					{
						displayName: '可增删改视图',
						name: 'can_create_modify_delete_view',
						type: 'boolean',
						default: true,
					},
					{
						displayName: '记录生效范围',
						name: 'record_range_type',
						type: 'options',
						options: [
							{ name: '全部记录', value: 1 },
							{ name: '满足任意条件', value: 2 },
							{ name: '满足全部条件', value: 3 },
						],
						default: 1,
						description: 'record_priv.record_range_type（priv 为可编辑/仅浏览时）',
					},
					{
						displayName: '清除子表设置',
						name: 'clear',
						type: 'boolean',
						default: false,
					},
				],
			},
		],
	},
	{
		displayName: '规则扩展JSON',
		name: 'privRuleJson',
		type: 'json',
		displayOptions: show(['updateSheetPrivFull']),
		default: '{}',
		description: '完整 priv_list/field_priv 等高级字段，与上方简易配置合并，JSON 优先',
	},
	{
		displayName: '子表ID',
		name: 'sheet_id',
		type: 'string',
		required: true,
		displayOptions: show(['addFieldGroup', 'updateFieldGroup', 'deleteFieldGroups', 'getFieldGroups']),
		default: '',
	},
	{
		displayName: '编组名称',
		name: 'group_name',
		type: 'string',
		displayOptions: show(['addFieldGroup', 'updateFieldGroup']),
		default: '',
	},
	{
		displayName: '编组ID',
		name: 'group_id',
		type: 'string',
		displayOptions: show(['updateFieldGroup', 'deleteFieldGroups']),
		default: '',
		description: 'update 时必填；delete 可填多个逗号分隔',
	},
	{
		displayName: '字段ID列表',
		name: 'field_ids',
		type: 'string',
		displayOptions: show(['addFieldGroup', 'updateFieldGroup']),
		default: '',
		description: 'children.field_id，逗号分隔；与下方 JSON 合并',
	},
	{
		displayName: '字段ID列表 JSON',
		name: 'fieldIdsJson',
		type: 'json',
		displayOptions: show(['addFieldGroup', 'updateFieldGroup']),
		default: '[]',
		description:
			'可选。非空数组时与上方列表合并去重。支持 ["id1"] 或 [{"field_id":"id1"}]',
	},
	{
		displayName: '偏移量',
		name: 'offset',
		type: 'number',
		displayOptions: show(['getFieldGroups']),
		default: 0,
		typeOptions: { minValue: 0 },
		description: '查询编组的分页偏移量',
	},
	{
		displayName: '每页数量',
		name: 'limit',
		type: 'number',
		displayOptions: show(['getFieldGroups']),
		default: 100,
		typeOptions: { minValue: 0, maxValue: 1000 },
		description: '查询编组的分页大小',
	},
];
