import type { INodeProperties } from 'n8n-workflow';
const showOnly = { resource: ['wedoc'], operation: ['updateSmartsheetField'] };
export const updateSmartsheetFieldDescription: INodeProperties[] = [
	{ displayName: '文档ID', name: 'docid', type: 'string', required: true, displayOptions: { show: showOnly }, default: '', description: '智能表格的docid' },
	{ displayName: '子表ID', name: 'sheet_id', type: 'string', required: true, displayOptions: { show: showOnly }, default: '', description: '子表的sheet_id' },
	{
		displayName: '字段列表',
		name: 'fieldsCollection',
		type: 'fixedCollection',
		required: true,
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加要更新的字段',
		typeOptions: { multipleValues: true },
		description: '要更新的字段列表',
		options: [
			{
				displayName: '字段',
				name: 'fields',
				values: [
					{
						displayName: '字段ID',
						name: 'field_id',
						type: 'string',
						default: '',
						required: true,
						description: '要更新的字段ID',
					},
					{
						displayName: '新字段名称',
						name: 'field_title',
						type: 'string',
						default: '',
						description: '新的字段名称，留空则不修改',
					},
					{
						displayName: '字段类型',
						name: 'field_type',
						type: 'options',
						required: true,
						default: 'FIELD_TYPE_TEXT',
						options: [
							{ name: '文本', value: 'FIELD_TYPE_TEXT' },
							{ name: '数字', value: 'FIELD_TYPE_NUMBER' },
							{ name: '复选框', value: 'FIELD_TYPE_CHECKBOX' },
							{ name: '日期', value: 'FIELD_TYPE_DATE_TIME' },
							{ name: '图片', value: 'FIELD_TYPE_IMAGE' },
							{ name: '文件', value: 'FIELD_TYPE_ATTACHMENT' },
							{ name: '成员', value: 'FIELD_TYPE_USER' },
							{ name: '超链接', value: 'FIELD_TYPE_URL' },
							{ name: '多选', value: 'FIELD_TYPE_SELECT' },
							{ name: '单选', value: 'FIELD_TYPE_SINGLE_SELECT' },
							{ name: '创建人', value: 'FIELD_TYPE_CREATED_USER' },
							{ name: '最后编辑人', value: 'FIELD_TYPE_MODIFIED_USER' },
							{ name: '创建时间', value: 'FIELD_TYPE_CREATED_TIME' },
							{ name: '最后编辑时间', value: 'FIELD_TYPE_MODIFIED_TIME' },
							{ name: '进度', value: 'FIELD_TYPE_PROGRESS' },
							{ name: '电话', value: 'FIELD_TYPE_PHONE_NUMBER' },
							{ name: '邮件', value: 'FIELD_TYPE_EMAIL' },
							{ name: '引用', value: 'FIELD_TYPE_REFERENCE' },
							{ name: '地理位置', value: 'FIELD_TYPE_LOCATION' },
							{ name: '货币', value: 'FIELD_TYPE_CURRENCY' },
							{ name: '企业微信群', value: 'FIELD_TYPE_WWGROUP' },
							{ name: '自动编号', value: 'FIELD_TYPE_AUTONUMBER' },
							{ name: '百分数', value: 'FIELD_TYPE_PERCENTAGE' },
							{ name: '条码', value: 'FIELD_TYPE_BARCODE' },
						],
						description: '必须填写字段的原类型，接口不支持修改字段类型',
					},
					{
						displayName: '选项列表（单选/多选）',
						name: 'select_options',
						type: 'string',
						default: '',
						description:
							'新的选项列表，多个选项用英文逗号分隔；与下方 JSON 合并。仅对单选/多选字段有效。',
						placeholder: '例如: 选项1,选项2,选项3',
					},
					{
						displayName: '选项列表 JSON',
						name: 'select_options_json',
						type: 'json',
						default: '[]',
						description:
							'可选。非空数组时与上方列表合并去重。支持 ["选项1"] 或 [{"text":"选项1"}]',
					},
					{
						displayName: '字段属性JSON',
						name: 'field_json',
						type: 'json',
						default: '{}',
						description: '用于更新 property_number、property_date_time 等官方字段属性',
					},
				],
			},
		],
	},
];
