import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['meeting'], operation: ['createMeeting'] };

export const createMeetingDescription: INodeProperties[] = [
	{
		displayName: '管理员UserID',
		name: 'admin_userid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description:
			'admin_userid。<a href="https://developer.work.weixin.qq.com/document/path/98148" target="_blank">官方文档</a>',
	},
	{
		displayName: '会议标题',
		name: 'title',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: 'title，会议标题',
		placeholder: '产品需求评审会',
	},
	{
		displayName: '会议开始时间',
		name: 'meeting_start',
		type: 'dateTime',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: 'meeting_start，Unix 时间戳（秒）',
	},
	{
		displayName: '会议时长(秒)',
		name: 'meeting_duration',
		type: 'number',
		required: true,
		displayOptions: { show: showOnly },
		default: 3600,
		description: 'meeting_duration，300～86399 秒',
		typeOptions: { minValue: 300, maxValue: 86399 },
	},
	{
		displayName: '会议描述',
		name: 'description',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		typeOptions: { rows: 2 },
	},
	{
		displayName: '会议地点',
		name: 'location',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
	},
	{
		displayName: '受邀成员UserID列表',
		name: 'invitee_userids',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: 'lisi,wangwu',
		description: 'invitees.userid，逗号分隔',
	},
	{
		displayName: '嘉宾列表',
		name: 'guestsCollection',
		type: 'fixedCollection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加嘉宾',
		typeOptions: { multipleValues: true },
		description: 'guests，外部嘉宾手机号列表',
		options: [
			{
				displayName: '嘉宾',
				name: 'guests',
				values: [
					{
						displayName: '国家/地区代码',
						name: 'area',
						type: 'string',
						default: '86',
					},
					{
						displayName: '手机号',
						name: 'phone_number',
						type: 'string',
						default: '',
					},
					{
						displayName: '嘉宾名称',
						name: 'guest_name',
						type: 'string',
						default: '',
					},
				],
			},
		],
	},
	{
		displayName: '日历ID',
		name: 'cal_id',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: 'cal_id，第三方应用必填',
	},
	{
		displayName: '应用AgentID',
		name: 'agentid',
		type: 'number',
		displayOptions: { show: showOnly },
		default: 0,
		description: 'agentid，仅旧第三方多应用套件需要；0 不传',
	},
	{
		displayName: '入会密码',
		name: 'settings_password',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: 'settings.password，4-6 位数字',
	},
	{
		displayName: '开启等候室',
		name: 'settings_enable_waiting_room',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
	},
	{
		displayName: '允许主持人前入会',
		name: 'settings_allow_enter_before_host',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: true,
	},
	{
		displayName: '入会静音',
		name: 'settings_enable_enter_mute',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '关闭', value: 0 },
			{ name: '开启', value: 1 },
			{ name: '超过6人自动开启', value: 2 },
		],
		default: 2,
		description: 'settings.enable_enter_mute',
	},
	{
		displayName: '来电提醒范围',
		name: 'settings_remind_scope',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '不提醒', value: 1 },
			{ name: '仅提醒主持人', value: 2 },
			{ name: '提醒所有成员', value: 3 },
			{ name: '指定部分人响铃', value: 4 },
		],
		default: 2,
		description: 'settings.remind_scope',
	},
	{
		displayName: '主持人UserID列表',
		name: 'settings_host_userids',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: 'lisi',
		description: 'settings.hosts.userid，最多 10 个',
	},
	{
		displayName: '开启屏幕水印',
		name: 'settings_enable_screen_watermark',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: 'settings.enable_screen_watermark',
	},
	{
		displayName: '允许自行取消静音',
		name: 'settings_allow_unmute_self',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: true,
		description: 'settings.allow_unmute_self',
	},
	{
		displayName: '允许外部成员入会',
		name: 'settings_allow_external_user',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: true,
		description: 'settings.allow_external_user：true 所有人可入会；false 仅企业内',
	},
	{
		displayName: '开启报名',
		name: 'settings_enable_enroll',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: 'settings.enable_enroll',
	},
	{
		displayName: '自动录制类型',
		name: 'settings_auto_record_type',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '禁用 none', value: 'none' },
			{ name: '本地 local', value: 'local' },
			{ name: '云录制 cloud', value: 'cloud' },
		],
		default: 'none',
		description: 'settings.auto_record_type',
	},
	{
		displayName: '扩展请求JSON',
		name: 'createMeetingExtraJson',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '{}',
		description: '其余字段（guests、reminders、settings 细项等），与上方合并，JSON 优先',
	},
];
