import type { INodeProperties } from 'n8n-workflow';

const showOnlyForUpdate = {
	resource: ['meeting'],
	operation: ['updateMeeting'],
};

export const updateMeetingDescription: INodeProperties[] = [
	{
		displayName: '会议ID',
		name: 'meetingid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnlyForUpdate },
		default: '',
		description:
			'meetingid，仅允许修改预约中的会议。<a href="https://developer.work.weixin.qq.com/document/path/98154" target="_blank">官方文档</a>',
	},
	{
		displayName: '会议标题',
		name: 'title',
		type: 'string',
		displayOptions: { show: showOnlyForUpdate },
		default: '',
		description: 'title',
	},
	{
		displayName: '会议开始时间',
		name: 'meeting_start',
		type: 'dateTime',
		displayOptions: { show: showOnlyForUpdate },
		default: '',
		description: 'meeting_start；修改时需同时传 duration',
	},
	{
		displayName: '会议时长(秒)',
		name: 'meeting_duration',
		type: 'number',
		displayOptions: { show: showOnlyForUpdate },
		default: 0,
		description: 'meeting_duration，300～86399；0 表示不修改',
	},
	{
		displayName: '会议描述',
		name: 'description',
		type: 'string',
		displayOptions: { show: showOnlyForUpdate },
		default: '',
	},
	{
		displayName: '会议地点',
		name: 'location',
		type: 'string',
		displayOptions: { show: showOnlyForUpdate },
		default: '',
	},
	{
		displayName: '受邀成员UserID列表',
		name: 'invitee_userids',
		type: 'string',
		displayOptions: { show: showOnlyForUpdate },
		default: '',
		placeholder: 'lisi,wangwu',
		description: 'invitees.userid，覆盖式设置受邀成员',
	},
	{
		displayName: '入会密码',
		name: 'settings_password',
		type: 'string',
		displayOptions: { show: showOnlyForUpdate },
		default: '',
		description: 'settings.password，4-6 位数字；空表示不修改',
	},
	{
		displayName: '开启等候室',
		name: 'settings_enable_waiting_room',
		type: 'boolean',
		displayOptions: { show: showOnlyForUpdate },
		default: false,
		description: 'settings.enable_waiting_room；仅表单填写时写入',
	},
	{
		displayName: '允许主持人前入会',
		name: 'settings_allow_enter_before_host',
		type: 'boolean',
		displayOptions: { show: showOnlyForUpdate },
		default: true,
		description: 'settings.allow_enter_before_host',
	},
	{
		displayName: '入会静音',
		name: 'settings_enable_enter_mute',
		type: 'options',
		displayOptions: { show: showOnlyForUpdate },
		options: [
			{ name: '不修改', value: -1 },
			{ name: '关闭', value: 0 },
			{ name: '开启', value: 1 },
			{ name: '超过6人自动开启', value: 2 },
		],
		default: -1,
		description: 'settings.enable_enter_mute；选「不修改」则不传',
	},
	{
		displayName: '开启屏幕水印',
		name: 'settings_enable_screen_watermark',
		type: 'boolean',
		displayOptions: { show: showOnlyForUpdate },
		default: false,
		description: 'settings.enable_screen_watermark',
	},
	{
		displayName: '来电提醒范围',
		name: 'settings_remind_scope',
		type: 'options',
		displayOptions: { show: showOnlyForUpdate },
		options: [
			{ name: '不修改', value: 0 },
			{ name: '不提醒', value: 1 },
			{ name: '仅提醒主持人', value: 2 },
			{ name: '提醒所有成员', value: 3 },
			{ name: '指定部分人响铃', value: 4 },
		],
		default: 0,
		description: 'settings.remind_scope；0 不传',
	},
	{
		displayName: '主持人UserID列表',
		name: 'settings_host_userids',
		type: 'string',
		displayOptions: { show: showOnlyForUpdate },
		default: '',
		placeholder: 'lisi,wangwu',
		description: 'settings.hosts.userid，覆盖式；空表示不修改',
	},
	{
		displayName: '指定响铃UserID列表',
		name: 'settings_ring_userids',
		type: 'string',
		displayOptions: {
			show: { ...showOnlyForUpdate, settings_remind_scope: [4] },
		},
		default: '',
		placeholder: 'zhangsan,lisi',
		description: 'settings.ring_users.userid，remind_scope=4 时生效',
	},
	{
		displayName: '允许自行取消静音',
		name: 'settings_allow_unmute_self',
		type: 'boolean',
		displayOptions: { show: showOnlyForUpdate },
		default: true,
		description: 'settings.allow_unmute_self',
	},
	{
		displayName: '允许外部成员入会',
		name: 'settings_allow_external_user',
		type: 'boolean',
		displayOptions: { show: showOnlyForUpdate },
		default: true,
		description: 'settings.allow_external_user',
	},
	{
		displayName: '开启报名',
		name: 'settings_enable_enroll',
		type: 'boolean',
		displayOptions: { show: showOnlyForUpdate },
		default: false,
		description: 'settings.enable_enroll',
	},
	{
		displayName: '自动录制类型',
		name: 'settings_auto_record_type',
		type: 'options',
		displayOptions: { show: showOnlyForUpdate },
		options: [
			{ name: '不修改', value: '' },
			{ name: '禁用 none', value: 'none' },
			{ name: '本地 local', value: 'local' },
			{ name: '云录制 cloud', value: 'cloud' },
		],
		default: '',
		description: 'settings.auto_record_type；空不传',
	},
	{
		displayName: '写入设置字段',
		name: 'update_write_settings',
		type: 'boolean',
		displayOptions: { show: showOnlyForUpdate },
		default: false,
		description:
			'开启后将上方等候室/静音/水印等 settings 写入请求（密码与主持人列表有值时始终写入）',
	},
	{
		displayName: '扩展请求JSON',
		name: 'updateMeetingExtraJson',
		type: 'json',
		displayOptions: { show: showOnlyForUpdate },
		default: '{}',
		description: '其余 settings/reminders 等，与上方合并，JSON 优先',
	},
];
