import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['meeting'], operation: ['updateAdvancedMeeting'] };

export const updateAdvancedMeetingDescription: INodeProperties[] = [
	{
		displayName: '会议ID',
		name: 'meetingid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description:
			'meetingid，仅允许修改预约中的会议。<a href="https://developer.work.weixin.qq.com/document/path/98154" target="_blank">官方文档</a>',
	},
	{
		displayName: '修改会议标题',
		name: 'update_title',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后写入 title',
	},
	{
		displayName: '会议标题',
		name: 'title',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, update_title: [true] } },
		default: '',
		description: 'title',
	},
	{
		displayName: '修改会议时间',
		name: 'update_time',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后必须同时填写开始时间与会议时长',
	},
	{
		displayName: '会议开始时间',
		name: 'meeting_start',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { ...showOnly, update_time: [true] } },
		default: '',
		description: 'meeting_start；修改时需同时指定 duration',
	},
	{
		displayName: '会议时长(秒)',
		name: 'meeting_duration',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, update_time: [true] } },
		default: 3600,
		typeOptions: { minValue: 300, maxValue: 86399 },
		description: 'meeting_duration，300～86399 秒',
	},
	{
		displayName: '修改会议描述',
		name: 'update_description',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后写入 description；内容留空表示清除',
	},
	{
		displayName: '会议描述',
		name: 'description',
		type: 'string',
		displayOptions: { show: { ...showOnly, update_description: [true] } },
		default: '',
		typeOptions: { rows: 2 },
	},
	{
		displayName: '修改会议地点',
		name: 'update_location',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后写入 location；内容留空表示清除',
	},
	{
		displayName: '会议地点',
		name: 'location',
		type: 'string',
		displayOptions: { show: { ...showOnly, update_location: [true] } },
		default: '',
	},
	{
		displayName: '修改受邀成员',
		name: 'update_invitees',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后覆盖受邀成员列表；留空表示清空',
	},
	{
		displayName: '受邀成员UserID列表',
		name: 'invitee_userids',
		type: 'string',
		displayOptions: { show: { ...showOnly, update_invitees: [true] } },
		default: '',
		placeholder: 'lisi,wangwu',
		description: 'invitees.userid，支持英文/中文逗号、竖线或换行分隔；与下方选择合并，最多 300 个',
	},
	{
		displayName: '受邀成员(选择)',
		name: 'invitee_userids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: { ...showOnly, update_invitees: [true] } },
		default: [],
		description: '与上方列表合并去重',
	},
	{
		displayName: '受邀成员 JSON',
		name: 'inviteesJson',
		type: 'json',
		displayOptions: { show: { ...showOnly, update_invitees: [true] } },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '修改嘉宾列表',
		name: 'update_guests',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后覆盖 guests；不添加嘉宾表示清空',
	},
	{
		displayName: '嘉宾列表',
		name: 'guestsCollection',
		type: 'fixedCollection',
		displayOptions: { show: { ...showOnly, update_guests: [true] } },
		default: {},
		placeholder: '添加嘉宾',
		typeOptions: { multipleValues: true },
		description: 'guests，覆盖式',
		options: [
			{
				displayName: '嘉宾',
				name: 'guests',
				values: [
					{
						displayName: '国家/地区代码',
						name: 'area',
						type: 'string',
						default: '86',
					},
					{
						displayName: '手机号',
						name: 'phone_number',
						type: 'string',
						default: '',
					},
					{
						displayName: '嘉宾名称',
						name: 'guest_name',
						type: 'string',
						default: '',
					},
				],
			},
		],
	},
	{
		displayName: '修改入会密码',
		name: 'update_password',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后写入密码；留空表示清除',
	},
	{
		displayName: '入会密码',
		name: 'settings_password',
		type: 'string',
		typeOptions: { password: true },
		displayOptions: { show: { ...showOnly, update_password: [true] } },
		default: '',
		description: 'settings.password，4-6 位数字；空表示不修改',
	},
	{
		displayName: '开启等候室',
		name: 'settings_enable_waiting_room',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, update_write_settings: [true] } },
		default: false,
		description: 'settings.enable_waiting_room',
	},
	{
		displayName: '允许主持人前入会',
		name: 'settings_allow_enter_before_host',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, update_write_settings: [true] } },
		default: true,
		description: 'settings.allow_enter_before_host',
	},
	{
		displayName: '入会静音',
		name: 'settings_enable_enter_mute',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '不修改', value: -1 },
			{ name: '关闭', value: 0 },
			{ name: '开启', value: 1 },
			{ name: '超过6人自动开启', value: 2 },
		],
		default: -1,
		description: 'settings.enable_enter_mute',
	},
	{
		displayName: '开启屏幕水印',
		name: 'settings_enable_screen_watermark',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, update_write_settings: [true] } },
		default: false,
		description: 'settings.enable_screen_watermark',
	},
	{
		displayName: '来电提醒范围',
		name: 'settings_remind_scope',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '不修改', value: 0 },
			{ name: '不提醒', value: 1 },
			{ name: '仅提醒主持人', value: 2 },
			{ name: '提醒所有成员', value: 3 },
			{ name: '指定部分人响铃', value: 4 },
		],
		default: 0,
		description: 'settings.remind_scope；0 不传',
	},
	{
		displayName: '修改主持人列表',
		name: 'update_hosts',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description: '开启后覆盖 hosts.userid；留空表示清空',
	},
	{
		displayName: '主持人UserID列表',
		name: 'settings_host_userids',
		type: 'string',
		displayOptions: { show: { ...showOnly, update_hosts: [true] } },
		default: '',
		placeholder: 'lisi,wangwu',
		description: 'settings.hosts.userid，支持英文/中文逗号、竖线或换行分隔；与下方选择合并，最多 10 个',
	},
	{
		displayName: '主持人(选择)',
		name: 'settings_host_userids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: { ...showOnly, update_hosts: [true] } },
		default: [],
		description: '与上方列表合并去重，合计最多 10 个',
	},
	{
		displayName: '指定响铃UserID列表',
		name: 'settings_ring_userids',
		type: 'string',
		displayOptions: {
			show: { ...showOnly, settings_remind_scope: [4] },
		},
		default: '',
		placeholder: 'zhangsan,lisi',
		description: 'settings.ring_users.userid，remind_scope=4 时生效；与下方选择合并',
	},
	{
		displayName: '指定响铃成员(选择)',
		name: 'settings_ring_userids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: {
			show: { ...showOnly, settings_remind_scope: [4] },
		},
		default: [],
		description: '与上方列表合并去重',
	},
	{
		displayName: '允许自行取消静音',
		name: 'settings_allow_unmute_self',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, update_write_settings: [true] } },
		default: true,
		description: 'settings.allow_unmute_self',
	},
	{
		displayName: '允许外部成员入会',
		name: 'settings_allow_external_user',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, update_write_settings: [true] } },
		default: true,
		description: 'settings.allow_external_user',
	},
	{
		displayName: '开启报名',
		name: 'settings_enable_enroll',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, update_write_settings: [true] } },
		default: false,
		description: 'settings.enable_enroll',
	},
	{
		displayName: '自动录制类型',
		name: 'settings_auto_record_type',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '不修改', value: '' },
			{ name: '禁用 none', value: 'none' },
			{ name: '本地 local', value: 'local' },
			{ name: '云录制 cloud', value: 'cloud' },
		],
		default: '',
		description: 'settings.auto_record_type；空不传',
	},
	{
		displayName: '写入设置字段',
		name: 'update_write_settings',
		type: 'boolean',
		displayOptions: { show: showOnly },
		default: false,
		description:
			'开启后将上方等候室/静音/水印等 settings 写入请求（密码与主持人列表有值时始终写入）',
	},
	{
		displayName: '高级设置(兼容旧版)',
		name: 'advancedSettings',
		type: 'collection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加设置',
		description: '兼容旧工作流；新字段优先使用上方独立表单',
		options: [
			{
				displayName: '会议描述',
				name: 'description',
				type: 'string',
				default: '',
			},
			{
				displayName: '会议密码',
				name: 'password',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				description: '写入 settings.password',
			},
			{
				displayName: '允许主持人前入会',
				name: 'allow_enter_before_host',
				type: 'boolean',
				default: true,
			},
			{
				displayName: '入会时静音',
				name: 'enable_mute_on_entry',
				type: 'boolean',
				default: false,
				description: '映射为 settings.enable_enter_mute',
			},
		],
	},
	{
		displayName: '扩展请求JSON',
		name: 'updateMeetingExtraJson',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '{}',
		description: '完整 settings/reminders 等，与上方合并，JSON 优先',
	},
];
