import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['mchpay'] };

export const mchpayDescription: INodeProperties[] = [
	{
		displayName: '操作',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnly },
		options: [
			{
				name: '[企业红包] 发放企业红包',
				value: 'sendRedpack',
				action: '发放企业红包',
				description:
					'mmpaymkttransfers/sendworkwxredpack。<a href="https://developer.work.weixin.qq.com/document/path/90275" target="_blank">官方文档</a>',
			},
			{
				name: '[企业红包] 查询红包记录',
				value: 'queryRedpack',
				action: '查询红包记录',
				description: 'mmpaymkttransfers/queryworkwxredpack',
			},
			{
				name: '[向员工付款] 付款',
				value: 'payToEmployee',
				action: '向员工付款',
				description:
					'mmpaymkttransfers/promotion/paywwsptrans2pocket。<a href="https://developer.work.weixin.qq.com/document/path/90278" target="_blank">官方文档</a>',
			},
			{
				name: '[向员工付款] 查询付款记录',
				value: 'queryPayToEmployee',
				action: '查询付款记录',
				description: 'mmpaymkttransfers/promotion/querywwsptrans2pocket',
			},
		],
		default: 'sendRedpack',
	},
	{
		displayName: '说明',
		name: 'mchNotice',
		type: 'notice',
		displayOptions: { show: showOnly },
		default: '',
		description:
			'本资源调用 api.mch.weixin.qq.com 商户 XML 接口，需配置「企业微信商户支付」凭证（商户号、API 密钥、双向证书、应用 secret）。openid 可用通讯录 convertToOpenid 获取。',
	},
	// --- 红包 ---
	{
		displayName: '商户订单号',
		name: 'mch_billno',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack', 'queryRedpack'] } },
		default: '',
		description: 'mch_billno，唯一',
	},
	{
		displayName: '接收人 OpenID',
		name: 're_openid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
		description: 're_openid，wxappid 下的 openid',
	},
	{
		displayName: '金额(分)',
		name: 'total_amount',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: 100,
		description: 'total_amount，单位分',
	},
	{
		displayName: '祝福语',
		name: 'wishing',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '恭喜发财',
	},
	{
		displayName: '项目名称',
		name: 'act_name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack', 'payToEmployee'] } },
		default: '',
		description: 'act_name',
	},
	{
		displayName: '备注',
		name: 'remark',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
	},
	{
		displayName: '应用 AgentID',
		name: 'agentid',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack', 'payToEmployee'] } },
		default: '',
		description: '与 sender_name 互斥；空则用凭证默认 agentId',
	},
	{
		displayName: '发送者名称',
		name: 'sender_name',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
		description: '以个人名义发送时填写，与 agentid 互斥',
	},
	{
		displayName: '场景 scene_id',
		name: 'scene_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
		description: '金额>200元或<1元时必填，如 PRODUCT_4',
	},
	{
		displayName: '扩展字段JSON',
		name: 'extraXmlFields',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '{}',
		description: '合并进 XML 的额外字段（如 sender_header_media_id）',
	},
	// --- 付款 ---
	{
		displayName: '商户订单号',
		name: 'partner_trade_no',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['payToEmployee', 'queryPayToEmployee'] },
		},
		default: '',
		description: 'partner_trade_no',
	},
	{
		displayName: '员工 OpenID',
		name: 'openid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '',
	},
	{
		displayName: '金额(分)',
		name: 'amount',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: 100,
	},
	{
		displayName: '付款说明',
		name: 'desc',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '',
	},
	{
		displayName: '调用方 IP',
		name: 'spbill_create_ip',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '127.0.0.1',
	},
	{
		displayName: '校验姓名',
		name: 'check_name',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		options: [
			{ name: '不校验 NO_CHECK', value: 'NO_CHECK' },
			{ name: '强校验 FORCE_CHECK', value: 'FORCE_CHECK' },
		],
		default: 'NO_CHECK',
	},
	{
		displayName: '收款人姓名',
		name: 're_user_name',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '',
		description: 'check_name=FORCE_CHECK 时必填',
	},
	{
		displayName: '付款消息类型',
		name: 'ww_msg_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		options: [
			{ name: '普通付款 NORMAL_MSG', value: 'NORMAL_MSG' },
			{ name: '审批付款 APPROVAL_MSG', value: 'APPROVAL_MSG' },
		],
		default: 'NORMAL_MSG',
	},
	{
		displayName: '审批单号',
		name: 'approval_number',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '',
		description: 'ww_msg_type=APPROVAL_MSG 时填写',
	},
];
