import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['mchpay'] };

export const mchpayDescription: INodeProperties[] = [
	{
		displayName: '操作',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnly },
		options: [
			{
				name: '[兼容旧商户·企业红包] 发放企业红包',
				value: 'sendRedpack',
				action: '发放企业红包',
				description: '向成员发放企业红包',
			},
			{
				name: '[兼容旧商户·企业红包] 查询红包记录',
				value: 'queryRedpack',
				action: '查询红包记录',
				description: '查询企业红包发放结果',
			},
			{
				name: '[兼容旧商户·向员工付款] 付款',
				value: 'payToEmployee',
				action: '向员工付款',
				description: '向员工发起企业付款',
			},
			{
				name: '[兼容旧商户·向员工付款] 查询付款记录',
				value: 'queryPayToEmployee',
				action: '查询付款记录',
				description: '查询向员工付款的结果',
			},
		],
		default: 'sendRedpack',
	},
	{
		displayName: '这些是旧版企业红包/企业付款 XML 接口，全新创建的企业微信通常不可用。使用前请配置「企业微信商户支付」凭证（商户号、密钥与证书）；收款人 OpenID 可先用通讯录「userid 与 openid 互换」获取。',
		name: 'mchNotice',
		type: 'notice',
		displayOptions: { show: showOnly },
		default: '',
	},
	// --- 红包 ---
	{
		displayName: '商户订单号',
		name: 'mch_billno',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack', 'queryRedpack'] } },
		default: '',
		typeOptions: { maxLength: 28 },
		description: '商户订单号，需保证唯一；超时重试时请使用原单号',
	},
	{
		displayName: '接收人 OpenID',
		name: 're_openid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
		typeOptions: { maxLength: 32 },
		description: '收款用户在企业微信下的 OpenID',
	},
	{
		displayName: '金额(分)',
		name: 'total_amount',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: 100,
		typeOptions: { minValue: 1, numberStepSize: 1 },
		description: '红包金额，单位：分（默认单笔不小于 1 元）',
	},
	{
		displayName: '祝福语',
		name: 'wishing',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '恭喜发财',
		typeOptions: { maxLength: 128 },
	},
	{
		displayName: '项目名称',
		name: 'act_name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
		typeOptions: { maxLength: 32 },
	},
	{
		displayName: '项目名称',
		name: 'act_name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '',
		typeOptions: { maxLength: 50 },
	},
	{
		displayName: '备注',
		name: 'remark',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
		typeOptions: { maxLength: 256 },
	},
	{
		displayName: '应用 AgentID',
		name: 'agentid',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack', 'payToEmployee'] } },
		default: '',
		typeOptions: { maxLength: 20 },
		description: '以企业应用名义发红包时填写；与「发送者名称」二选一，空则使用凭证中的默认应用',
	},
	{
		displayName: '发送者名称',
		name: 'sender_name',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
		typeOptions: { maxLength: 128 },
		description: '以个人名义发红包时填写；与「应用 AgentID」二选一',
	},
	{
		displayName: '场景 ID',
		name: 'scene_id',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		options: [
			{ name: '不指定', value: '' },
			{ name: 'PRODUCT_1 商品促销', value: 'PRODUCT_1' },
			{ name: 'PRODUCT_2 抽奖', value: 'PRODUCT_2' },
			{ name: 'PRODUCT_3 虚拟物品兑奖', value: 'PRODUCT_3' },
			{ name: 'PRODUCT_4 企业内部福利', value: 'PRODUCT_4' },
			{ name: 'PRODUCT_5 渠道分润', value: 'PRODUCT_5' },
			{ name: 'PRODUCT_6 保险回馈', value: 'PRODUCT_6' },
			{ name: 'PRODUCT_7 彩票派奖', value: 'PRODUCT_7' },
			{ name: 'PRODUCT_8 税务刮奖', value: 'PRODUCT_8' },
		],
		default: '',
		description: '金额大于 200 元或小于 1 元时必填',
	},
	{
		displayName: '发送者头像素材ID',
		name: 'sender_header_media_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
		typeOptions: { maxLength: 128 },
		description: '以个人名义发红包时可选，素材 media_id',
	},
	{
		displayName: '扩展字段JSON',
		name: 'extraXmlFields',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '{}',
		description: '额外业务字段，仅接受安全 XML 字段名及字符串/数字值；表单中的核心字段始终优先',
	},
	{
		displayName: '该操作会实际发放资金。系统错误或超时时必须使用原商户订单号查询或重试，不能更换单号，否则可能重复发放。',
		name: 'redpackRiskNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
	},
	{
		displayName: '查询接口仅支持最近 30 天内的订单。查无记录不等于发放失败，请保留原单号并稍后重试。',
		name: 'queryAgeNotice',
		type: 'notice',
		displayOptions: {
			show: { ...showOnly, operation: ['queryRedpack', 'queryPayToEmployee'] },
		},
		default: '',
	},
	// --- 付款 ---
	{
		displayName: '商户订单号',
		name: 'partner_trade_no',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['payToEmployee', 'queryPayToEmployee'] },
		},
		default: '',
		typeOptions: { maxLength: 32 },
	},
	{
		displayName: '员工 OpenID',
		name: 'openid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '',
		typeOptions: { maxLength: 64 },
	},
	{
		displayName: '金额(分)',
		name: 'amount',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: 100,
		typeOptions: { minValue: 1, numberStepSize: 1 },
	},
	{
		displayName: '付款说明',
		name: 'desc',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '',
		typeOptions: { maxLength: 81 },
	},
	{
		displayName: '调用方 IP',
		name: 'spbill_create_ip',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '127.0.0.1',
	},
	{
		displayName: '校验姓名',
		name: 'check_name',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		options: [
			{ name: '不校验 NO_CHECK', value: 'NO_CHECK' },
			{ name: '强校验 FORCE_CHECK', value: 'FORCE_CHECK' },
		],
		default: 'NO_CHECK',
	},
	{
		displayName: '收款人姓名',
		name: 're_user_name',
		type: 'string',
		displayOptions: {
			show: { ...showOnly, operation: ['payToEmployee'], check_name: ['FORCE_CHECK'] },
		},
		default: '',
		typeOptions: { maxLength: 64 },
		description: 'check_name=FORCE_CHECK 时必填',
	},
	{
		displayName: '付款消息类型',
		name: 'ww_msg_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		options: [
			{ name: '普通付款 NORMAL_MSG', value: 'NORMAL_MSG' },
			{ name: '审批付款 APPROVAL_MSG', value: 'APPROVAL_MSG' },
		],
		default: 'NORMAL_MSG',
	},
	{
		displayName: '审批单号',
		name: 'approval_number',
		type: 'string',
		displayOptions: {
			show: { ...showOnly, operation: ['payToEmployee'], ww_msg_type: ['APPROVAL_MSG'] },
		},
		default: '',
		typeOptions: { maxLength: 128 },
		description: 'ww_msg_type=APPROVAL_MSG 时填写',
	},
	{
		displayName: '该操作会实际向员工付款。业务结果不明确时先用原商户订单号查询；重试必须保持原单号和原参数，避免重复付款。',
		name: 'payRiskNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '',
	},
];
