import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['mchpay'] };

export const mchpayDescription: INodeProperties[] = [
	{
		displayName: '操作',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnly },
		options: [
			{
				name: '[企业红包] 发放企业红包',
				value: 'sendRedpack',
				action: '发放企业红包',
				description: '向成员发放企业红包',
			},
			{
				name: '[企业红包] 查询红包记录',
				value: 'queryRedpack',
				action: '查询红包记录',
				description: '查询企业红包发放结果',
			},
			{
				name: '[向员工付款] 付款',
				value: 'payToEmployee',
				action: '向员工付款',
				description: '向员工发起企业付款',
			},
			{
				name: '[向员工付款] 查询付款记录',
				value: 'queryPayToEmployee',
				action: '查询付款记录',
				description: '查询向员工付款的结果',
			},
		],
		default: 'sendRedpack',
	},
	{
		displayName: '说明',
		name: 'mchNotice',
		type: 'notice',
		displayOptions: { show: showOnly },
		default: '',
		description:
			'使用前请配置「企业微信商户支付」凭证（商户号、密钥与证书）。收款人 OpenID 可先用通讯录「userid 与 openid 互换」获取。',
	},
	// --- 红包 ---
	{
		displayName: '商户订单号',
		name: 'mch_billno',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack', 'queryRedpack'] } },
		default: '',
		description: '商户订单号，需保证唯一；超时重试时请使用原单号',
	},
	{
		displayName: '接收人 OpenID',
		name: 're_openid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
		description: '收款用户在企业微信下的 OpenID',
	},
	{
		displayName: '金额(分)',
		name: 'total_amount',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: 100,
		description: '红包金额，单位：分（默认单笔不小于 1 元）',
	},
	{
		displayName: '祝福语',
		name: 'wishing',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '恭喜发财',
	},
	{
		displayName: '项目名称',
		name: 'act_name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack', 'payToEmployee'] } },
		default: '',
	},
	{
		displayName: '备注',
		name: 'remark',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
	},
	{
		displayName: '应用 AgentID',
		name: 'agentid',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack', 'payToEmployee'] } },
		default: '',
		description: '以企业应用名义发红包时填写；与「发送者名称」二选一，空则使用凭证中的默认应用',
	},
	{
		displayName: '发送者名称',
		name: 'sender_name',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
		description: '以个人名义发红包时填写；与「应用 AgentID」二选一',
	},
	{
		displayName: '场景 ID',
		name: 'scene_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['sendRedpack'] } },
		default: '',
		description: '金额大于 200 元或小于 1 元时必填，例如 PRODUCT_4（企业内部福利）',
	},
	{
		displayName: '扩展字段JSON',
		name: 'extraXmlFields',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '{}',
		description: '额外业务字段，按企业微信支付文档填写（如发送者头像素材 ID）',
	},
	// --- 付款 ---
	{
		displayName: '商户订单号',
		name: 'partner_trade_no',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['payToEmployee', 'queryPayToEmployee'] },
		},
		default: '',
	},
	{
		displayName: '员工 OpenID',
		name: 'openid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '',
	},
	{
		displayName: '金额(分)',
		name: 'amount',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: 100,
	},
	{
		displayName: '付款说明',
		name: 'desc',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '',
	},
	{
		displayName: '调用方 IP',
		name: 'spbill_create_ip',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '127.0.0.1',
	},
	{
		displayName: '校验姓名',
		name: 'check_name',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		options: [
			{ name: '不校验 NO_CHECK', value: 'NO_CHECK' },
			{ name: '强校验 FORCE_CHECK', value: 'FORCE_CHECK' },
		],
		default: 'NO_CHECK',
	},
	{
		displayName: '收款人姓名',
		name: 're_user_name',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '',
		description: 'check_name=FORCE_CHECK 时必填',
	},
	{
		displayName: '付款消息类型',
		name: 'ww_msg_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		options: [
			{ name: '普通付款 NORMAL_MSG', value: 'NORMAL_MSG' },
			{ name: '审批付款 APPROVAL_MSG', value: 'APPROVAL_MSG' },
		],
		default: 'NORMAL_MSG',
	},
	{
		displayName: '审批单号',
		name: 'approval_number',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['payToEmployee'] } },
		default: '',
		description: 'ww_msg_type=APPROVAL_MSG 时填写',
	},
];
