import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['externalContact'], operation: ['addGroupWelcomeTemplate'] };

export const addGroupWelcomeTemplateDescription: INodeProperties[] = [
	// 文本内容
	{
		displayName: '文本消息内容',
		name: 'text_content',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		typeOptions: { rows: 4 },
		description: '消息文本内容，最长为3000字节。支持%NICKNAME%占位符，发送时会替换为客户昵称。text与附件可以同时发送',
		placeholder: '亲爱的%NICKNAME%用户，欢迎加入我们的客户群！',
	},
	// 附件类型（只能选一个）
	{
		displayName: '附件类型',
		name: 'attachmentType',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '无附件', value: 'none' },
			{ name: '图片', value: 'image' },
			{ name: '链接', value: 'link' },
			{ name: '小程序', value: 'miniprogram' },
			{ name: '文件', value: 'file' },
			{ name: '视频', value: 'video' },
		],
		default: 'none',
		description: 'Text以外的消息类型只能有一个。text与附件可以同时发送，将以两条消息触达客户',
	},
	// 图片
	{
		displayName: '图片Media ID',
		name: 'image_media_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, attachmentType: ['image'] } },
		default: '',
		description: '图片的media_id，可通过素材管理接口获得。media_id和pic_url只需填写一个',
	},
	{
		displayName: '图片URL',
		name: 'image_pic_url',
		type: 'string',
		displayOptions: { show: { ...showOnly, attachmentType: ['image'] } },
		default: '',
		description: '图片的链接，仅可使用上传图片接口得到的链接。media_id和pic_url只需填写一个',
	},
	// 链接
	{
		displayName: '链接标题（必填）',
		name: 'link_title',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, attachmentType: ['link'] } },
		default: '',
		description: '图文消息标题，最长为128字节',
	},
	{
		displayName: '链接封面URL',
		name: 'link_picurl',
		type: 'string',
		displayOptions: { show: { ...showOnly, attachmentType: ['link'] } },
		default: '',
		description: '图文消息封面的URL',
	},
	{
		displayName: '链接描述',
		name: 'link_desc',
		type: 'string',
		displayOptions: { show: { ...showOnly, attachmentType: ['link'] } },
		default: '',
		description: '图文消息的描述，最长为512字节',
	},
	{
		displayName: '链接URL（必填）',
		name: 'link_url',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, attachmentType: ['link'] } },
		default: '',
		description: '图文消息的链接',
	},
	// 小程序
	{
		displayName: '小程序标题（必填）',
		name: 'miniprogram_title',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, attachmentType: ['miniprogram'] } },
		default: '',
		description: '小程序消息标题，最长为64字节',
	},
	{
		displayName: '小程序封面Media ID（必填）',
		name: 'miniprogram_pic_media_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, attachmentType: ['miniprogram'] } },
		default: '',
		description: '小程序消息封面的mediaid，封面图建议尺寸为520*416',
	},
	{
		displayName: '小程序AppID（必填）',
		name: 'miniprogram_appid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, attachmentType: ['miniprogram'] } },
		default: '',
		description: '小程序appid，必须是关联到企业的小程序应用',
	},
	{
		displayName: '小程序页面路径（必填）',
		name: 'miniprogram_page',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, attachmentType: ['miniprogram'] } },
		default: '',
		description: '小程序page路径',
		placeholder: '/path/index',
	},
	// 文件
	{
		displayName: '文件Media ID（必填）',
		name: 'file_media_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, attachmentType: ['file'] } },
		default: '',
		description: '文件ID，可通过素材管理、异步上传临时素材接口获得',
	},
	// 视频
	{
		displayName: '视频Media ID（必填）',
		name: 'video_media_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, attachmentType: ['video'] } },
		default: '',
		description: '视频媒体文件ID，可通过素材管理、异步上传临时素材接口获得',
	},
	// 其他参数
	{
		displayName: '应用AgentID',
		name: 'agentid',
		type: 'number',
		typeOptions: { minValue: 0, numberStepSize: 1 },
		default: 0,
		displayOptions: { show: showOnly },
		description: '授权方安装的应用agentid。仅旧的第三方多应用套件需要填此参数',
	},
	{
		displayName: '是否通知成员',
		name: 'notify',
		type: 'options',
		options: [
			{ name: '通知', value: 1 },
			{ name: '不通知', value: 0 },
		],
		default: 1,
		displayOptions: { show: showOnly },
		description: '是否通知成员将这条入群欢迎语应用到客户群中，不填则通知',
	},
];
