import type { INodeProperties } from 'n8n-workflow';

const showOnly = {
	resource: ['externalContact'],
	operation: ['createMomentStrategy'],
};

export const createMomentStrategyDescription: INodeProperties[] = [
	{
		displayName: '规则组名称',
		name: 'strategy_name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: showOnly },
	},
	{
		displayName: '父规则组ID',
		name: 'parent_id',
		type: 'number',
		typeOptions: { minValue: 0, numberStepSize: 1 },
		default: 0,
		displayOptions: { show: showOnly },
		description: '父规则组ID，如果不指定父规则组则为0',
	},
	{
		displayName: '存在父规则组时，管理范围必须是父规则组的子集，权限会完全继承父组且本节点不会发送权限配置',
		name: 'parentMomentStrategyNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { ...showOnly, parent_id: [{ _cnd: { gt: 0 } }] } },
	},
	{
		displayName: '管理员UserID列表',
		name: 'admin_list',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '规则组管理员 UserID，逗号分隔，不可配置超级管理员，最多 20 个；与下方选择合并',
		placeholder: 'zhangsan,lisi',
	},
	{
		displayName: '管理员(选择)',
		name: 'admin_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: [],
		displayOptions: { show: showOnly },
		description: '与上方列表合并去重，合计最多 20 个',
	},
	{
		displayName: '允许查看成员的全部客户朋友圈发表',
		name: 'privilege_view_moment_list',
		type: 'boolean',
		default: true,
		displayOptions: { show: { ...showOnly, parent_id: [0] } },
	},
	{
		displayName: '允许成员发表客户朋友圈',
		name: 'privilege_send_moment',
		type: 'boolean',
		default: true,
		displayOptions: { show: { ...showOnly, parent_id: [0] } },
		description: '允许成员发表客户朋友圈，默认为true',
	},
	{
		displayName: '允许配置封面和签名',
		name: 'privilege_manage_moment_cover_and_sign',
		type: 'boolean',
		default: true,
		displayOptions: { show: { ...showOnly, parent_id: [0] } },
		description: '配置封面和签名，默认为true',
	},
	{
		displayName: '管理范围成员UserID列表',
		name: 'range_userids',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: 'zhangsan,lisi',
		description: '快捷添加成员节点，逗号分隔；与下方选择/表单合并，合计最多 3000 个节点',
	},
	{
		displayName: '管理范围成员(选择)',
		name: 'range_userids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: showOnly },
		default: [],
		description: '与上方成员列表合并去重',
	},
	{
		displayName: '管理范围成员 JSON',
		name: 'rangeUseridsJson',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择/表单合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '管理范围部门ID列表',
		name: 'range_partyids',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: '1,2,3',
		description: '快捷添加部门节点，逗号分隔；与下方选择/表单合并，合计最多 3000 个节点',
	},
	{
		displayName: '管理范围部门(选择)',
		name: 'range_partyids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getDepartments' },
		displayOptions: { show: showOnly },
		default: [],
		description: '与上方部门列表合并去重',
	},
	{
		displayName: '管理范围部门 JSON',
		name: 'rangePartyidsJson',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择/表单合并去重。支持 [1,2] 或 [{"partyid":1}]',
	},
	{
		displayName: '管理范围(详细)',
		name: 'rangeCollection',
		type: 'fixedCollection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加管理范围节点',
		typeOptions: { multipleValues: true },
		description: '规则组管理范围详细节点；可与上方列表合并，合计最多 3000 个',
		options: [
			{
				displayName: '范围节点',
				name: 'ranges',
				values: [
					{
						displayName: '节点类型',
						name: 'type',
						type: 'options',
						options: [
							{ name: '成员', value: 1 },
							{ name: '部门', value: 2 },
						],
						default: 1,
						description: '规则组管理范围节点类型，1-成员 2-部门',
					},
					{
						displayName: '成员UserID',
						name: 'userid',
						type: 'string',
						default: '',
						displayOptions: { show: { type: [1] } },
						description: '规则组的管理成员ID（type为1时填写）；可与下方选择二选一',
					},
					{
						displayName: '成员(选择)',
						name: 'userid_selected',
						type: 'options',
						typeOptions: { loadOptionsMethod: 'getAllUsers' },
						default: '',
						displayOptions: { show: { type: [1] } },
						description: '与上方字符串二选一；均填写时以字符串为准',
					},
					{
						displayName: '部门ID',
						name: 'partyid',
						type: 'number',
						typeOptions: { minValue: 1, numberStepSize: 1 },
						default: 0,
						displayOptions: { show: { type: [2] } },
						description: '规则组的管理部门ID（type为2时填写）；可与下方选择二选一',
					},
					{
						displayName: '部门(选择)',
						name: 'partyid_selected',
						type: 'options',
						typeOptions: { loadOptionsMethod: 'getDepartments' },
						default: '',
						displayOptions: { show: { type: [2] } },
						description: '与上方部门 ID 二选一；均填写时以数字字段为准',
					},
				],
			},
		],
	},
];
