import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['externalContact'], operation: ['createCustomerAcquisitionLink'] };

export const createCustomerAcquisitionLinkDescription: INodeProperties[] = [
	{
		displayName: '链接名称',
		name: 'link_name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: showOnly },
		description: '获客链接的名称，最长为30个字符',
		placeholder: '获客链接1号',
	},
	{
		displayName: '使用范围类型',
		name: 'rangeType',
		type: 'options',
		required: true,
		displayOptions: { show: showOnly },
		options: [
			{ name: '指定成员', value: 'user', description: '指定成员可使用此链接' },
			{ name: '指定部门', value: 'department', description: '指定部门可使用此链接' },
			{ name: '成员和部门', value: 'both', description: '同时指定成员和部门' },
		],
		default: 'user',
		description: '使用范围类型，range覆盖的总用户数不得超过500人',
	},
	{
		displayName: '成员列表',
		name: 'user_list',
		type: 'string',
		displayOptions: { show: { ...showOnly, rangeType: ['user', 'both'] } },
		default: '',
		description: '支持逗号、竖线或换行分隔，自动去重；使用范围合计最多 500 个节点',
		placeholder: 'zhangsan,lisi',
	},
	{
		displayName: '部门列表',
		name: 'department_list',
		type: 'string',
		displayOptions: { show: { ...showOnly, rangeType: ['department', 'both'] } },
		default: '',
		description: '正整数部门 ID，支持逗号、竖线或换行分隔；部门覆盖人数也计入 500 人限制',
		placeholder: '2,3',
	},
	{
		displayName: '跳过验证',
		name: 'skip_verify',
		type: 'boolean',
		default: true,
		displayOptions: { show: showOnly },
		description: '是否无需验证，默认为true',
	},
	{
		displayName: '标记客户来源',
		name: 'mark_source',
		type: 'boolean',
		default: true,
		displayOptions: { show: showOnly },
		description: '是否标记客户添加来源为该应用创建的获客链接，仅对「营销获客」应用生效',
	},
	{
		displayName: '启用优先分配',
		name: 'enablePriorityOption',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否启用客户与成员关系绑定（仅部分经营类目企业支持）',
	},
	{
		displayName: '优先分配类型',
		name: 'priority_type',
		type: 'options',
		options: [
			{ name: '全企业范围内优先分配给有好友关系的', value: 1 },
			{ name: '指定范围内优先分配有好友关系的', value: 2 },
		],
		default: 1,
		displayOptions: { show: { ...showOnly, enablePriorityOption: [true] } },
		description: '客户与成员关系绑定类型',
	},
	{
		displayName: '优先分配成员列表',
		name: 'priority_userid_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, enablePriorityOption: [true], priority_type: [2] } },
		description: '指定范围时必填，支持逗号、竖线或换行分隔，自动去重，最多 1000 个',
		placeholder: 'tom,lisi',
	},
];
