import type { INodeProperties } from 'n8n-workflow';

const showOnly = {
	resource: ['externalContact'],
	operation: ['editMomentStrategy'],
};

export const editMomentStrategyDescription: INodeProperties[] = [
	{
		displayName: '规则组ID',
		name: 'strategy_id',
		type: 'number',
		typeOptions: { minValue: 1, numberStepSize: 1 },
		required: true,
		default: 1,
		displayOptions: { show: showOnly },
	},
	{
		displayName: '更新规则组名称',
		name: 'updateStrategyName',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '开启后发送新的规则组名称',
	},
	{
		displayName: '规则组名称',
		name: 'strategy_name',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, updateStrategyName: [true] } },
	},
	{
		displayName: '更新管理员列表',
		name: 'updateAdminList',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否更新管理员列表（覆盖旧的负责人列表）',
	},
	{
		displayName: '管理员UserID列表',
		name: 'admin_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, updateAdminList: [true] } },
		description: '管理员 UserID，逗号分隔，将覆盖旧负责人列表；与下方选择合并，最多 20 个',
		placeholder: 'zhangsan,lisi',
	},
	{
		displayName: '管理员(选择)',
		name: 'admin_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: [],
		displayOptions: { show: { ...showOnly, updateAdminList: [true] } },
		description: '与上方列表合并去重',
	},
	{
		displayName: '管理员列表 JSON',
		name: 'adminListJson',
		type: 'json',
		default: '[]',
		displayOptions: { show: { ...showOnly, updateAdminList: [true] } },
		description:
			'可选。非空数组时与上方列表/选择合并去重，最多 20 个。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '更新权限配置',
		name: 'updatePrivilege',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否更新权限配置（覆盖旧的权限配置）',
	},
	{
		displayName: '允许查看成员的全部客户朋友圈发表',
		name: 'privilege_view_moment_list',
		type: 'boolean',
		default: true,
		displayOptions: { show: { ...showOnly, updatePrivilege: [true] } },
	},
	{
		displayName: '允许成员发表客户朋友圈',
		name: 'privilege_send_moment',
		type: 'boolean',
		default: true,
		displayOptions: { show: { ...showOnly, updatePrivilege: [true] } },
	},
	{
		displayName: '允许配置封面和签名',
		name: 'privilege_manage_moment_cover_and_sign',
		type: 'boolean',
		default: true,
		displayOptions: { show: { ...showOnly, updatePrivilege: [true] } },
		description: '配置封面和签名',
	},
	{
		displayName: '添加范围成员UserID列表',
		name: 'range_add_userids',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: 'zhangsan,lisi',
		description: '快捷添加成员节点；与下方选择/详细表单合并',
	},
	{
		displayName: '添加范围成员(选择)',
		name: 'range_add_userids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: showOnly },
		default: [],
		description: '与上方添加成员列表合并去重',
	},
	{
		displayName: '添加范围成员 JSON',
		name: 'rangeAddUseridsJson',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择/表单合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '添加范围部门ID列表',
		name: 'range_add_partyids',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: '1,2',
		description: '快捷添加部门节点；与下方选择/详细表单合并',
	},
	{
		displayName: '添加范围部门(选择)',
		name: 'range_add_partyids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getDepartments' },
		displayOptions: { show: showOnly },
		default: [],
		description: '与上方添加部门列表合并去重',
	},
	{
		displayName: '添加范围部门 JSON',
		name: 'rangeAddPartyidsJson',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择/表单合并去重。支持 [1,2] 或 [{"partyid":1}]',
	},
	{
		displayName: '添加管理范围(详细)',
		name: 'rangeAddCollection',
		type: 'fixedCollection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加管理范围节点',
		typeOptions: { multipleValues: true },
		description: '向管理范围添加的详细节点',
		options: [
			{
				displayName: '范围节点',
				name: 'ranges',
				values: [
					{
						displayName: '节点类型',
						name: 'type',
						type: 'options',
						options: [
							{ name: '成员', value: 1 },
							{ name: '部门', value: 2 },
						],
						default: 1,
						description: '节点类型，1-成员 2-部门',
					},
					{
						displayName: '成员UserID',
						name: 'userid',
						type: 'string',
						default: '',
						displayOptions: { show: { type: [1] } },
						description: '成员userid（type为1时填写）；可与下方选择二选一',
					},
					{
						displayName: '成员(选择)',
						name: 'userid_selected',
						type: 'options',
						typeOptions: { loadOptionsMethod: 'getAllUsers' },
						default: '',
						displayOptions: { show: { type: [1] } },
						description: '与上方字符串二选一；均填写时以字符串为准',
					},
					{
						displayName: '部门ID',
						name: 'partyid',
						type: 'number',
						typeOptions: { minValue: 1, numberStepSize: 1 },
						default: 0,
						displayOptions: { show: { type: [2] } },
						description: '部门partyid（type为2时填写）；可与下方选择二选一',
					},
					{
						displayName: '部门(选择)',
						name: 'partyid_selected',
						type: 'options',
						typeOptions: { loadOptionsMethod: 'getDepartments' },
						default: '',
						displayOptions: { show: { type: [2] } },
						description: '与上方部门 ID 二选一；均填写时以数字字段为准',
					},
				],
			},
		],
	},
	{
		displayName: '添加管理范围节点 JSON',
		name: 'rangeAddNodesJson',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '[]',
		description:
			'可选。非空数组时覆盖上方添加范围详细节点（仍会与列表合并）。支持 [{"type":1,"userid":"..."}] 或 [{"type":2,"partyid":1}]',
	},
	{
		displayName: '删除范围成员UserID列表',
		name: 'range_del_userids',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: 'zhangsan,lisi',
		description: '快捷删除成员节点；与下方选择/详细表单合并',
	},
	{
		displayName: '删除范围成员(选择)',
		name: 'range_del_userids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: showOnly },
		default: [],
		description: '与上方删除成员列表合并去重',
	},
	{
		displayName: '删除范围成员 JSON',
		name: 'rangeDelUseridsJson',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择/表单合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '删除范围部门ID列表',
		name: 'range_del_partyids',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		placeholder: '1,2',
		description: '快捷删除部门节点；与下方选择/详细表单合并',
	},
	{
		displayName: '删除范围部门(选择)',
		name: 'range_del_partyids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getDepartments' },
		displayOptions: { show: showOnly },
		default: [],
		description: '与上方删除部门列表合并去重',
	},
	{
		displayName: '删除范围部门 JSON',
		name: 'rangeDelPartyidsJson',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择/表单合并去重。支持 [1,2] 或 [{"partyid":1}]',
	},
	{
		displayName: '删除管理范围(详细)',
		name: 'rangeDelCollection',
		type: 'fixedCollection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '删除管理范围节点',
		typeOptions: { multipleValues: true },
		description: '从管理范围删除的详细节点',
		options: [
			{
				displayName: '范围节点',
				name: 'ranges',
				values: [
					{
						displayName: '节点类型',
						name: 'type',
						type: 'options',
						options: [
							{ name: '成员', value: 1 },
							{ name: '部门', value: 2 },
						],
						default: 1,
						description: '节点类型，1-成员 2-部门',
					},
					{
						displayName: '成员UserID',
						name: 'userid',
						type: 'string',
						default: '',
						displayOptions: { show: { type: [1] } },
						description: '成员userid（type为1时填写）；可与下方选择二选一',
					},
					{
						displayName: '成员(选择)',
						name: 'userid_selected',
						type: 'options',
						typeOptions: { loadOptionsMethod: 'getAllUsers' },
						default: '',
						displayOptions: { show: { type: [1] } },
						description: '与上方字符串二选一；均填写时以字符串为准',
					},
					{
						displayName: '部门ID',
						name: 'partyid',
						type: 'number',
						typeOptions: { minValue: 1, numberStepSize: 1 },
						default: 0,
						displayOptions: { show: { type: [2] } },
						description: '部门partyid（type为2时填写）；可与下方选择二选一',
					},
					{
						displayName: '部门(选择)',
						name: 'partyid_selected',
						type: 'options',
						typeOptions: { loadOptionsMethod: 'getDepartments' },
						default: '',
						displayOptions: { show: { type: [2] } },
						description: '与上方部门 ID 二选一；均填写时以数字字段为准',
					},
				],
			},
		],
	},
	{
		displayName: '删除管理范围节点 JSON',
		name: 'rangeDelNodesJson',
		type: 'json',
		displayOptions: { show: showOnly },
		default: '[]',
		description:
			'可选。非空数组时覆盖上方删除范围详细节点（仍会与列表合并）。支持 [{"type":1,"userid":"..."}] 或 [{"type":2,"partyid":1}]',
	},
];
