import type { INodeProperties } from 'n8n-workflow';

const showOnly = {
	resource: ['externalContact'],
	operation: ['updateInterceptRule'],
};

export const updateInterceptRuleDescription: INodeProperties[] = [
	{
		displayName: '规则ID（必填）',
		name: 'rule_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: showOnly },
		description: '规则ID',
	},
	{
		displayName: '更新规则名称',
		name: 'updateRuleName',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '开启后才会向企业微信发送规则名称字段',
	},
	{
		displayName: '规则名称',
		name: 'rule_name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { ...showOnly, updateRuleName: [true] } },
		description: '规则名称，长度 1–20 个 UTF-8 字符',
	},
	{
		displayName: '更新敏感词列表',
		name: 'updateWordList',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '开启后才会向企业微信发送敏感词列表字段',
	},
	{
		displayName: '敏感词列表',
		name: 'word_list',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { ...showOnly, updateWordList: [true] } },
		typeOptions: { rows: 3 },
		description: '支持逗号、竖线或换行分隔，自动去重；每项 1–32 个字符，最多 300 项',
		placeholder: '敏感词1,敏感词2',
	},
	{
		displayName: '更新拦截方式',
		name: 'updateInterceptType',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
	},
	{
		displayName: '拦截方式',
		name: 'intercept_type',
		type: 'options',
		options: [
			{ name: '警告并拦截发送', value: 1 },
			{ name: '仅发警告', value: 2 },
		],
		default: 1,
		displayOptions: { show: { ...showOnly, updateInterceptType: [true] } },
	},
	// 更新语义规则
	{
		displayName: '更新拦截语义规则',
		name: 'updateSemantics',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否更新额外的拦截语义规则。若设置为空列表表示清除所有的语义规则',
	},
	{
		displayName: '额外拦截语义规则',
		name: 'semantics_list',
		type: 'multiOptions',
		options: [
			{ name: '手机号', value: 1 },
			{ name: '邮箱地址', value: 2 },
			{ name: '红包', value: 3 },
		],
		default: [],
		displayOptions: { show: { ...showOnly, updateSemantics: [true] } },
		description: '额外的拦截语义规则，若为空表示清除所有的语义规则',
	},
	// 新增适用范围
	{
		displayName: '新增适用范围',
		name: 'enableAddRange',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否新增使用范围',
	},
	{
		displayName: '新增成员UserID列表',
		name: 'add_user_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, enableAddRange: [true] } },
		description: '支持逗号、竖线或换行分隔；与下方选择合并；成员与部门合计每次最多 1000 个节点',
		placeholder: 'zhangsan,lisi',
	},
	{
		displayName: '新增成员(选择)',
		name: 'add_user_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: [],
		displayOptions: { show: { ...showOnly, enableAddRange: [true] } },
		description: '与上方列表合并去重',
	},
	{
		displayName: '新增成员 JSON',
		name: 'addUserListJson',
		type: 'json',
		default: '[]',
		displayOptions: { show: { ...showOnly, enableAddRange: [true] } },
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '新增部门ID列表',
		name: 'add_department_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, enableAddRange: [true] } },
		description: '正整数部门 ID；与下方选择合并；成员与部门合计每次最多 1000 个节点',
		placeholder: '1,2,3',
	},
	{
		displayName: '新增部门(选择)',
		name: 'add_department_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getDepartments' },
		default: [],
		displayOptions: { show: { ...showOnly, enableAddRange: [true] } },
		description: '与上方列表合并去重',
	},
	// 删除适用范围
	{
		displayName: '删除适用范围',
		name: 'enableRemoveRange',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否删除使用范围',
	},
	{
		displayName: '删除成员UserID列表',
		name: 'remove_user_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, enableRemoveRange: [true] } },
		description: '支持逗号、竖线或换行分隔；与下方选择合并；成员与部门合计每次最多 1000 个节点',
		placeholder: 'zhangsan,lisi',
	},
	{
		displayName: '删除成员(选择)',
		name: 'remove_user_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: [],
		displayOptions: { show: { ...showOnly, enableRemoveRange: [true] } },
		description: '与上方列表合并去重',
	},
	{
		displayName: '删除成员 JSON',
		name: 'removeUserListJson',
		type: 'json',
		default: '[]',
		displayOptions: { show: { ...showOnly, enableRemoveRange: [true] } },
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '删除部门ID列表',
		name: 'remove_department_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, enableRemoveRange: [true] } },
		description: '正整数部门 ID；与下方选择合并；成员与部门合计每次最多 1000 个节点',
		placeholder: '1,2,3',
	},
	{
		displayName: '删除部门(选择)',
		name: 'remove_department_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getDepartments' },
		default: [],
		displayOptions: { show: { ...showOnly, enableRemoveRange: [true] } },
		description: '与上方列表合并去重',
	},
];
