import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['externalContact'], operation: ['updateProductAlbum'] };

export const updateProductAlbumDescription: INodeProperties[] = [
	{
		displayName: '商品ID（必填）',
		name: 'product_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: showOnly },
		description: '要更新的商品ID',
	},
	{
		displayName: '更新商品描述',
		name: 'updateDescription',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '开启后才会向企业微信发送商品描述字段',
	},
	{
		displayName: '商品描述',
		name: 'description',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { ...showOnly, updateDescription: [true] } },
		typeOptions: { rows: 3 },
		description: '商品的名称、特色等，不超过 300 个字符',
		placeholder: '世界上最好的商品',
	},
	{
		displayName: '更新商品价格',
		name: 'updatePrice',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '开启后才会向企业微信发送价格字段，也可显式设置为 0',
	},
	{
		displayName: '商品价格（分）',
		name: 'price',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0, maxValue: 500000 },
		displayOptions: { show: { ...showOnly, updatePrice: [true] } },
		description: '商品价格，单位为分，范围 0–500000',
	},
	{
		displayName: '更新商品编码',
		name: 'updateProductSn',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '开启后才会向企业微信发送商品编码字段',
	},
	{
		displayName: '商品编码',
		name: 'product_sn',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { ...showOnly, updateProductSn: [true] } },
		description: '商品编码，不超过 128 个 UTF-8 字节，只能包含数字和英文字母',
		placeholder: 'SKU001',
	},
	{
		displayName: '更新商品图片',
		name: 'updateAttachments',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
	},
	{
		displayName: '商品图片',
		name: 'attachmentCollection',
		type: 'fixedCollection',
		required: true,
		displayOptions: { show: { ...showOnly, updateAttachments: [true] } },
		default: {},
		placeholder: '添加图片',
		typeOptions: { multipleValues: true },
		description: '更新后的完整商品图片列表，必须填写 1–9 个；下方 JSON 非空时覆盖表单',
		options: [
			{
				displayName: '图片',
				name: 'attachments',
				values: [
					{
						displayName: '图片Media ID',
						name: 'media_id',
						type: 'string',
						default: '',
						required: true,
						description: '图片的media_id，仅支持通过上传附件资源接口的资源',
					},
				],
			},
		],
	},
	{
		displayName: '商品图片 JSON',
		name: 'attachmentsJson',
		type: 'json',
		displayOptions: { show: { ...showOnly, updateAttachments: [true] } },
		default: '[]',
		description:
			'可选。非空数组时覆盖上方图片表单。支持 [{"media_id":"..."}] 或 ["media_id"]',
	},
];
