import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['externalContact'], operation: ['updateContactWay'] };

function updateToggle(
	displayName: string,
	name: string,
	description: string,
): INodeProperties {
	return {
		displayName,
		name,
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description,
	};
}

function showWhen(name: string) {
	return { ...showOnly, [name]: [true] };
}

const conclusionShow = showWhen('updateConclusions');

export const updateContactWayDescription: INodeProperties[] = [
	{
		displayName: '联系方式配置ID',
		name: 'config_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: showOnly },
		description: '要更新的企业联系方式配置 ID',
		placeholder: '42b34949e138eb6e027c123cba77fAAA',
	},
	updateToggle('更新成员列表', 'updateUsers', '开启后使用下面的列表覆盖原成员列表；留空会发送空数组'),
	{
		displayName: '配置的成员UserID列表',
		name: 'user',
		type: 'string',
		default: '',
		displayOptions: { show: showWhen('updateUsers') },
		description: '成员 UserID，支持逗号、竖线或换行分隔，最多 100 个；与下方选择合并',
		placeholder: 'zhangsan,lisi,wangwu',
	},
	{
		displayName: '成员(选择)',
		name: 'user_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: [],
		displayOptions: { show: showWhen('updateUsers') },
		description: '与上方列表合并去重',
	},
	{
		displayName: '成员列表 JSON',
		name: 'userJson',
		type: 'json',
		default: '[]',
		displayOptions: { show: showWhen('updateUsers') },
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	updateToggle('更新部门列表', 'updateParty', '开启后使用下面的列表覆盖原部门列表；留空会发送空数组'),
	{
		displayName: '配置的部门ID列表',
		name: 'party',
		type: 'string',
		default: '',
		displayOptions: { show: showWhen('updateParty') },
		description: '正整数部门 ID，支持逗号、竖线或换行分隔；仅多人配置有效；与下方选择合并',
		placeholder: '2,3',
	},
	{
		displayName: '部门(选择)',
		name: 'party_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getDepartments' },
		default: [],
		displayOptions: { show: showWhen('updateParty') },
		description: '与上方列表合并去重',
	},
	updateToggle('更新备注', 'updateRemark', '开启后覆盖原备注；留空可清空备注'),
	{
		displayName: '备注',
		name: 'remark',
		type: 'string',
		typeOptions: { maxValue: 30 },
		default: '',
		displayOptions: { show: showWhen('updateRemark') },
		description: '不超过 30 个字符；留空会发送空字符串',
		placeholder: '渠道客户',
	},
	updateToggle('更新跳过验证', 'updateSkipVerify', '开启后覆盖“是否无需验证”设置'),
	{
		displayName: '跳过验证',
		name: 'skip_verify',
		type: 'boolean',
		default: true,
		displayOptions: { show: showWhen('updateSkipVerify') },
		description: '外部客户添加时是否无需验证',
	},
	updateToggle('更新控件样式', 'updateStyle', '仅“在小程序中联系”的配置生效'),
	{
		displayName: '样式',
		name: 'style',
		type: 'options',
		options: [
			{ name: '样式1', value: 1 },
			{ name: '样式2', value: 2 },
			{ name: '样式3', value: 3 },
		],
		default: 1,
		displayOptions: { show: showWhen('updateStyle') },
		description: '多人联系方式仅支持样式 1 或 2，接口会按原配置类型校验',
	},
	updateToggle('更新 State 参数', 'updateState', '开启后覆盖渠道 State；留空可清空'),
	{
		displayName: '自定义State参数',
		name: 'state',
		type: 'string',
		typeOptions: { maxValue: 30 },
		default: '',
		displayOptions: { show: showWhen('updateState') },
		description: '不超过 30 个字符；留空会发送空字符串',
		placeholder: 'teststate',
	},
	updateToggle('更新二维码有效期', 'updateExpiresIn', '仅临时会话配置有效'),
	{
		displayName: '二维码有效期（秒）',
		name: 'expires_in',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1209600, numberStepSize: 1 },
		default: 604800,
		displayOptions: { show: showWhen('updateExpiresIn') },
		description: '1–1209600 秒，最多 14 天',
	},
	updateToggle('更新会话有效期', 'updateChatExpiresIn', '仅临时会话配置有效'),
	{
		displayName: '会话有效期（秒）',
		name: 'chat_expires_in',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1209600, numberStepSize: 1 },
		default: 86400,
		displayOptions: { show: showWhen('updateChatExpiresIn') },
		description: '1–1209600 秒，最多 14 天',
	},
	updateToggle('更新客户 UnionID', 'updateUnionid', '仅临时会话配置有效；留空可移除限制'),
	{
		displayName: '客户UnionID',
		name: 'unionid',
		type: 'string',
		default: '',
		displayOptions: { show: showWhen('updateUnionid') },
		description: '可进行临时会话的客户 UnionID；留空会发送空字符串',
		placeholder: 'oxTWIuGaIt6gTKsQRLau2M0AAAA',
	},
	updateToggle('更新客户来源标记', 'updateMarkSource', '仅营销获客应用且由创建该配置的应用更新时有效'),
	{
		displayName: '标记客户来源',
		name: 'mark_source',
		type: 'boolean',
		default: true,
		displayOptions: { show: showWhen('updateMarkSource') },
		description: '是否标记客户添加来源为该应用创建的「联系我」',
	},
	updateToggle('更新结束语', 'updateConclusions', '仅仍有效的临时会话配置可更新'),
	{
		displayName: '结束语类型',
		name: 'conclusionType',
		type: 'options',
		displayOptions: { show: conclusionShow },
		options: [
			{ name: '文本', value: 'text' },
			{ name: '图片', value: 'image' },
			{ name: '链接', value: 'link' },
			{ name: '小程序', value: 'miniprogram' },
		],
		default: 'text',
		description: '选择一种结束语内容；隐藏类型的旧值不会发送',
	},
	{
		displayName: '文本内容',
		name: 'conclusion_text',
		type: 'string',
		typeOptions: { rows: 3 },
		required: true,
		displayOptions: { show: { ...conclusionShow, conclusionType: ['text'] } },
		default: '',
		description: '最长 4000 个 UTF-8 字节',
	},
	{
		displayName: '图片Media ID',
		name: 'conclusion_image_media_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...conclusionShow, conclusionType: ['image'] } },
		default: '',
	},
	{
		displayName: '链接标题',
		name: 'conclusion_link_title',
		type: 'string',
		required: true,
		displayOptions: { show: { ...conclusionShow, conclusionType: ['link'] } },
		default: '',
		description: '最长 128 个 UTF-8 字节',
	},
	{
		displayName: '链接封面URL',
		name: 'conclusion_link_picurl',
		type: 'string',
		displayOptions: { show: { ...conclusionShow, conclusionType: ['link'] } },
		default: '',
	},
	{
		displayName: '链接描述',
		name: 'conclusion_link_desc',
		type: 'string',
		displayOptions: { show: { ...conclusionShow, conclusionType: ['link'] } },
		default: '',
		description: '最长 512 个 UTF-8 字节',
	},
	{
		displayName: '链接URL',
		name: 'conclusion_link_url',
		type: 'string',
		required: true,
		displayOptions: { show: { ...conclusionShow, conclusionType: ['link'] } },
		default: '',
	},
	{
		displayName: '小程序标题',
		name: 'conclusion_miniprogram_title',
		type: 'string',
		required: true,
		displayOptions: { show: { ...conclusionShow, conclusionType: ['miniprogram'] } },
		default: '',
		description: '最长 64 个 UTF-8 字节',
	},
	{
		displayName: '小程序AppID',
		name: 'conclusion_miniprogram_appid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...conclusionShow, conclusionType: ['miniprogram'] } },
		default: '',
	},
	{
		displayName: '小程序页面路径',
		name: 'conclusion_miniprogram_page',
		type: 'string',
		required: true,
		displayOptions: { show: { ...conclusionShow, conclusionType: ['miniprogram'] } },
		default: '',
	},
	{
		displayName: '小程序封面Media ID',
		name: 'conclusion_miniprogram_pic_media_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...conclusionShow, conclusionType: ['miniprogram'] } },
		default: '',
	},
];
