import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['externalContact'], operation: ['updateCustomerAcquisitionLink'] };

export const updateCustomerAcquisitionLinkDescription: INodeProperties[] = [
	{
		displayName: '链接ID',
		name: 'link_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: showOnly },
		description: '获客链接的ID，需要是当前应用创建',
	},
	{
		displayName: '更新链接名称',
		name: 'updateLinkName',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '开启后才会向企业微信发送链接名称字段',
	},
	{
		displayName: '链接名称',
		name: 'link_name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { ...showOnly, updateLinkName: [true] } },
		description: '更新后的链接名称，最长 30 个字符',
	},
	{
		displayName: '更新使用范围',
		name: 'updateRange',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否更新使用范围（覆盖更新）',
	},
	{
		displayName: '使用范围类型',
		name: 'rangeType',
		type: 'options',
		displayOptions: { show: { ...showOnly, updateRange: [true] } },
		options: [
			{ name: '指定成员', value: 'user', description: '指定成员可使用此链接' },
			{ name: '指定部门', value: 'department', description: '指定部门可使用此链接' },
			{ name: '成员和部门', value: 'both', description: '同时指定成员和部门' },
		],
		default: 'user',
		description: '使用范围类型，覆盖的总人数不能超过500人',
	},
	{
		displayName: '成员UserID列表',
		name: 'user_list',
		type: 'string',
		displayOptions: { show: { ...showOnly, updateRange: [true], rangeType: ['user', 'both'] } },
		default: '',
		description: '支持逗号、竖线或换行分隔；与下方选择合并；覆盖范围合计最多 500 个节点',
		placeholder: 'zhangsan,lisi',
	},
	{
		displayName: '成员(选择)',
		name: 'user_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: [],
		displayOptions: { show: { ...showOnly, updateRange: [true], rangeType: ['user', 'both'] } },
		description: '与上方列表合并去重',
	},
	{
		displayName: '成员列表 JSON',
		name: 'userListJson',
		type: 'json',
		default: '[]',
		displayOptions: { show: { ...showOnly, updateRange: [true], rangeType: ['user', 'both'] } },
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '部门ID列表',
		name: 'department_list',
		type: 'string',
		displayOptions: { show: { ...showOnly, updateRange: [true], rangeType: ['department', 'both'] } },
		default: '',
		description: '正整数部门 ID，支持逗号、竖线或换行分隔；与下方选择合并；部门覆盖人数也计入 500 人限制',
		placeholder: '2,3',
	},
	{
		displayName: '部门(选择)',
		name: 'department_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getDepartments' },
		default: [],
		displayOptions: { show: { ...showOnly, updateRange: [true], rangeType: ['department', 'both'] } },
		description: '与上方列表合并去重',
	},
	{
		displayName: '部门列表 JSON',
		name: 'departmentListJson',
		type: 'json',
		default: '[]',
		displayOptions: { show: { ...showOnly, updateRange: [true], rangeType: ['department', 'both'] } },
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 [1,2] 或 [{"partyid":1}]',
	},
	{
		displayName: '更新跳过验证设置',
		name: 'updateSkipVerify',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '开启后才会向企业微信发送跳过验证设置',
	},
	{
		displayName: '跳过验证',
		name: 'skip_verify',
		type: 'boolean',
		default: true,
		displayOptions: { show: { ...showOnly, updateSkipVerify: [true] } },
		description: '是否无需验证',
	},
	{
		displayName: '更新客户来源标记',
		name: 'updateMarkSource',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '开启后才会向企业微信发送客户来源标记',
	},
	{
		displayName: '标记客户来源',
		name: 'mark_source',
		type: 'boolean',
		default: true,
		displayOptions: { show: { ...showOnly, updateMarkSource: [true] } },
		description: '是否标记客户添加来源为该应用创建的获客链接，仅对「营销获客」应用生效',
	},
	{
		displayName: '更新优先分配配置',
		name: 'updatePriorityOption',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否更新客户与成员关系绑定配置（覆盖更新，仅部分经营类目企业支持）',
	},
	{
		displayName: '优先分配类型',
		name: 'priority_type',
		type: 'options',
		options: [
			{ name: '全企业范围内优先分配给有好友关系的', value: 1 },
			{ name: '指定范围内优先分配有好友关系的', value: 2 },
		],
		default: 1,
		displayOptions: { show: { ...showOnly, updatePriorityOption: [true] } },
		description: '客户与成员关系绑定类型',
	},
	{
		displayName: '优先分配成员UserID列表',
		name: 'priority_userid_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, updatePriorityOption: [true], priority_type: [2] } },
		description: '指定范围时必填，支持逗号、竖线或换行分隔；与下方选择合并，最多 1000 个',
		placeholder: 'tom,lisi',
	},
	{
		displayName: '优先分配成员(选择)',
		name: 'priority_userid_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: [],
		displayOptions: { show: { ...showOnly, updatePriorityOption: [true], priority_type: [2] } },
		description: '与上方列表合并去重',
	},
	{
		displayName: '优先分配成员 JSON',
		name: 'priorityUseridListJson',
		type: 'json',
		default: '[]',
		displayOptions: { show: { ...showOnly, updatePriorityOption: [true], priority_type: [2] } },
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
];
