import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['externalpay'] };

export const externalpayDescription: INodeProperties[] = [
	{
		displayName: '操作',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnly },
		options: [
			{
				name: '[商户号] 查询商户号详情',
				value: 'getMerchant',
				action: '查询商户号详情',
				description: '查询商户号详情',
			},
			{
				name: '[商户号] 设置商户号使用范围',
				value: 'setMchUseScope',
				action: '设置商户号使用范围',
				description: '设置商户号可使用范围',
			},
			{
				name: '[收款] 获取对外收款记录',
				value: 'getBillList',
				action: '获取对外收款记录',
				description: '获取对外收款记录',
			},
			{
				name: '[收款] 获取收款项目商户单号',
				value: 'getPaymentInfo',
				action: '获取收款项目商户单号',
				description: '获取收款项目的商户单号',
			},
			{
				name: '[资金] 获取资金流水',
				value: 'getFundFlow',
				action: '获取资金流水',
				description: '获取资金流水',
			},
		],
		default: 'getBillList',
	},
	{
		displayName: '管理企业对外收款，包括商户号、收款记录与资金流水。企业红包、向员工付款请使用「企业红包与向员工付款」；小程序进件请使用「小程序对外收款」。',
		name: 'corpPayNotice',
		type: 'notice',
		displayOptions: { show: showOnly },
		default: '',
	},
	// getMerchant / setMchUseScope
	{
		displayName: '商户号',
		name: 'mch_id',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['getMerchant', 'setMchUseScope'] },
		},
		default: '',
		description:
			'微信支付商户号 mch_id，不超过 32 个 UTF-8 字节。<a href="https://developer.work.weixin.qq.com/document/path/93666" target="_blank">官方文档</a>',
	},
	{
		displayName: '商户号',
		name: 'mch_id',
		type: 'string',
		displayOptions: {
			show: { ...showOnly, operation: ['getFundFlow'] },
		},
		default: '',
		description: '商户号 ID，不超过 32 个 UTF-8 字节；不填则拉取所有商户号的资金流水',
	},

	{
		displayName: '使用范围成员',
		name: 'scope_users',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['setMchUseScope'] } },
		default: '',
		placeholder: 'zhangsan,lisi',
		typeOptions: { rows: 2 },
		description: '成员 UserID 列表；支持逗号、中文逗号、竖线或换行分隔，重复值会自动去除；与下方选择合并',
	},
	{
		displayName: '使用范围成员(选择)',
		name: 'scope_users_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: { ...showOnly, operation: ['setMchUseScope'] } },
		default: [],
		description: '与上方成员列表合并去重',
	},
	{
		displayName: '使用范围成员 JSON',
		name: 'scopeUsersJson',
		type: 'json',
		displayOptions: { show: { ...showOnly, operation: ['setMchUseScope'] } },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '使用范围部门',
		name: 'scope_partyids',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['setMchUseScope'] } },
		default: '',
		placeholder: '1,2',
		typeOptions: { rows: 2 },
		description: '正整数部门 ID 列表；支持逗号、中文逗号、竖线或换行分隔；与下方选择合并',
	},
	{
		displayName: '使用范围部门(选择)',
		name: 'scope_partyids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getDepartments' },
		displayOptions: { show: { ...showOnly, operation: ['setMchUseScope'] } },
		default: [],
		description: '与上方部门列表合并去重',
	},
	{
		displayName: '使用范围部门 JSON',
		name: 'scopePartyidsJson',
		type: 'json',
		displayOptions: { show: { ...showOnly, operation: ['setMchUseScope'] } },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 [1,2] 或 [{"partyid":1}]',
	},
	{
		displayName: '使用范围标签',
		name: 'scope_tagids',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['setMchUseScope'] } },
		default: '',
		placeholder: '1,2',
		typeOptions: { rows: 2 },
		description: '正整数标签 ID 列表；支持逗号、中文逗号、竖线或换行分隔；与下方选择合并',
	},
	{
		displayName: '使用范围标签(选择)',
		name: 'scope_tagids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getTags' },
		displayOptions: { show: { ...showOnly, operation: ['setMchUseScope'] } },
		default: [],
		description: '与上方标签列表合并去重',
	},
	{
		displayName: '使用范围标签 JSON',
		name: 'scopeTagidsJson',
		type: 'json',
		displayOptions: { show: { ...showOnly, operation: ['setMchUseScope'] } },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 [1,2] 或 [{"tagid":1}]',
	},
	{
		displayName: '该操作会整体更新商户号可使用范围。请确认成员、部门与标签列表完整后执行。',
		name: 'scopeUpdateNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['setMchUseScope'] } },
		default: '',
	},
	// getBillList / getFundFlow
	{
		displayName: '开始时间',
		name: 'begin_time',
		type: 'dateTime',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['getBillList', 'getFundFlow'] },
		},
		default: '',
		description: 'begin_time（Unix 秒）',
	},
	{
		displayName: '结束时间',
		name: 'end_time',
		type: 'dateTime',
		required: true,
		displayOptions: {
			show: { ...showOnly, operation: ['getBillList', 'getFundFlow'] },
		},
		default: '',
		description: 'end_time（Unix 秒），不能早于开始时间，起止间隔不超过 31 天',
	},
	{
		displayName: '收款成员UserID',
		name: 'payee_userid',
		type: 'string',
		displayOptions: { show: { ...showOnly, operation: ['getBillList'] } },
		default: '',
		description: '企业收款成员 userid，不填则为全部成员；可与下方选择二选一',
	},
	{
		displayName: '收款成员(选择)',
		name: 'payee_userid_selected',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: { ...showOnly, operation: ['getBillList'] } },
		default: '',
		description: '与上方字符串二选一；均填写时以字符串为准',
	},
	{
		displayName: '游标',
		name: 'cursor',
		type: 'string',
		displayOptions: {
			show: { ...showOnly, operation: ['getBillList', 'getFundFlow'] },
		},
		default: '',
		description: '分页游标 cursor',
	},
	{
		displayName: '返回数量',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000, numberStepSize: 1 },
		displayOptions: { show: { ...showOnly, operation: ['getBillList'] } },
		default: 10,
		description: '返回的最大记录数，最多 1000 条',
	},
	{
		displayName: '返回数量',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 200, numberStepSize: 1 },
		displayOptions: { show: { ...showOnly, operation: ['getFundFlow'] } },
		default: 100,
		description: '返回的最大记录数，默认 100，最多 200 条',
	},
	{
		displayName: '只能查询不早于 2022-12-01 且最长保留 3 年的流水；当日流水通常在次日上午 11 点后生成。',
		name: 'fundFlowNotice',
		type: 'notice',
		displayOptions: { show: { ...showOnly, operation: ['getFundFlow'] } },
		default: '',
	},
	// getPaymentInfo
	{
		displayName: '收款项目单号',
		name: 'payment_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, operation: ['getPaymentInfo'] } },
		default: '',
		description:
			'payment_id，发起对外收款返回。<a href="https://developer.work.weixin.qq.com/document/path/95944" target="_blank">官方文档</a>',
	},
];
