import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['checkin'], operation: ['addCheckinRecord'] };
const showSingle = { ...showOnly, recordInputMode: ['single'] };

export const addCheckinRecordDescription: INodeProperties[] = [
	{
		displayName: '输入方式',
		name: 'recordInputMode',
		type: 'options',
		displayOptions: { show: showOnly },
		options: [
			{ name: '单条表单', value: 'single' },
			{ name: '批量 JSON', value: 'json' },
		],
		default: 'single',
		description: '单条表单适合普通操作；批量 JSON 一次最多添加 200 条记录',
	},
	{
		displayName: '成员UserID',
		name: 'userid',
		type: 'string',
		displayOptions: { show: showSingle },
		default: '',
		description: '成员的 UserID；可与下方选择二选一',
	},
	{
		displayName: '成员(选择)',
		name: 'userid_selected',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: '',
		displayOptions: { show: showSingle },
		description: '与上方字符串二选一；均填写时以字符串为准',
	},
	{
		displayName: '打卡时间',
		name: 'checkin_time',
		type: 'dateTime',
		required: true,
		displayOptions: { show: showSingle },
		default: '',
		description: '打卡时间，发送为 Unix 时间戳（秒）',
	},
	{
		displayName: '打卡地点标题',
		name: 'location_title',
		type: 'string',
		required: true,
		displayOptions: { show: showSingle },
		default: '',
		description: '打卡地点标题，最多 1024 个字符',
	},
	{
		displayName: '打卡地点详情',
		name: 'location_detail',
		type: 'string',
		required: true,
		displayOptions: { show: showSingle },
		default: '',
		description: '打卡地点详情，最多 1024 个字符',
	},
	{
		displayName: '设备类型',
		name: 'device_type',
		type: 'options',
		required: true,
		displayOptions: { show: showSingle },
		options: [
			{ name: '门禁', value: 1 },
			{ name: '考勤机（人脸/指纹）', value: 2 },
			{ name: '其他', value: 3 },
		],
		default: 1,
		description: '打卡设备类型，文档必填',
	},
	{
		displayName: '设备详情',
		name: 'device_detail',
		type: 'string',
		required: true,
		displayOptions: { show: showSingle },
		default: '',
		description: '打卡设备品牌或说明，最多 40 个字符',
	},
	{
		displayName: '备注',
		name: 'notes',
		type: 'string',
		displayOptions: { show: showSingle },
		default: '',
		description: '打卡备注，最多 1024 个字符',
	},
	{
		displayName: '包含位置坐标',
		name: 'includeCoordinates',
		type: 'boolean',
		displayOptions: { show: showSingle },
		default: false,
		description: '开启后发送 GCJ-02 经纬度的百万倍整数；关闭时不发送坐标字段',
	},
	{
		displayName: '经度 × 1000000',
		name: 'lng',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showSingle, includeCoordinates: [true] } },
		default: 0,
		typeOptions: { minValue: -180000000, maxValue: 180000000 },
	},
	{
		displayName: '纬度 × 1000000',
		name: 'lat',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showSingle, includeCoordinates: [true] } },
		default: 0,
		typeOptions: { minValue: -90000000, maxValue: 90000000 },
	},
	{
		displayName: 'WiFi名称',
		name: 'wifiname',
		type: 'string',
		displayOptions: { show: showSingle },
		default: '',
		description: 'WiFi 名称，最多 1024 个字符；填写后必须同时填写 MAC 地址',
	},
	{
		displayName: 'WiFi MAC',
		name: 'wifimac',
		type: 'string',
		displayOptions: { show: showSingle },
		default: '',
		placeholder: 'a2:8b:7f:c0:27:4b',
		description: 'WiFi MAC/BSSID，格式为六组十六进制字节',
	},
	{
		displayName: '附件MediaID',
		name: 'mediaids',
		type: 'string',
		displayOptions: { show: showSingle },
		default: '',
		description: '打卡附件 media_id，当前最多允许 1 个',
	},
	{
		displayName: '打卡记录JSON',
		name: 'recordsJson',
		type: 'json',
		required: true,
		displayOptions: { show: { ...showOnly, recordInputMode: ['json'] } },
		default: '[]',
		typeOptions: { rows: 12 },
		description: 'records 数组，不要再包一层 records；一次 1–200 条。每条记录会按官方字段规则校验',
	},
];
