import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['checkin'], operation: ['addCheckinRecord'] };

export const addCheckinRecordDescription: INodeProperties[] = [
	{
		displayName: '成员UserID',
		name: 'userid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: '成员的 UserID。<a href="https://developer.work.weixin.qq.com/document/path/99647" target="_blank">官方文档</a>',
	},
	{
		displayName: '打卡时间',
		name: 'checkin_time',
		type: 'dateTime',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: '打卡时间，Unix 时间戳（秒）',
	},
	{
		displayName: '打卡地点标题',
		name: 'location_title',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: '打卡地点 title，限制 1024 字符',
	},
	{
		displayName: '打卡地点详情',
		name: 'location_detail',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: '打卡地点详情，限制 1024 字符',
	},
	{
		displayName: '备注',
		name: 'notes',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '打卡备注（notes），限制 1024 字符',
	},
	{
		displayName: '经度',
		name: 'lng',
		type: 'number',
		displayOptions: { show: showOnly },
		default: 0,
		description: '打卡地点经度（可选，接口单位与官方文档一致）',
	},
	{
		displayName: '纬度',
		name: 'lat',
		type: 'number',
		displayOptions: { show: showOnly },
		default: 0,
		description: '打卡地点纬度（可选）',
	},
	{
		displayName: '设备类型',
		name: 'device_type',
		type: 'number',
		displayOptions: { show: showOnly },
		default: 0,
		description: '设备类型 device_type（可选，0 表示不传）',
	},
	{
		displayName: '设备详情',
		name: 'device_detail',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '设备详情 device_detail（可选）',
	},
	{
		displayName: 'WiFi名称',
		name: 'wifiname',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '打卡 WiFi 名称（可选）',
	},
	{
		displayName: 'WiFi MAC',
		name: 'wifimac',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '打卡 WiFi MAC/bssid，传入 wifiname 时必填，格式如 a2:8b:7f:c0:27:4b',
	},
	{
		displayName: '附件MediaID',
		name: 'mediaids',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '打卡附件 media_id，当前最多 1 个；多个用逗号分隔',
	},
];
