import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['checkin'], operation: ['manageRules'] };

export const manageRulesDescription: INodeProperties[] = [
	{
		displayName: '操作类型',
		name: 'action',
		type: 'options',
		required: true,
		displayOptions: { show: showOnly },
		options: [
			{ name: '创建规则', value: 'create' },
			{ name: '更新规则', value: 'update' },
			{ name: '删除规则', value: 'delete' },
		],
		default: 'create',
		description: '管理打卡规则的操作类型',
	},
	{
		displayName: '规则ID',
		name: 'groupid',
		type: 'number',
		displayOptions: { show: { ...showOnly, action: ['update', 'delete'] } },
		default: 0,
		required: true,
		description: '打卡规则 groupid（更新/删除时必填）',
	},
	{
		displayName: '立即生效',
		name: 'effective_now',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['create', 'update', 'delete'] } },
		default: false,
		description: 'effective_now，是否立即生效',
	},
	{
		displayName: '覆盖表单中的基础字段',
		name: 'includeBasicFields',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['update'] } },
		default: false,
		description:
			'更新规则时默认只发送规则 ID 和高级 JSON，避免表单默认值意外覆盖现有配置；开启后才发送下方基础字段',
	},
	{
		displayName: '规则名称',
		name: 'groupname',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: '',
	},
	{
		displayName: '规则类型',
		name: 'grouptype',
		type: 'options',
		displayOptions: { show: { ...showOnly, action: ['create'] } },
		options: [
			{ name: '固定时间上下班', value: 1 },
			{ name: '按班次上下班', value: 2 },
			{ name: '自由上下班', value: 3 },
		],
		default: 1,
	},
	{
		displayName: '打卡方式',
		name: 'checkin_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		options: [
			{ name: '手机', value: 0 },
			{ name: '考勤机', value: 2 },
			{ name: '手机和考勤机', value: 3 },
		],
		default: 0,
		description: 'group.type 字段',
	},
	{
		displayName: '应用范围成员UserID列表',
		name: 'range_userids',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: '',
		placeholder: 'zhangsan,lisi',
		description: 'range.userid，逗号分隔；与下方选择合并',
	},
	{
		displayName: '应用范围成员(选择)',
		name: 'range_userids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: [],
		description: '与上方列表合并去重',
	},
	{
		displayName: '应用范围部门ID列表',
		name: 'range_partyids',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: '',
		placeholder: '1,2',
		description: 'range.party_id，逗号分隔；与下方选择合并',
	},
	{
		displayName: '应用范围部门(选择)',
		name: 'range_partyids_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getDepartments' },
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: [],
		description: '与上方列表合并去重',
	},
	{
		displayName: '应用范围标签ID列表',
		name: 'range_tagids',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: '',
		placeholder: '1,2',
		description: 'range.tagid，逗号分隔',
	},
	{
		displayName: '白名单成员UserID列表',
		name: 'white_users',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: '',
		placeholder: 'zhangsan',
		description: 'white_users，无需打卡的成员；与下方选择合并',
	},
	{
		displayName: '白名单成员(选择)',
		name: 'white_users_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: [],
		description: '与上方列表合并去重',
	},
	{
		displayName: '同步法定节假日',
		name: 'sync_holidays',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: true,
	},
	{
		displayName: '打卡必须拍照',
		name: 'need_photo',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: false,
	},
	{
		displayName: '备注可用本地图片',
		name: 'note_can_use_local_pic',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: false,
	},
	{
		displayName: '非工作日允许打卡',
		name: 'allow_checkin_offworkday',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: false,
	},
	{
		displayName: '非工作日允许提交补卡',
		name: 'allow_apply_offworkday',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: false,
	},
	{
		displayName: '人脸识别打卡',
		name: 'use_face_detect',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: false,
	},
	{
		displayName: '人脸活体检测',
		name: 'open_face_live_detect',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: false,
	},
	{
		displayName: '同步外出打卡',
		name: 'sync_out_checkin',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: false,
	},
	{
		displayName: '打卡交替方式',
		name: 'checkin_method_type',
		type: 'options',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		options: [
			{ name: '手机', value: 0 },
			{ name: '智慧硬件', value: 1 },
			{ name: '手机+智慧硬件', value: 2 },
		],
		default: 0,
		description:
			'0 多组交替；1 单组交替；2 仅记录打卡时间。固定/排班上下班在休息时生效，自由上下班始终生效',
	},
	{
		displayName: '工作日',
		name: 'workdays',
		type: 'multiOptions',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: [1, 2, 3, 4, 5],
		description: '简易固定班次工作日；0 表示周日，1–6 表示周一到周六',
		options: [
			{ name: '周日', value: 0 },
			{ name: '周一', value: 1 },
			{ name: '周二', value: 2 },
			{ name: '周三', value: 3 },
			{ name: '周四', value: 4 },
			{ name: '周五', value: 5 },
			{ name: '周六', value: 6 },
		],
	},
	{
		displayName: '上班时间',
		name: 'work_sec',
		type: 'options',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: 32400,
		description: '距 0 点秒数；也可用高级 JSON 覆盖',
		options: [
			{ name: '08:00', value: 28800 },
			{ name: '08:30', value: 30600 },
			{ name: '09:00', value: 32400 },
			{ name: '09:30', value: 34200 },
			{ name: '10:00', value: 36000 },
		],
	},
	{
		displayName: '下班时间',
		name: 'off_work_sec',
		type: 'options',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: 64800,
		description: '距 0 点秒数；也可用高级 JSON 覆盖',
		options: [
			{ name: '17:00', value: 61200 },
			{ name: '17:30', value: 63000 },
			{ name: '18:00', value: 64800 },
			{ name: '18:30', value: 66600 },
			{ name: '19:00', value: 68400 },
			{ name: '20:00', value: 72000 },
			{ name: '21:00', value: 75600 },
		],
	},
	{
		displayName: '最早上班打卡时间',
		name: 'earliest_work_sec',
		type: 'options',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: 28800,
		description: '须为整分钟；默认 08:00',
		options: [
			{ name: '06:00', value: 21600 },
			{ name: '07:00', value: 25200 },
			{ name: '07:30', value: 27000 },
			{ name: '08:00', value: 28800 },
			{ name: '08:30', value: 30600 },
			{ name: '09:00', value: 32400 },
		],
	},
	{
		displayName: '最晚上班打卡时间',
		name: 'latest_work_sec',
		type: 'options',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: 36000,
		description: '须为整分钟；默认 10:00',
		options: [
			{ name: '09:00', value: 32400 },
			{ name: '09:30', value: 34200 },
			{ name: '10:00', value: 36000 },
			{ name: '10:30', value: 37800 },
			{ name: '11:00', value: 39600 },
			{ name: '12:00', value: 43200 },
		],
	},
	{
		displayName: '最早下班打卡时间',
		name: 'earliest_off_work_sec',
		type: 'options',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: 61200,
		description: '须为整分钟；默认 17:00',
		options: [
			{ name: '16:00', value: 57600 },
			{ name: '16:30', value: 59400 },
			{ name: '17:00', value: 61200 },
			{ name: '17:30', value: 63000 },
			{ name: '18:00', value: 64800 },
		],
	},
	{
		displayName: '最晚下班打卡时间',
		name: 'latest_off_work_sec',
		type: 'options',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: 68400,
		description: '须为整分钟；默认 19:00',
		options: [
			{ name: '18:00', value: 64800 },
			{ name: '19:00', value: 68400 },
			{ name: '20:00', value: 72000 },
			{ name: '21:00', value: 75600 },
			{ name: '22:00', value: 79200 },
			{ name: '23:00', value: 82800 },
			{ name: '23:59', value: 86340 },
		],
	},
	{
		displayName: '位置打卡点',
		name: 'locInfosCollection',
		type: 'fixedCollection',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: {},
		placeholder: '添加位置',
		typeOptions: { multipleValues: true },
		description: 'loc_infos',
		options: [
			{
				displayName: '位置',
				name: 'locs',
				values: [
					{
						displayName: '纬度*1000000',
						name: 'lat',
						type: 'number',
						default: 0,
					},
					{
						displayName: '经度*1000000',
						name: 'lng',
						type: 'number',
						default: 0,
					},
					{
						displayName: '地点名称',
						name: 'loc_title',
						type: 'string',
						default: '',
					},
					{
						displayName: '详细地址',
						name: 'loc_detail',
						type: 'string',
						default: '',
					},
					{
						displayName: '范围(米)',
						name: 'distance',
						type: 'number',
						default: 300,
					},
				],
			},
		],
	},
	{
		displayName: 'WiFi打卡点',
		name: 'wifiInfosCollection',
		type: 'fixedCollection',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: {},
		placeholder: '添加WiFi',
		typeOptions: { multipleValues: true },
		description: 'wifimac_infos',
		options: [
			{
				displayName: 'WiFi',
				name: 'wifis',
				values: [
					{
						displayName: 'WiFi名称',
						name: 'wifiname',
						type: 'string',
						default: '',
					},
					{
						displayName: 'MAC地址',
						name: 'wifimac',
						type: 'string',
						default: '',
						placeholder: 'c0:7b:bc:37:f8:d3',
					},
				],
			},
		],
	},
	{
		displayName: '使用高级配置(JSON)',
		name: 'useAdvancedConfig',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['create', 'update'] } },
		default: false,
		description: '开启后 advancedConfig 会合并进 group（可覆盖上方字段）',
	},
	{
		displayName: '高级配置JSON',
		name: 'advancedConfig',
		type: 'json',
		displayOptions: {
			show: { ...showOnly, action: ['create', 'update'], useAdvancedConfig: [true] },
		},
		default: '{}',
		description:
			'完整 group 或 group 内字段对象；JSON 字段优先。可配置 checkindate、schedulelist、ot_info_v2、buka_remind 等所有文档字段',
	},
];
