import type { INodeProperties } from 'n8n-workflow';
import type { ExtraHttpOp } from '../../shared/extraHttpOp';
import { extraHttpOpOptions } from '../../shared/extraHttpOp';

/** 家校补全接口（部门 / 学生家长 / 直播 / 模式设置） */
export const schoolExtraHttpOps: ExtraHttpOp[] = [
	{ id: 'departmentCreate', name: '[家校部门] 创建部门', action: '创建家校部门', description: '创建家校部门', path: '/cgi-bin/school/department/create', method: 'POST' },
	{ id: 'departmentDelete', name: '[家校部门] 删除部门', action: '删除家校部门', description: '删除家校部门', path: '/cgi-bin/school/department/delete', method: 'GET' },
	{ id: 'departmentList', name: '[家校部门] 获取部门列表', action: '获取家校部门列表', description: '获取家校部门列表', path: '/cgi-bin/school/department/list', method: 'GET' },
	{ id: 'departmentUpdate', name: '[家校部门] 更新部门', action: '更新家校部门', description: '更新家校部门', path: '/cgi-bin/school/department/update', method: 'POST' },
	{ id: 'getChatCreateMode', name: '[家校] 获取群创建模式', action: '获取家校群创建模式', description: '获取家校群创建模式', path: '/cgi-bin/school/get_chat_create_mode', method: 'GET' },
	{ id: 'getuserinfo', name: '[家校] 获取访问用户身份', action: '获取家校访问用户身份', description: '获取家校访问用户身份', path: '/cgi-bin/school/getuserinfo', method: 'GET' },
	{ id: 'livingGetLivingInfo', name: '[家校直播·兼容] 获取直播详情', action: '获取家校直播详情（兼容操作）', description: '兼容操作；新工作流请使用“[家校沟通] 获取直播详情”', path: '/cgi-bin/school/living/get_living_info', method: 'GET' },
	{ id: 'livingGetUnwatchStat', name: '[家校直播·旧版兼容] 获取未观看统计', action: '获取家校直播未观看统计（旧版兼容）', description: '旧版兼容操作；新工作流请优先使用未观看直播统计 V2', path: '/cgi-bin/school/living/get_unwatch_stat', method: 'POST' },
	{ id: 'livingGetWatchStat', name: '[家校直播·旧版兼容] 获取观看统计', action: '获取家校直播观看统计（旧版兼容）', description: '旧版兼容操作；新工作流请优先使用观看直播统计 V2', path: '/cgi-bin/school/living/get_watch_stat', method: 'POST' },
	{ id: 'setArchSyncMode', name: '[家校] 设置通讯录同步模式', action: '设置家校通讯录同步模式', description: '设置家校通讯录同步模式', path: '/cgi-bin/school/set_arch_sync_mode', method: 'POST' },
	{ id: 'setChatCreateMode', name: '[家校] 设置群创建模式', action: '设置家校群创建模式', description: '设置家校群创建模式', path: '/cgi-bin/school/set_chat_create_mode', method: 'POST' },
	{ id: 'setUpgradeInfo', name: '[家校] 设置升级信息', action: '设置家校升级信息', description: '设置家校自动升年级配置', path: '/cgi-bin/school/set_upgrade_info', method: 'POST' },
	{ id: 'userList', name: '[家校学生] 获取学生列表', action: '获取学生列表', description: '获取指定部门的学生详情', path: '/cgi-bin/school/user/list', method: 'GET' },
	{ id: 'userListParent', name: '[家校家长] 获取家长列表', action: '获取家长列表', description: '获取指定部门的家长详情', path: '/cgi-bin/school/user/list_parent', method: 'GET' },
];

export const schoolExtraHttpOpsById: Record<string, ExtraHttpOp> = Object.fromEntries(
	schoolExtraHttpOps.map((operation) => [operation.id, operation]),
);

export const schoolExtraHttpOpsOptionValues = schoolExtraHttpOps.map((operation) => operation.id);

export function getSchoolExtraHttpOpOptions() {
	return extraHttpOpOptions(schoolExtraHttpOps);
}

const show = (operations: string[]) => ({ resource: ['school'], operation: operations });

const departmentTypes = [
	{ name: '班级', value: 1 },
	{ name: '年级', value: 2 },
	{ name: '学段', value: 3 },
	{ name: '校区', value: 4 },
];

const adminTypes = [
	{ name: '校区负责人', value: 1 },
	{ name: '年级负责人', value: 2 },
	{ name: '班主任', value: 3 },
	{ name: '任课老师', value: 4 },
	{ name: '学段负责人', value: 5 },
];

const standardGrades = [
	{ name: '非标准年级', value: 0 },
	{ name: '幼儿园小小班', value: 1 },
	{ name: '幼儿园小班', value: 2 },
	{ name: '幼儿园中班', value: 3 },
	{ name: '幼儿园大班', value: 4 },
	{ name: '幼儿园学前班', value: 5 },
	{ name: '小学一年级', value: 31 },
	{ name: '小学二年级', value: 32 },
	{ name: '小学三年级', value: 33 },
	{ name: '小学四年级', value: 34 },
	{ name: '小学五年级', value: 35 },
	{ name: '小学六年级', value: 36 },
	{ name: '小学七年级', value: 37 },
	{ name: '小学八年级', value: 38 },
	{ name: '小学九年级', value: 39 },
	{ name: '初中一年级', value: 61 },
	{ name: '初中二年级', value: 62 },
	{ name: '初中三年级', value: 63 },
	{ name: '初中四年级', value: 64 },
	{ name: '高中一年级', value: 91 },
	{ name: '高中二年级', value: 92 },
	{ name: '高中三年级', value: 93 },
	{ name: '高中四年级', value: 94 },
	...Array.from({ length: 12 }, (_, index) => ({
		name: `自定义学段${['一', '二', '三', '四', '五', '六', '七', '八', '九', '十', '十一', '十二'][index]}年级`,
		value: 121 + index,
	})),
];

const createAdminValues: INodeProperties[] = [
	{
		displayName: '成员 UserID',
		name: 'userid',
		type: 'string',
		required: true,
		default: '',
		description: '管理端账号，1–64 个 UTF-8 字节',
	},
	{
		displayName: '管理员类型',
		name: 'type',
		type: 'options',
		required: true,
		options: adminTypes,
		default: 3,
		description: '类型必须与部门类型匹配',
	},
	{
		displayName: '科目',
		name: 'subject',
		type: 'string',
		default: '',
		displayOptions: { show: { type: [3, 4] } },
		description: '仅班主任或任课老师可设置，最多 15 个字符',
	},
];

const updateAdminValues: INodeProperties[] = [
	{
		displayName: '操作',
		name: 'op',
		type: 'options',
		required: true,
		options: [
			{ name: '新增或更新', value: 0 },
			{ name: '删除', value: 1 },
		],
		default: 0,
	},
	{
		displayName: '成员 UserID',
		name: 'userid',
		type: 'string',
		required: true,
		default: '',
		description: '管理端账号，1–64 个 UTF-8 字节',
	},
	{
		displayName: '管理员类型',
		name: 'type',
		type: 'options',
		required: true,
		options: adminTypes,
		default: 3,
		displayOptions: { show: { op: [0] } },
	},
	{
		displayName: '科目',
		name: 'subject',
		type: 'string',
		default: '',
		displayOptions: { show: { op: [0], type: [3, 4] } },
		description: '仅班主任或任课老师可设置，最多 15 个字符',
	},
];

export const schoolExtraHttpOpsDescription: INodeProperties[] = [
	{
		displayName: '部门名称',
		name: 'school_department_name',
		type: 'string',
		default: '',
		displayOptions: { show: show(['departmentCreate']) },
		description: '1–32 个字符，不能包含 - : * ? &quot; &lt; &gt; / 或中文逗号；创建标准年级时可留空',
	},
	{
		displayName: '父部门 ID',
		name: 'school_parentid',
		type: 'number',
		required: true,
		default: 1,
		typeOptions: { minValue: 1, maxValue: 4294967295, numberStepSize: 1 },
		displayOptions: { show: show(['departmentCreate']) },
		description: '班级的父部门必须是年级',
	},
	{
		displayName: '部门类型',
		name: 'school_department_type',
		type: 'options',
		required: true,
		options: departmentTypes,
		default: 1,
		displayOptions: { show: show(['departmentCreate']) },
	},
	{
		displayName: '指定部门 ID',
		name: 'specify_department_id',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['departmentCreate']) },
		description: '关闭时由企业微信自动生成部门 ID',
	},
	{
		displayName: '部门 ID',
		name: 'school_department_id',
		type: 'number',
		required: true,
		default: 2,
		typeOptions: { minValue: 2, maxValue: 4294967295, numberStepSize: 1 },
		displayOptions: {
			show: { ...show(['departmentCreate']), specify_department_id: [true] },
		},
		description: '指定时必须大于 1',
	},
	{
		displayName: '设置标准年级',
		name: 'include_standard_grade',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: { ...show(['departmentCreate']), school_department_type: [2] },
		},
	},
	{
		displayName: '标准年级',
		name: 'standard_grade',
		type: 'options',
		required: true,
		options: standardGrades,
		default: 31,
		displayOptions: {
			show: {
				...show(['departmentCreate']),
				school_department_type: [2],
				include_standard_grade: [true],
			},
		},
	},
	{
		displayName: '设置入学年份',
		name: 'include_register_year',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: { ...show(['departmentCreate']), school_department_type: [2] },
		},
	},
	{
		displayName: '入学年份',
		name: 'register_year',
		type: 'number',
		required: true,
		default: 2026,
		typeOptions: { minValue: 1970, maxValue: 2100, numberStepSize: 1 },
		displayOptions: {
			show: {
				...show(['departmentCreate']),
				school_department_type: [2],
				include_register_year: [true],
			},
		},
	},
	{
		displayName: '设置排序次序',
		name: 'include_department_order',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['departmentCreate']) },
	},
	{
		displayName: '排序次序',
		name: 'school_department_order',
		type: 'number',
		required: true,
		default: 0,
		typeOptions: { minValue: 0, maxValue: 4294967295, numberStepSize: 1 },
		displayOptions: {
			show: { ...show(['departmentCreate']), include_department_order: [true] },
		},
		description: '值越大越靠前',
	},
	{
		displayName: '部门管理员',
		name: 'departmentAdminsCollection',
		type: 'fixedCollection',
		default: {},
		placeholder: '添加管理员',
		typeOptions: { multipleValues: true },
		displayOptions: { show: show(['departmentCreate']) },
		description: '管理员类型必须与部门类型匹配；同一管理员配置不能重复',
		options: [{ displayName: '管理员', name: 'admins', values: createAdminValues }],
	},
	{
		displayName: '部门 ID',
		name: 'school_department_id',
		type: 'number',
		required: true,
		default: 1,
		typeOptions: { minValue: 1, maxValue: 4294967295, numberStepSize: 1 },
		displayOptions: { show: show(['departmentUpdate', 'departmentDelete']) },
	},
	{
		displayName: '不能删除根部门，也不能删除仍含子部门或成员的部门。删除成功后不可恢复。',
		name: 'departmentDeleteNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: show(['departmentDelete']) },
	},
	{
		displayName: '修改部门名称',
		name: 'update_department_name',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['departmentUpdate']) },
	},
	{
		displayName: '部门名称',
		name: 'school_department_name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: { ...show(['departmentUpdate']), update_department_name: [true] },
		},
		description: '1–32 个字符；标准年级会忽略此字段',
	},
	{
		displayName: '修改父部门',
		name: 'update_department_parent',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['departmentUpdate']) },
	},
	{
		displayName: '父部门 ID',
		name: 'school_parentid',
		type: 'number',
		required: true,
		default: 1,
		typeOptions: { minValue: 1, maxValue: 4294967295, numberStepSize: 1 },
		displayOptions: {
			show: { ...show(['departmentUpdate']), update_department_parent: [true] },
		},
	},
	{
		displayName: '修改部门 ID',
		name: 'update_department_id',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['departmentUpdate']) },
	},
	{
		displayName: '新部门 ID',
		name: 'school_new_id',
		type: 'number',
		required: true,
		default: 1,
		typeOptions: { minValue: 1, maxValue: 4294967295, numberStepSize: 1 },
		displayOptions: {
			show: { ...show(['departmentUpdate']), update_department_id: [true] },
		},
	},
	{
		displayName: '修改入学年份',
		name: 'update_register_year',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['departmentUpdate']) },
	},
	{
		displayName: '入学年份',
		name: 'register_year',
		type: 'number',
		required: true,
		default: 2026,
		typeOptions: { minValue: 1970, maxValue: 2100, numberStepSize: 1 },
		displayOptions: {
			show: { ...show(['departmentUpdate']), update_register_year: [true] },
		},
	},
	{
		displayName: '修改标准年级',
		name: 'update_standard_grade',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['departmentUpdate']) },
		description: '可以选择“非标准年级”将标准年级转为非标准年级',
	},
	{
		displayName: '标准年级',
		name: 'standard_grade',
		type: 'options',
		required: true,
		options: standardGrades,
		default: 0,
		displayOptions: {
			show: { ...show(['departmentUpdate']), update_standard_grade: [true] },
		},
	},
	{
		displayName: '修改排序次序',
		name: 'update_department_order',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['departmentUpdate']) },
	},
	{
		displayName: '排序次序',
		name: 'school_department_order',
		type: 'number',
		required: true,
		default: 0,
		typeOptions: { minValue: 0, maxValue: 4294967295, numberStepSize: 1 },
		displayOptions: {
			show: { ...show(['departmentUpdate']), update_department_order: [true] },
		},
	},
	{
		displayName: '更新部门管理员',
		name: 'update_department_admins',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['departmentUpdate']) },
	},
	{
		displayName: '部门管理员变更',
		name: 'departmentAdminsCollection',
		type: 'fixedCollection',
		required: true,
		default: {},
		placeholder: '添加管理员变更',
		typeOptions: { multipleValues: true },
		displayOptions: {
			show: { ...show(['departmentUpdate']), update_department_admins: [true] },
		},
		options: [{ displayName: '管理员变更', name: 'admins', values: updateAdminValues }],
	},
	{
		displayName: '筛选指定部门',
		name: 'filter_department',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['departmentList']) },
		description: '关闭时获取全量组织架构；开启时获取指定部门及其子部门',
	},
	{
		displayName: '部门 ID',
		name: 'school_department_id',
		type: 'number',
		required: true,
		default: 1,
		typeOptions: { minValue: 1, maxValue: 4294967295, numberStepSize: 1 },
		displayOptions: {
			show: { ...show(['departmentList']), filter_department: [true] },
		},
	},
	{
		displayName: 'OAuth Code',
		name: 'school_code',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: show(['getuserinfo']) },
		description: '网页授权回调 Code，最多 512 个 UTF-8 字节，只能使用一次且 5 分钟后过期',
	},
	{
		displayName: '每次授权返回的 Code 均不同，只能使用一次，并会在 5 分钟后自动过期。',
		name: 'schoolCodeNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: show(['getuserinfo']) },
	},
	{
		displayName: '这是为旧工作流保留的兼容操作。新工作流请使用上方“家校沟通”分组中的直播详情或 V2 统计操作。',
		name: 'schoolLivingCompatibilityNotice',
		type: 'notice',
		default: '',
		displayOptions: {
			show: show(['livingGetLivingInfo', 'livingGetUnwatchStat', 'livingGetWatchStat']),
		},
	},
	{
		displayName: '直播 ID',
		name: 'school_livingid',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: show(['livingGetLivingInfo', 'livingGetUnwatchStat', 'livingGetWatchStat']),
		},
	},
	{
		displayName: '分页 Next Key',
		name: 'school_next_key',
		type: 'string',
		default: '',
		displayOptions: { show: show(['livingGetUnwatchStat', 'livingGetWatchStat']) },
		description: '首次请求留空；后续填写上次返回的 next_key',
	},
	{
		displayName: '通讯录同步模式',
		name: 'arch_sync_mode',
		type: 'options',
		required: true,
		options: [
			{ name: '禁止标签同步至家校通讯录', value: 1 },
			{ name: '禁止家校通讯录同步至标签', value: 2 },
			{ name: '禁止双向同步', value: 3 },
		],
		default: 1,
		displayOptions: { show: show(['setArchSyncMode']) },
	},
	{
		displayName: '该设置会改变企业标签与家校通讯录之间的同步方向，请确认现有同步策略后执行。',
		name: 'archSyncNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: show(['setArchSyncMode']) },
	},
	{
		displayName: '班级群创建方式',
		name: 'create_mode',
		type: 'options',
		required: true,
		options: [
			{ name: '自动创建', value: 0 },
			{ name: '手动创建', value: 1 },
		],
		default: 0,
		displayOptions: { show: show(['setChatCreateMode']) },
	},
	{
		displayName: '设置自动升年级日期',
		name: 'set_upgrade_time',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['setUpgradeInfo']) },
		description: '企业微信只使用所选时间中的月和日',
	},
	{
		displayName: '自动升年级日期',
		name: 'upgrade_time',
		type: 'dateTime',
		required: true,
		default: '',
		displayOptions: {
			show: { ...show(['setUpgradeInfo']), set_upgrade_time: [true] },
		},
		description: '将转换为 Unix 秒；接口仅使用月和日',
	},
	{
		displayName: '设置自动升年级开关',
		name: 'set_upgrade_switch',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['setUpgradeInfo']) },
	},
	{
		displayName: '自动升年级开关',
		name: 'upgrade_switch',
		type: 'options',
		required: true,
		options: [
			{ name: '关闭', value: 0 },
			{ name: '开启', value: 1 },
		],
		default: 0,
		displayOptions: {
			show: { ...show(['setUpgradeInfo']), set_upgrade_switch: [true] },
		},
	},
	{
		displayName: '部门 ID',
		name: 'school_department_id',
		type: 'number',
		required: true,
		default: 1,
		typeOptions: { minValue: 1, maxValue: 4294967295, numberStepSize: 1 },
		displayOptions: { show: show(['userList', 'userListParent']) },
		description: '要读取学生或家长详情的部门 ID',
	},
];
