import type { INodeProperties } from 'n8n-workflow';

const show = (operations: string[]) => ({ resource: ['school'], operation: operations });

const childValues: INodeProperties[] = [
	{
		displayName: '学生 UserID',
		name: 'student_userid',
		type: 'string',
		required: true,
		default: '',
		description: '学生的 UserID，长度不超过 64 个 UTF-8 字节',
	},
	{
		displayName: '与学生的关系',
		name: 'relation',
		type: 'string',
		required: true,
		default: '',
		placeholder: '爸爸',
		description: '家长与学生的关系，最长 32 个 UTF-8 字节',
	},
];

const nestedChildrenField: INodeProperties = {
	displayName: '孩子列表',
	name: 'children',
	type: 'fixedCollection',
	required: true,
	default: {},
	placeholder: '添加孩子',
	typeOptions: { multipleValues: true },
	description: '至少 1 个、最多 10 个孩子；同一学生不能重复',
	options: [{ displayName: '孩子', name: 'children', values: childValues }],
};

const studentCreateValues: INodeProperties[] = [
	{
		displayName: '学生 UserID',
		name: 'student_userid',
		type: 'string',
		required: true,
		default: '',
		description: '1–64 个 UTF-8 字节，学校内唯一；必须以数字或字母开头',
	},
	{
		displayName: '学生姓名',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		description: '1–32 个字符',
	},
	{
		displayName: '班级 ID 列表',
		name: 'department',
		type: 'string',
		required: true,
		default: '',
		placeholder: '1,2',
		description: '最多 20 个正整数；与下方 JSON 合并；支持逗号、中文逗号、竖线或换行分隔',
	},
	{
		displayName: '班级 ID 列表 JSON',
		name: 'departmentJson',
		type: 'json',
		default: '[]',
		description:
			'可选。非空数组时与上方列表合并去重。支持 [1,2] 或 [{"departmentid":1}]',
	},
	{
		displayName: '学生手机号',
		name: 'mobile',
		type: 'string',
		default: '',
	},
	{
		displayName: '发起邀请',
		name: 'to_invite',
		type: 'boolean',
		default: true,
		description: '仅已验证的学校可以发起邀请',
	},
];

const studentUpdateValues: INodeProperties[] = [
	{
		displayName: '学生 UserID',
		name: 'student_userid',
		type: 'string',
		required: true,
		default: '',
		description: '当前学生 UserID',
	},
	{
		displayName: '修改学生 UserID',
		name: 'update_new_student_userid',
		type: 'boolean',
		default: false,
	},
	{
		displayName: '新学生 UserID',
		name: 'new_student_userid',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { update_new_student_userid: [true] } },
		description: '不能与现有 UserID 重复；每个学生仅能修改一次',
	},
	{
		displayName: '修改学生姓名',
		name: 'update_name',
		type: 'boolean',
		default: false,
	},
	{
		displayName: '学生姓名',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { update_name: [true] } },
		description: '1–32 个字符',
	},
	{
		displayName: '修改班级',
		name: 'update_department',
		type: 'boolean',
		default: false,
	},
	{
		displayName: '班级 ID 列表',
		name: 'department',
		type: 'string',
		required: true,
		default: '',
		placeholder: '1,2',
		displayOptions: { show: { update_department: [true] } },
		description: '全量更新学生所在班级，最多 20 个；与下方 JSON 合并',
	},
	{
		displayName: '班级 ID 列表 JSON',
		name: 'departmentJson',
		type: 'json',
		default: '[]',
		displayOptions: { show: { update_department: [true] } },
		description:
			'可选。非空数组时与上方列表合并去重。支持 [1,2] 或 [{"departmentid":1}]',
	},
	{
		displayName: '修改手机号',
		name: 'update_mobile',
		type: 'boolean',
		default: false,
	},
	{
		displayName: '学生手机号',
		name: 'mobile',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { update_mobile: [true] } },
	},
];

const parentCreateValues: INodeProperties[] = [
	{
		displayName: '家长 UserID',
		name: 'parent_userid',
		type: 'string',
		required: true,
		default: '',
		description: '1–64 个 UTF-8 字节，学校内唯一；必须以数字或字母开头',
	},
	{
		displayName: '家长手机号',
		name: 'mobile',
		type: 'string',
		required: true,
		default: '',
	},
	nestedChildrenField,
	{
		displayName: '发起邀请',
		name: 'to_invite',
		type: 'boolean',
		default: true,
		description: '仅已验证的学校可以发起邀请',
	},
];

const parentUpdateValues: INodeProperties[] = [
	{
		displayName: '家长 UserID',
		name: 'parent_userid',
		type: 'string',
		required: true,
		default: '',
		description: '当前家长 UserID',
	},
	{
		displayName: '修改家长 UserID',
		name: 'update_new_parent_userid',
		type: 'boolean',
		default: false,
	},
	{
		displayName: '新家长 UserID',
		name: 'new_parent_userid',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { update_new_parent_userid: [true] } },
		description: '不能与现有 UserID 重复；每个家长仅能修改一次',
	},
	{
		displayName: '修改手机号',
		name: 'update_mobile',
		type: 'boolean',
		default: false,
	},
	{
		displayName: '家长手机号',
		name: 'mobile',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { update_mobile: [true] } },
	},
	{
		displayName: '更新孩子列表',
		name: 'update_children',
		type: 'boolean',
		default: false,
		description: '启用后全量替换孩子列表；空列表会被企业微信忽略',
	},
	{
		...nestedChildrenField,
		displayOptions: { show: { update_children: [true] } },
	},
];

export const schoolContactOpsDescription: INodeProperties[] = [
	{
		displayName: '学生 UserID',
		name: 'userid',
		type: 'string',
		default: '',
		displayOptions: { show: show(['deleteStudent']) },
		description: '要删除的学生 UserID，长度不超过 64 个 UTF-8 字节；可与下方选择二选一',
	},
	{
		displayName: '学生(选择)',
		name: 'userid_selected',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: '',
		displayOptions: { show: show(['deleteStudent']) },
		description: '与上方字符串二选一；家校 UserID 若已在企业通讯录可见可从此选择',
	},
	{
		displayName: '删除会移除学生及其家校通讯录关系。请确认 UserID 列表无误后再执行。',
		name: 'deleteStudentNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: show(['deleteStudent', 'batchDeleteStudent']) },
	},
	{
		displayName: '学生 UserID',
		name: 'student_userid',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: show(['updateStudent']) },
		description: '当前学生 UserID，1–64 个 UTF-8 字节',
	},
	{
		displayName: '修改学生 UserID',
		name: 'update_new_student_userid',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['updateStudent']) },
	},
	{
		displayName: '新学生 UserID',
		name: 'new_student_userid',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: { ...show(['updateStudent']), update_new_student_userid: [true] },
		},
		description: '不能与现有 UserID 重复；每个学生仅能修改一次',
	},
	{
		displayName: '每个学生仅能修改一次 UserID；更新成功后请同步所有依赖旧 UserID 的工作流。',
		name: 'studentUseridUpdateNotice',
		type: 'notice',
		default: '',
		displayOptions: {
			show: { ...show(['updateStudent']), update_new_student_userid: [true] },
		},
	},
	{
		displayName: '修改学生姓名',
		name: 'update_name',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['updateStudent']) },
	},
	{
		displayName: '学生姓名',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { ...show(['updateStudent']), update_name: [true] } },
		description: '1–32 个字符',
	},
	{
		displayName: '修改班级',
		name: 'update_department',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['updateStudent']) },
	},
	{
		displayName: '班级 ID 列表',
		name: 'department',
		type: 'string',
		required: true,
		default: '',
		placeholder: '1,2',
		displayOptions: {
			show: { ...show(['updateStudent']), update_department: [true] },
		},
		description:
			'全量更新学生所在班级，最多 20 个；与下方 JSON 合并；支持逗号、中文逗号、竖线或换行分隔',
	},
	{
		displayName: '班级 ID 列表 JSON',
		name: 'departmentJson',
		type: 'json',
		default: '[]',
		displayOptions: {
			show: { ...show(['updateStudent']), update_department: [true] },
		},
		description:
			'可选。非空数组时与上方列表合并去重。支持 [1,2] 或 [{"departmentid":1}]',
	},
	{
		displayName: '修改手机号',
		name: 'update_mobile',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['updateStudent']) },
	},
	{
		displayName: '学生手机号',
		name: 'mobile',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { ...show(['updateStudent']), update_mobile: [true] } },
	},
	{
		displayName: '学生列表输入方式',
		name: 'studentInputMode',
		type: 'options',
		options: [
			{ name: '逐项填写', value: 'form' },
			{ name: 'JSON 数组', value: 'json' },
		],
		default: 'form',
		displayOptions: { show: show(['batchCreateStudent', 'batchUpdateStudent']) },
		description: '每次最多 100 个学生；复杂或大批量数据可直接提供官方 students 数组',
	},
	{
		displayName: '学生列表',
		name: 'studentsCollection',
		type: 'fixedCollection',
		required: true,
		default: {},
		placeholder: '添加学生',
		typeOptions: { multipleValues: true },
		displayOptions: {
			show: { ...show(['batchCreateStudent']), studentInputMode: ['form'] },
		},
		description: '至少 1 个、最多 100 个学生',
		options: [{ displayName: '学生', name: 'students', values: studentCreateValues }],
	},
	{
		displayName: '学生列表',
		name: 'studentsCollection',
		type: 'fixedCollection',
		required: true,
		default: {},
		placeholder: '添加学生',
		typeOptions: { multipleValues: true },
		displayOptions: {
			show: { ...show(['batchUpdateStudent']), studentInputMode: ['form'] },
		},
		description: '至少 1 个、最多 100 个学生；每项至少选择一个更新字段',
		options: [{ displayName: '学生', name: 'students', values: studentUpdateValues }],
	},
	{
		displayName: '学生列表 JSON',
		name: 'studentsJson',
		type: 'json',
		required: true,
		default: '[]',
		displayOptions: {
			show: {
				...show(['batchCreateStudent', 'batchUpdateStudent']),
				studentInputMode: ['json'],
			},
		},
		description: '填写官方 students 数组；节点仍会逐项校验必填字段、长度、数量与重复 UserID',
	},
	{
		displayName: 'UserID 列表',
		name: 'userid_list',
		type: 'string',
		default: '',
		placeholder: 'id1,id2',
		typeOptions: { rows: 3 },
		displayOptions: { show: show(['batchDeleteStudent', 'batchDeleteParent']) },
		description: '与下方选择合并，最多 100 个；支持逗号、中文逗号、竖线或换行分隔，重复值会自动去除',
	},
	{
		displayName: 'UserID(选择)',
		name: 'userid_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: show(['batchDeleteStudent', 'batchDeleteParent']) },
		default: [],
		description: '与上方列表合并去重；学生/家长 UserID 若已录入通讯录可从此选择',
	},
	{
		displayName: 'UserID 列表 JSON',
		name: 'useridListJson',
		type: 'json',
		default: '[]',
		displayOptions: { show: show(['batchDeleteStudent', 'batchDeleteParent']) },
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '家长 UserID',
		name: 'parent_userid',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: show(['createParent', 'updateParent']) },
		description: '1–64 个 UTF-8 字节；必须以数字或字母开头',
	},
	{
		displayName: '家长手机号',
		name: 'mobile',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: show(['createParent']) },
	},
	{
		displayName: '孩子列表',
		name: 'childrenCollection',
		type: 'fixedCollection',
		required: true,
		default: {},
		placeholder: '添加孩子',
		typeOptions: { multipleValues: true },
		displayOptions: { show: show(['createParent']) },
		description: '至少 1 个、最多 10 个孩子',
		options: [{ displayName: '孩子', name: 'children', values: childValues }],
	},
	{
		displayName: '发起邀请',
		name: 'to_invite',
		type: 'boolean',
		default: true,
		displayOptions: { show: show(['createParent']) },
		description: '仅已验证的学校可以发起邀请',
	},
	{
		displayName: '家长 UserID',
		name: 'userid',
		type: 'string',
		default: '',
		displayOptions: { show: show(['deleteParent']) },
		description: '要删除的家长 UserID，长度不超过 64 个 UTF-8 字节；可与下方选择二选一',
	},
	{
		displayName: '家长(选择)',
		name: 'userid_selected',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		default: '',
		displayOptions: { show: show(['deleteParent']) },
		description: '与上方字符串二选一；家校 UserID 若已在企业通讯录可见可从此选择',
	},
	{
		displayName: '删除会移除家长及其家校通讯录关系。请确认 UserID 列表无误后再执行。',
		name: 'deleteParentNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: show(['deleteParent', 'batchDeleteParent']) },
	},
	{
		displayName: '修改家长 UserID',
		name: 'update_new_parent_userid',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['updateParent']) },
	},
	{
		displayName: '新家长 UserID',
		name: 'new_parent_userid',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: { ...show(['updateParent']), update_new_parent_userid: [true] },
		},
		description: '不能与现有 UserID 重复；每个家长仅能修改一次',
	},
	{
		displayName: '每个家长仅能修改一次 UserID；更新成功后请同步所有依赖旧 UserID 的工作流。',
		name: 'parentUseridUpdateNotice',
		type: 'notice',
		default: '',
		displayOptions: {
			show: { ...show(['updateParent']), update_new_parent_userid: [true] },
		},
	},
	{
		displayName: '修改手机号',
		name: 'update_mobile',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['updateParent']) },
	},
	{
		displayName: '家长手机号',
		name: 'mobile',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { ...show(['updateParent']), update_mobile: [true] } },
	},
	{
		displayName: '更新孩子列表',
		name: 'update_children',
		type: 'boolean',
		default: false,
		displayOptions: { show: show(['updateParent']) },
		description: '启用后全量替换孩子列表；空列表会被企业微信忽略',
	},
	{
		displayName: '该字段是全量更新：未列出的原有孩子关系将被移除。列表必须包含 1–10 个孩子。',
		name: 'childrenUpdateNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { ...show(['updateParent']), update_children: [true] } },
	},
	{
		displayName: '孩子列表',
		name: 'childrenCollection',
		type: 'fixedCollection',
		required: true,
		default: {},
		placeholder: '添加孩子',
		typeOptions: { multipleValues: true },
		displayOptions: { show: { ...show(['updateParent']), update_children: [true] } },
		description: '全量孩子列表，至少 1 个、最多 10 个',
		options: [{ displayName: '孩子', name: 'children', values: childValues }],
	},
	{
		displayName: '家长列表输入方式',
		name: 'parentInputMode',
		type: 'options',
		options: [
			{ name: '逐项填写', value: 'form' },
			{ name: 'JSON 数组', value: 'json' },
		],
		default: 'form',
		displayOptions: { show: show(['batchCreateParent', 'batchUpdateParent']) },
		description: '每次最多 100 个家长；复杂或大批量数据可直接提供官方 parents 数组',
	},
	{
		displayName: '家长列表',
		name: 'parentsCollection',
		type: 'fixedCollection',
		required: true,
		default: {},
		placeholder: '添加家长',
		typeOptions: { multipleValues: true },
		displayOptions: {
			show: { ...show(['batchCreateParent']), parentInputMode: ['form'] },
		},
		description: '至少 1 个、最多 100 个家长',
		options: [{ displayName: '家长', name: 'parents', values: parentCreateValues }],
	},
	{
		displayName: '家长列表',
		name: 'parentsCollection',
		type: 'fixedCollection',
		required: true,
		default: {},
		placeholder: '添加家长',
		typeOptions: { multipleValues: true },
		displayOptions: {
			show: { ...show(['batchUpdateParent']), parentInputMode: ['form'] },
		},
		description: '至少 1 个、最多 100 个家长；每项至少选择一个更新字段',
		options: [{ displayName: '家长', name: 'parents', values: parentUpdateValues }],
	},
	{
		displayName: '家长列表 JSON',
		name: 'parentsJson',
		type: 'json',
		required: true,
		default: '[]',
		displayOptions: {
			show: {
				...show(['batchCreateParent', 'batchUpdateParent']),
				parentInputMode: ['json'],
			},
		},
		description: '填写官方 parents 数组；节点仍会逐项校验必填字段、孩子数量、长度与重复 UserID',
	},
];
