import type { INodeProperties } from 'n8n-workflow';

const showOnlyForSubmitApproval = {
	resource: ['approval'],
	operation: ['submitApproval'],
};

export const submitApprovalDescription: INodeProperties[] = [
	{
		displayName: '申请人UserID',
		name: 'creator_userid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnlyForSubmitApproval },
		default: '',
		description: 'creator_userid，申请人需在应用可见范围内',
	},
	{
		displayName: '审批模板ID',
		name: 'template_id',
		type: 'string',
		required: true,
		displayOptions: { show: showOnlyForSubmitApproval },
		default: '',
		description: 'template_id',
	},
	{
		displayName: '审批人模式',
		name: 'use_template_approver',
		type: 'options',
		required: true,
		displayOptions: { show: showOnlyForSubmitApproval },
		options: [
			{ name: '接口指定审批人/抄送人 (process 必填)', value: 0 },
			{ name: '使用模板后台审批流程', value: 1 },
		],
		default: 1,
		description: 'use_template_approver',
	},
	{
		displayName: '提单部门ID',
		name: 'choose_department',
		type: 'number',
		displayOptions: { show: showOnlyForSubmitApproval },
		default: 0,
		description: 'choose_department，不填默认为主部门',
	},
	{
		displayName: '申请表单控件值',
		name: 'applyContentsCollection',
		type: 'fixedCollection',
		displayOptions: { show: showOnlyForSubmitApproval },
		default: {},
		placeholder: '添加控件值',
		typeOptions: { multipleValues: true },
		description:
			'简易控件表单：Text/Number/Money/Date/Selector/Contact/File；更复杂结构用下方 JSON',
		options: [
			{
				displayName: '控件',
				name: 'contents',
				values: [
					{
						displayName: '控件类型',
						name: 'control',
						type: 'options',
						options: [
							{ name: '文本 Text', value: 'Text' },
							{ name: '多行文本 Textarea', value: 'Textarea' },
							{ name: '数字 Number', value: 'Number' },
							{ name: '金额 Money', value: 'Money' },
							{ name: '日期 Date', value: 'Date' },
							{ name: '时长 DateRange', value: 'DateRange' },
							{ name: '选择 Selector', value: 'Selector' },
							{ name: '成员/部门 Contact', value: 'Contact' },
							{ name: '附件 File', value: 'File' },
							{ name: '电话 PhoneNumber', value: 'PhoneNumber' },
							{ name: '说明 Tips', value: 'Tips' },
						],
						default: 'Text',
					},
					{
						displayName: '控件ID',
						name: 'id',
						type: 'string',
						required: true,
						default: '',
						placeholder: 'Text-1',
						description: '与模板详情中的 id 一致',
					},
					{
						displayName: '文本/数值',
						name: 'text',
						type: 'string',
						default: '',
						displayOptions: {
							show: { control: ['Text', 'Textarea', 'Number', 'PhoneNumber'] },
						},
						description: 'Text/Textarea 用 text；Number 写数字字符串',
					},
					{
						displayName: '新金钱额',
						name: 'new_money',
						type: 'string',
						default: '',
						displayOptions: { show: { control: ['Money'] } },
						description: 'Money 控件 new_money（字符串，单位与模板一致）',
					},
					{
						displayName: '日期类型',
						name: 'date_type',
						type: 'options',
						options: [
							{ name: '日期 day', value: 'day' },
							{ name: '日期+时间 hour', value: 'hour' },
						],
						default: 'day',
						displayOptions: { show: { control: ['Date'] } },
						description: 'Date 控件 type',
					},
					{
						displayName: '日期时间',
						name: 'date_s',
						type: 'dateTime',
						default: '',
						required: true,
						displayOptions: { show: { control: ['Date'] } },
						description: 'Date 控件 s_timestamp（Unix 秒）',
					},
					{
						displayName: '时长类型',
						name: 'date_range_type',
						type: 'options',
						options: [
							{ name: '半天 halfday', value: 'halfday' },
							{ name: '小时 hour', value: 'hour' },
						],
						default: 'halfday',
						displayOptions: { show: { control: ['DateRange'] } },
						description: 'DateRange.type',
					},
					{
						displayName: '时长开始',
						name: 'date_range_begin',
						type: 'dateTime',
						default: '',
						required: true,
						displayOptions: { show: { control: ['DateRange'] } },
						description: 'DateRange.new_begin',
					},
					{
						displayName: '时长结束',
						name: 'date_range_end',
						type: 'dateTime',
						default: '',
						required: true,
						displayOptions: { show: { control: ['DateRange'] } },
						description: 'DateRange.new_end',
					},
					{
						displayName: '时长秒数',
						name: 'date_range_duration',
						type: 'number',
						required: true,
						displayOptions: { show: { control: ['DateRange'] } },
						default: 86400,
						typeOptions: { minValue: 1 },
						description: 'DateRange.new_duration；按模板的时长计算规则填写',
					},
					{
						displayName: '选择方式',
						name: 'selector_type',
						type: 'options',
						options: [
							{ name: '单选 single', value: 'single' },
							{ name: '多选 multi', value: 'multi' },
						],
						default: 'single',
						displayOptions: { show: { control: ['Selector'] } },
						description: 'Selector.type',
					},
					{
						displayName: '选项Key列表',
						name: 'selector_keys',
						type: 'string',
						default: '',
						required: true,
						displayOptions: { show: { control: ['Selector'] } },
						placeholder: 'option-1,option-2',
						description: 'Selector.options[].key，逗号分隔；key 来自模板详情',
					},
					{
						displayName: '联系人类型',
						name: 'contact_kind',
						type: 'options',
						options: [
							{ name: '成员 members', value: 'members' },
							{ name: '部门 departments', value: 'departments' },
						],
						default: 'members',
						displayOptions: { show: { control: ['Contact'] } },
						description: 'Contact 控件写 members 或 departments',
					},
					{
						displayName: '成员UserID列表',
						name: 'contact_userids',
						type: 'string',
						default: '',
						required: true,
						displayOptions: {
							show: { control: ['Contact'], contact_kind: ['members'] },
						},
						placeholder: 'zhangsan,lisi',
						description: 'Contact members.userid，逗号分隔',
					},
					{
						displayName: '部门ID列表',
						name: 'contact_partyids',
						type: 'string',
						default: '',
						required: true,
						displayOptions: {
							show: { control: ['Contact'], contact_kind: ['departments'] },
						},
						placeholder: '1,2',
						description: 'Contact departments.openapi_id，逗号分隔',
					},
					{
						displayName: '附件MediaID列表',
						name: 'file_mediaids',
						type: 'string',
						default: '',
						required: true,
						displayOptions: { show: { control: ['File'] } },
						placeholder: 'MEDIA_ID1,MEDIA_ID2',
						description: 'File 控件 files[].file_id，逗号分隔',
					},
				],
			},
		],
	},
	{
		displayName: '申请表单数据JSON',
		name: 'apply_data_json',
		type: 'json',
		displayOptions: { show: showOnlyForSubmitApproval },
		default: '{}',
		description: '完整 apply_data。非空对象时优先；空对象则使用上方控件值表单',
	},
	{
		displayName: '摘要行',
		name: 'summaryLines',
		type: 'fixedCollection',
		required: true,
		displayOptions: { show: showOnlyForSubmitApproval },
		default: {},
		placeholder: '添加摘要行',
		typeOptions: { multipleValues: true },
		description: 'summary_list，最多 3 行，每行不超过 20 字',
		options: [
			{
				displayName: '摘要',
				name: 'lines',
				values: [
					{
						displayName: '摘要文字',
						name: 'text',
						type: 'string',
						required: true,
						default: '',
					},
					{
						displayName: '语言',
						name: 'lang',
						type: 'options',
						options: [
							{ name: '中文 zh_CN', value: 'zh_CN' },
							{ name: '英文 en', value: 'en' },
						],
						default: 'zh_CN',
					},
				],
			},
		],
	},
	{
		displayName: '审批流程节点',
		name: 'processNodeCollection',
		type: 'fixedCollection',
		required: true,
		displayOptions: {
			show: { ...showOnlyForSubmitApproval, use_template_approver: [0] },
		},
		default: {},
		placeholder: '添加节点',
		typeOptions: { multipleValues: true },
		description: 'process.node_list；use_template_approver=0 时必填',
		options: [
			{
				displayName: '节点',
				name: 'nodes',
				values: [
					{
						displayName: '节点类型',
						name: 'type',
						type: 'options',
						options: [
							{ name: '审批人', value: 1 },
							{ name: '抄送人', value: 2 },
							{ name: '办理人', value: 3 },
						],
						default: 1,
					},
					{
						displayName: '多人审批方式',
						name: 'apv_rel',
						type: 'options',
						options: [
							{ name: '会签', value: 1 },
							{ name: '或签', value: 2 },
							{ name: '依次审批', value: 3 },
						],
						default: 1,
						description: 'type 为审批人/办理人时有效',
					},
					{
						displayName: '成员UserID列表',
						name: 'userid_list',
						type: 'string',
						required: true,
						default: '',
						placeholder: 'user1,user2',
						description: '逗号分隔',
					},
				],
			},
		],
	},
	{
		displayName: '扩展请求JSON',
		name: 'approvalExtraJson',
		type: 'json',
		displayOptions: { show: showOnlyForSubmitApproval },
		default: '{}',
		description: '其余字段与上方合并，同名字段以 JSON 为准',
	},
];
