import type { INodeProperties } from 'n8n-workflow';

const showOnlyForSubmitApproval = {
	resource: ['approval'],
	operation: ['submitApproval'],
};

export const submitApprovalDescription: INodeProperties[] = [
	{
		displayName: '申请人UserID',
		name: 'creator_userid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnlyForSubmitApproval },
		default: '',
		description: 'creator_userid，申请人需在应用可见范围内',
	},
	{
		displayName: '审批模板ID',
		name: 'template_id',
		type: 'string',
		required: true,
		displayOptions: { show: showOnlyForSubmitApproval },
		default: '',
		description: 'template_id',
	},
	{
		displayName: '审批人模式',
		name: 'use_template_approver',
		type: 'options',
		required: true,
		displayOptions: { show: showOnlyForSubmitApproval },
		options: [
			{ name: '接口指定审批人/抄送人 (process 必填)', value: 0 },
			{ name: '使用模板后台审批流程', value: 1 },
		],
		default: 1,
		description: 'use_template_approver',
	},
	{
		displayName: '提单部门ID',
		name: 'choose_department',
		type: 'number',
		displayOptions: { show: showOnlyForSubmitApproval },
		default: 0,
		description: 'choose_department，不填默认为主部门',
	},
	{
		displayName: '申请表单控件值',
		name: 'applyContentsCollection',
		type: 'fixedCollection',
		displayOptions: { show: showOnlyForSubmitApproval },
		default: {},
		placeholder: '添加控件值',
		typeOptions: { multipleValues: true },
		description:
			'简易控件表单：Text/Number/Money/Date/DateRange/Selector/Contact/File/RelatedApproval/Location/Vacation/Attendance/Table/Formula；更复杂结构用下方 JSON',
		options: [
			{
				displayName: '控件',
				name: 'contents',
				values: [
					{
						displayName: '控件类型',
						name: 'control',
						type: 'options',
						options: [
							{ name: '文本 Text', value: 'Text' },
							{ name: '多行文本 Textarea', value: 'Textarea' },
							{ name: '数字 Number', value: 'Number' },
							{ name: '金额 Money', value: 'Money' },
							{ name: '日期 Date', value: 'Date' },
							{ name: '时长 DateRange', value: 'DateRange' },
							{ name: '选择 Selector', value: 'Selector' },
							{ name: '成员/部门 Contact', value: 'Contact' },
							{ name: '附件 File', value: 'File' },
							{ name: '电话 PhoneNumber', value: 'PhoneNumber' },
							{ name: '说明 Tips', value: 'Tips' },
							{ name: '关联审批 RelatedApproval', value: 'RelatedApproval' },
							{ name: '位置 Location', value: 'Location' },
							{ name: '请假 Vacation', value: 'Vacation' },
							{ name: '出差/外出/加班 Attendance', value: 'Attendance' },
							{ name: '明细 Table', value: 'Table' },
							{ name: '公式 Formula', value: 'Formula' },
						],
						default: 'Text',
					},
					{
						displayName: '控件ID',
						name: 'id',
						type: 'string',
						required: true,
						default: '',
						placeholder: 'Text-1',
						description: '与模板详情中的 id 一致',
					},
					{
						displayName: '文本/数值',
						name: 'text',
						type: 'string',
						default: '',
						displayOptions: {
							show: { control: ['Text', 'Textarea', 'Number', 'PhoneNumber'] },
						},
						description: 'Text/Textarea 用 text；Number 写数字字符串',
					},
					{
						displayName: '新金钱额',
						name: 'new_money',
						type: 'string',
						default: '',
						displayOptions: { show: { control: ['Money'] } },
						description: 'Money 控件 new_money（字符串，单位与模板一致）',
					},
					{
						displayName: '日期类型',
						name: 'date_type',
						type: 'options',
						options: [
							{ name: '日期 day', value: 'day' },
							{ name: '日期+时间 hour', value: 'hour' },
						],
						default: 'day',
						displayOptions: { show: { control: ['Date'] } },
						description: 'Date 控件 type',
					},
					{
						displayName: '日期时间',
						name: 'date_s',
						type: 'dateTime',
						default: '',
						required: true,
						displayOptions: { show: { control: ['Date'] } },
						description: 'Date 控件 s_timestamp（Unix 秒）',
					},
					{
						displayName: '时长类型',
						name: 'date_range_type',
						type: 'options',
						options: [
							{ name: '半天 halfday', value: 'halfday' },
							{ name: '小时 hour', value: 'hour' },
						],
						default: 'halfday',
						displayOptions: { show: { control: ['DateRange'] } },
						description: 'DateRange.type',
					},
					{
						displayName: '时长开始',
						name: 'date_range_begin',
						type: 'dateTime',
						default: '',
						required: true,
						displayOptions: { show: { control: ['DateRange'] } },
						description: 'DateRange.new_begin',
					},
					{
						displayName: '时长结束',
						name: 'date_range_end',
						type: 'dateTime',
						default: '',
						required: true,
						displayOptions: { show: { control: ['DateRange'] } },
						description: 'DateRange.new_end',
					},
					{
						displayName: '时长秒数',
						name: 'date_range_duration',
						type: 'number',
						required: true,
						displayOptions: { show: { control: ['DateRange'] } },
						default: 86400,
						typeOptions: { minValue: 1 },
						description: 'DateRange.new_duration；按模板的时长计算规则填写',
					},
					{
						displayName: '选择方式',
						name: 'selector_type',
						type: 'options',
						options: [
							{ name: '单选 single', value: 'single' },
							{ name: '多选 multi', value: 'multi' },
						],
						default: 'single',
						displayOptions: { show: { control: ['Selector'] } },
						description: 'Selector.type',
					},
					{
						displayName: '选项Key列表',
						name: 'selector_keys',
						type: 'string',
						default: '',
						required: true,
						displayOptions: { show: { control: ['Selector'] } },
						placeholder: 'option-1,option-2',
						description: 'Selector.options[].key，逗号分隔；key 来自模板详情',
					},
					{
						displayName: '联系人类型',
						name: 'contact_kind',
						type: 'options',
						options: [
							{ name: '成员 members', value: 'members' },
							{ name: '部门 departments', value: 'departments' },
						],
						default: 'members',
						displayOptions: { show: { control: ['Contact'] } },
						description: 'Contact 控件写 members 或 departments',
					},
					{
						displayName: '成员UserID列表',
						name: 'contact_userids',
						type: 'string',
						default: '',
						displayOptions: {
							show: { control: ['Contact'], contact_kind: ['members'] },
						},
						placeholder: 'zhangsan,lisi',
						description: 'Contact members.userid，逗号分隔；与下方选择合并',
					},
					{
						displayName: '成员(选择)',
						name: 'contact_userids_selected',
						type: 'multiOptions',
						typeOptions: { loadOptionsMethod: 'getAllUsers' },
						default: [],
						displayOptions: {
							show: { control: ['Contact'], contact_kind: ['members'] },
						},
						description: '与上方列表合并去重',
					},
					{
						displayName: '部门ID列表',
						name: 'contact_partyids',
						type: 'string',
						default: '',
						displayOptions: {
							show: { control: ['Contact'], contact_kind: ['departments'] },
						},
						placeholder: '1,2',
						description: 'Contact departments.openapi_id，逗号分隔；与下方选择合并',
					},
					{
						displayName: '部门(选择)',
						name: 'contact_partyids_selected',
						type: 'multiOptions',
						typeOptions: { loadOptionsMethod: 'getDepartments' },
						default: [],
						displayOptions: {
							show: { control: ['Contact'], contact_kind: ['departments'] },
						},
						description: '与上方列表合并去重',
					},
					{
						displayName: '附件MediaID列表',
						name: 'file_mediaids',
						type: 'string',
						default: '',
						required: true,
						displayOptions: { show: { control: ['File'] } },
						placeholder: 'MEDIA_ID1,MEDIA_ID2',
						description: 'File 控件 files[].file_id，逗号分隔',
					},
					{
						displayName: '关联审批单号',
						name: 'related_sp_nos',
						type: 'string',
						default: '',
						required: true,
						displayOptions: { show: { control: ['RelatedApproval'] } },
						placeholder: '202011180001,202011180002',
						description: 'RelatedApproval.related_approval[].sp_no，逗号分隔',
					},
					{
						displayName: '纬度',
						name: 'location_latitude',
						type: 'string',
						default: '',
						required: true,
						displayOptions: { show: { control: ['Location'] } },
						placeholder: '30.547239',
						description: 'Location.latitude，精确到 6 位小数',
					},
					{
						displayName: '经度',
						name: 'location_longitude',
						type: 'string',
						default: '',
						required: true,
						displayOptions: { show: { control: ['Location'] } },
						placeholder: '104.063291',
						description: 'Location.longitude，精确到 6 位小数',
					},
					{
						displayName: '地点标题',
						name: 'location_title',
						type: 'string',
						default: '',
						required: true,
						displayOptions: { show: { control: ['Location'] } },
						description: 'Location.title',
					},
					{
						displayName: '地点详情',
						name: 'location_address',
						type: 'string',
						default: '',
						displayOptions: { show: { control: ['Location'] } },
						description: 'Location.address',
					},
					{
						displayName: '选择地点时间',
						name: 'location_time',
						type: 'dateTime',
						default: '',
						required: true,
						displayOptions: { show: { control: ['Location'] } },
						description: 'Location.time（Unix 秒）',
					},
					{
						displayName: '请假类型Key',
						name: 'vacation_selector_key',
						type: 'string',
						default: '',
						required: true,
						displayOptions: { show: { control: ['Vacation'] } },
						placeholder: '3',
						description: 'Vacation.selector.options[0].key，来自模板 vacation_list.item.id',
					},
					{
						displayName: '假勤类型',
						name: 'attendance_type',
						type: 'options',
						options: [
							{ name: '请假 (1)', value: 1 },
							{ name: '出差 (3)', value: 3 },
							{ name: '外出 (4)', value: 4 },
							{ name: '加班 (5)', value: 5 },
						],
						default: 1,
						displayOptions: { show: { control: ['Vacation', 'Attendance'] } },
						description: 'attendance.type；请假控件固定为 1',
					},
					{
						displayName: '假勤时长类型',
						name: 'attendance_range_type',
						type: 'options',
						options: [
							{ name: '半天 halfday', value: 'halfday' },
							{ name: '小时 hour', value: 'hour' },
						],
						default: 'hour',
						displayOptions: { show: { control: ['Vacation', 'Attendance'] } },
						description: 'attendance.date_range.type',
					},
					{
						displayName: '假勤开始',
						name: 'attendance_begin',
						type: 'dateTime',
						default: '',
						required: true,
						displayOptions: { show: { control: ['Vacation', 'Attendance'] } },
						description: 'attendance.date_range.new_begin',
					},
					{
						displayName: '假勤结束',
						name: 'attendance_end',
						type: 'dateTime',
						default: '',
						required: true,
						displayOptions: { show: { control: ['Vacation', 'Attendance'] } },
						description: 'attendance.date_range.new_end',
					},
					{
						displayName: '假勤时长秒数',
						name: 'attendance_duration',
						type: 'number',
						required: true,
						displayOptions: { show: { control: ['Vacation', 'Attendance'] } },
						default: 86400,
						typeOptions: { minValue: 0 },
						description: 'attendance.date_range.new_duration；有 slice_info 时可填 0',
					},
					{
						displayName: '时长分片 JSON',
						name: 'attendance_slice_info_json',
						type: 'json',
						default: '{}',
						displayOptions: { show: { control: ['Attendance'] } },
						description:
							'可选 attendance.slice_info；如 {"day_items":[{"daytime":1713801600,"duration":86400}]}',
					},
					{
						displayName: '明细行 JSON',
						name: 'table_children_json',
						type: 'json',
						default: '[]',
						required: true,
						displayOptions: { show: { control: ['Table'] } },
						description:
							'Table.value.children 数组；每项为 {"list":[{control,id,value},...]}，至少一行',
					},
					{
						displayName: '公式结果',
						name: 'formula_value',
						type: 'string',
						default: '',
						required: true,
						displayOptions: { show: { control: ['Formula'] } },
						placeholder: '5.0',
						description: 'Formula.formula.value，计算结果字符串',
					},
				],
			},
		],
	},
	{
		displayName: '申请表单数据JSON',
		name: 'apply_data_json',
		type: 'json',
		displayOptions: { show: showOnlyForSubmitApproval },
		default: '{}',
		description: '完整 apply_data。非空对象时优先；空对象则使用上方控件值表单',
	},
	{
		displayName: '摘要行',
		name: 'summaryLines',
		type: 'fixedCollection',
		required: true,
		displayOptions: { show: showOnlyForSubmitApproval },
		default: {},
		placeholder: '添加摘要行',
		typeOptions: { multipleValues: true },
		description: 'summary_list，最多 3 行，每行不超过 20 字',
		options: [
			{
				displayName: '摘要',
				name: 'lines',
				values: [
					{
						displayName: '摘要文字',
						name: 'text',
						type: 'string',
						required: true,
						default: '',
					},
					{
						displayName: '语言',
						name: 'lang',
						type: 'options',
						options: [
							{ name: '中文 zh_CN', value: 'zh_CN' },
							{ name: '英文 en', value: 'en' },
						],
						default: 'zh_CN',
					},
				],
			},
		],
	},
	{
		displayName: '审批流程节点',
		name: 'processNodeCollection',
		type: 'fixedCollection',
		required: true,
		displayOptions: {
			show: { ...showOnlyForSubmitApproval, use_template_approver: [0] },
		},
		default: {},
		placeholder: '添加节点',
		typeOptions: { multipleValues: true },
		description: 'process.node_list；use_template_approver=0 时必填',
		options: [
			{
				displayName: '节点',
				name: 'nodes',
				values: [
					{
						displayName: '节点类型',
						name: 'type',
						type: 'options',
						options: [
							{ name: '审批人', value: 1 },
							{ name: '抄送人', value: 2 },
							{ name: '办理人', value: 3 },
						],
						default: 1,
					},
					{
						displayName: '多人审批方式',
						name: 'apv_rel',
						type: 'options',
						options: [
							{ name: '会签', value: 1 },
							{ name: '或签', value: 2 },
							{ name: '依次审批', value: 3 },
						],
						default: 1,
						description: 'type 为审批人/办理人时有效',
					},
					{
						displayName: '成员UserID列表',
						name: 'userid_list',
						type: 'string',
						default: '',
						placeholder: 'user1,user2',
						description: '逗号分隔；与下方选择合并',
					},
					{
						displayName: '成员(选择)',
						name: 'userid_list_selected',
						type: 'multiOptions',
						typeOptions: { loadOptionsMethod: 'getAllUsers' },
						default: [],
						description: '与上方列表合并去重',
					},
				],
			},
		],
	},
	{
		displayName: '扩展请求JSON',
		name: 'approvalExtraJson',
		type: 'json',
		displayOptions: { show: showOnlyForSubmitApproval },
		default: '{}',
		description: '其余字段与上方合并，同名字段以 JSON 为准',
	},
];
