import type { INodeProperties } from 'n8n-workflow';

export const templateControlFields: INodeProperties[] = [
	{
		displayName: '控件类型',
		name: 'control',
		type: 'options',
		required: true,
		options: [
			{ name: '文本 Text', value: 'Text' },
			{ name: '多行文本 Textarea', value: 'Textarea' },
			{ name: '数字 Number', value: 'Number' },
			{ name: '金额 Money', value: 'Money' },
			{ name: '日期 Date', value: 'Date' },
			{ name: '单选/多选 Selector', value: 'Selector' },
			{ name: '成员/部门 Contact', value: 'Contact' },
			{ name: '说明 Tips', value: 'Tips' },
			{ name: '附件 File', value: 'File' },
			{ name: '明细 Table', value: 'Table' },
			{ name: '位置 Location', value: 'Location' },
			{ name: '关联审批 RelatedApproval', value: 'RelatedApproval' },
			{ name: '时长 DateRange', value: 'DateRange' },
			{ name: '电话 PhoneNumber', value: 'PhoneNumber' },
			{ name: '假期 Vacation', value: 'Vacation' },
			{ name: '出差/外出/加班 Attendance', value: 'Attendance' },
			{ name: '收款账户 BankAccount', value: 'BankAccount' },
		],
		default: 'Text',
	},
	{
		displayName: '控件ID',
		name: 'id',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Text-01',
		description: '模板内唯一，格式为“控件类型-数字”',
	},
	{
		displayName: '控件标题',
		name: 'title',
		type: 'string',
		required: true,
		default: '',
		description: '最多 40 个字符，模板内不能重名',
	},
	{
		displayName: '占位说明',
		name: 'placeholder',
		type: 'string',
		default: '',
		description: '最多 80 个字符；假勤控件不支持占位说明',
	},
	{
		displayName: '是否必填',
		name: 'require',
		type: 'boolean',
		default: false,
	},
	{
		displayName: '不打印',
		name: 'un_print',
		type: 'boolean',
		default: false,
	},
	{
		displayName: '选择器类型',
		name: 'selector_type',
		type: 'options',
		displayOptions: { show: { control: ['Selector'] } },
		options: [
			{ name: '单选', value: 'single' },
			{ name: '多选', value: 'multi' },
		],
		default: 'single',
	},
	{
		displayName: '选项文字列表',
		name: 'selector_options',
		type: 'string',
		required: true,
		displayOptions: { show: { control: ['Selector'] } },
		default: '',
		placeholder: '选项1,选项2',
		description: '支持逗号、中文逗号、竖线或换行分隔',
	},
	{
		displayName: '日期类型',
		name: 'date_type',
		type: 'options',
		displayOptions: { show: { control: ['Date'] } },
		options: [
			{ name: '日期', value: 'day' },
			{ name: '日期和时间', value: 'hour' },
		],
		default: 'day',
	},
	{
		displayName: '联系人选择类型',
		name: 'contact_type',
		type: 'options',
		displayOptions: { show: { control: ['Contact'] } },
		options: [
			{ name: '单选', value: 'single' },
			{ name: '多选', value: 'multi' },
		],
		default: 'single',
	},
	{
		displayName: '联系人模式',
		name: 'contact_mode',
		type: 'options',
		displayOptions: { show: { control: ['Contact'] } },
		options: [
			{ name: '成员', value: 'user' },
			{ name: '部门', value: 'department' },
		],
		default: 'user',
	},
	{
		displayName: '仅允许拍照',
		name: 'file_is_only_photo',
		type: 'boolean',
		displayOptions: { show: { control: ['File'] } },
		default: false,
	},
	{
		displayName: '时长粒度',
		name: 'date_range_type',
		type: 'options',
		displayOptions: { show: { control: ['DateRange'] } },
		options: [
			{ name: '按天/半天', value: 'halfday' },
			{ name: '按小时', value: 'hour' },
		],
		default: 'halfday',
	},
	{
		displayName: '时长按工作日计算',
		name: 'date_range_official_holiday',
		type: 'boolean',
		displayOptions: { show: { control: ['DateRange'] } },
		default: false,
	},
	{
		displayName: '每天时长(秒)',
		name: 'date_range_perday_duration',
		type: 'number',
		displayOptions: { show: { control: ['DateRange'] } },
		default: 86400,
		typeOptions: { minValue: 1, maxValue: 86400 },
	},
	{
		displayName: '位置距离(米)',
		name: 'location_distance',
		type: 'options',
		displayOptions: { show: { control: ['Location'] } },
		options: [
			{ name: '100 米', value: 100 },
			{ name: '200 米', value: 200 },
			{ name: '300 米', value: 300 },
		],
		default: 100,
	},
	{
		displayName: '可关联模板ID列表',
		name: 'related_template_ids',
		type: 'string',
		displayOptions: { show: { control: ['RelatedApproval'] } },
		default: '',
		description: '留空表示可关联所有模板；支持逗号、中文逗号、竖线或换行分隔',
	},
	{
		displayName: '控件配置JSON',
		name: 'control_config_json',
		type: 'json',
		default: '{}',
		description:
			'非空对象时覆盖上述自动生成的 config；Table、Attendance 等复杂控件可在此填写完整 config',
	},
];
