import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['meetingroom'], operation: ['manageBooking'] };

export const manageBookingDescription: INodeProperties[] = [
	{
		displayName: '操作类型',
		name: 'action',
		type: 'options',
		required: true,
		displayOptions: { show: showOnly },
		options: [
			{ name: '查询预定信息', value: 'list' },
			{ name: '按预定ID查询详情', value: 'get' },
			{ name: '预定会议室', value: 'book' },
			{ name: '通过日程预定', value: 'bookBySchedule' },
			{ name: '通过会议预定', value: 'bookByMeeting' },
			{ name: '取消预定', value: 'cancel' },
		],
		default: 'list',
		description:
			'会议室预定管理。<a href="https://developer.work.weixin.qq.com/document/path/93620" target="_blank">官方文档</a>',
	},
	{
		displayName: '按会议室筛选',
		name: 'filter_by_meetingroom',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		default: false,
	},
	{
		displayName: '会议室ID',
		name: 'meetingroom_id',
		type: 'number',
		required: true,
		displayOptions: {
			show: { ...showOnly, action: ['list'], filter_by_meetingroom: [true] },
		},
		default: 1,
		typeOptions: { minValue: 1 },
	},
	{
		displayName: '指定查询时间',
		name: 'filter_by_time',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		default: false,
		description: '接口不支持跨天查询；关闭时使用企业微信默认时间范围',
	},
	{
		displayName: '查询开始时间',
		name: 'list_start_time',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['list'], filter_by_time: [true] } },
		default: '',
	},
	{
		displayName: '查询结束时间',
		name: 'list_end_time',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['list'], filter_by_time: [true] } },
		default: '',
	},
	{
		displayName: '城市',
		name: 'city',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		default: '',
		description: '填写楼宇或楼层时必须填写',
	},
	{
		displayName: '楼宇',
		name: 'building',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		default: '',
		description: '填写楼层时必须填写',
	},
	{
		displayName: '楼层',
		name: 'floor',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		default: '',
	},
	{
		displayName: '预定ID',
		name: 'booking_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['get', 'cancel'] } },
		default: '',
		description: '会议室预定 ID（booking_id）',
	},
	{
		displayName: '会议室ID',
		name: 'meetingroom_id_get',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['get'] } },
		default: 1,
		typeOptions: { minValue: 1 },
	},
	{
		displayName: '会议室ID',
		name: 'meetingroom_id_book',
		type: 'number',
		required: true,
		displayOptions: {
			show: { ...showOnly, action: ['book', 'bookBySchedule', 'bookByMeeting'] },
		},
		default: 1,
		typeOptions: { minValue: 1 },
	},
	{
		displayName: '开始时间',
		name: 'book_start_time',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['book'] } },
		default: '',
		description: '最小预定时长为 30 分钟，企业微信会按 30 分钟取整',
	},
	{
		displayName: '结束时间',
		name: 'book_end_time',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['book'] } },
		default: '',
	},
	{
		displayName: '会议主题',
		name: 'subject',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['book'] } },
		default: '',
	},
	{
		displayName: '预定人UserID',
		name: 'booker',
		type: 'string',
		displayOptions: {
			show: { ...showOnly, action: ['book', 'bookBySchedule', 'bookByMeeting'] },
		},
		default: '',
		description: '预定人的 UserID；可与下方选择二选一',
	},
	{
		displayName: '预定人(选择)',
		name: 'booker_selected',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: {
			show: { ...showOnly, action: ['book', 'bookBySchedule', 'bookByMeeting'] },
		},
		default: '',
		description: '与上方字符串二选一；均填写时以字符串为准',
	},
	{
		displayName: '参会人员UserID',
		name: 'attendees',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['book'] } },
		default: '',
		description: '支持逗号、中文逗号、竖线或换行分隔；与下方选择合并，将自动去空和去重',
	},
	{
		displayName: '参会人员(选择)',
		name: 'attendees_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: { ...showOnly, action: ['book'] } },
		default: [],
		description: '与上方列表合并去重',
	},
	{
		displayName: '日程ID',
		name: 'schedule_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['bookBySchedule'] } },
		default: '',
		description: '仅可使用同应用创建的日程',
	},
	{
		displayName: '会议ID',
		name: 'meetingid',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['bookByMeeting'] } },
		default: '',
		description: '仅可使用同应用创建的会议',
	},
	{
		displayName: '保留日程',
		name: 'keep_schedule',
		type: 'options',
		displayOptions: { show: { ...showOnly, action: ['cancel'] } },
		options: [
			{ name: '同步删除日程', value: 0 },
			{ name: '保留日程', value: 1 },
		],
		default: 0,
		description: '是否保留日程；仅对非重复日程有效',
	},
	{
		displayName: '取消日期',
		name: 'cancel_date',
		type: 'dateTime',
		displayOptions: { show: { ...showOnly, action: ['cancel'] } },
		default: '',
		description: '重复预定时指定要取消的日期；留空表示取消全部重复预定',
	},
];
