import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['meetingroom'], operation: ['manageMeetingroom'] };
const equipmentOptions = [
	{ name: '电视', value: 1 },
	{ name: '电话', value: 2 },
	{ name: '投影', value: 3 },
	{ name: '白板', value: 4 },
	{ name: '视频', value: 5 },
];

export const manageMeetingroomDescription: INodeProperties[] = [
	{
		displayName: '操作类型',
		name: 'action',
		type: 'options',
		required: true,
		displayOptions: { show: showOnly },
		options: [
			{ name: '查询会议室列表', value: 'list' },
			{ name: '添加会议室', value: 'add' },
			{ name: '编辑会议室', value: 'edit' },
			{ name: '删除会议室', value: 'delete' },
		],
		default: 'list',
		description:
			'选择会议室管理操作。<a href="https://developer.work.weixin.qq.com/document/path/93619" target="_blank">官方文档</a>',
	},
	{
		displayName: '城市',
		name: 'city',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		default: '',
		description: '按城市筛选；填写楼宇或楼层时必须填写',
	},
	{
		displayName: '楼宇',
		name: 'building',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		default: '',
		description: '按楼宇筛选；填写楼层时必须填写',
	},
	{
		displayName: '楼层',
		name: 'floor',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		default: '',
		description: '按楼层筛选会议室',
	},
	{
		displayName: '设备类型',
		name: 'equipment',
		type: 'multiOptions',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		options: equipmentOptions,
		default: [],
		description: '只返回同时满足设备条件的会议室',
	},
	{
		displayName: '会议室ID',
		name: 'meetingroom_id',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['edit', 'delete'] } },
		default: 1,
		typeOptions: { minValue: 1 },
		description: '会议室的唯一标识 ID',
	},
	{
		displayName: '会议室名称',
		name: 'name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['add'] } },
		default: '',
		description: '最多 30 个字符',
	},
	{
		displayName: '容纳人数',
		name: 'capacity',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['add'] } },
		default: 10,
		typeOptions: { minValue: 1 },
	},
	{
		displayName: '所在城市',
		name: 'city_add',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['add'] } },
		default: '',
		description: '设置位置时，城市、楼宇、楼层必须同时填写',
	},
	{
		displayName: '所在楼宇',
		name: 'building_add',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['add'] } },
		default: '',
	},
	{
		displayName: '所在楼层',
		name: 'floor_add',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['add'] } },
		default: '',
	},
	{
		displayName: '设备类型',
		name: 'equipment_add',
		type: 'multiOptions',
		displayOptions: { show: { ...showOnly, action: ['add'] } },
		options: equipmentOptions,
		default: [],
	},
	{
		displayName: '设置坐标',
		name: 'set_coordinate',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['add'] } },
		default: false,
		description: '为会议室所在建筑设置经纬度',
	},
	{
		displayName: '纬度',
		name: 'latitude',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['add'], set_coordinate: [true] } },
		default: '',
		placeholder: '22.540503',
	},
	{
		displayName: '经度',
		name: 'longitude',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['add'], set_coordinate: [true] } },
		default: '',
		placeholder: '113.934528',
	},
	{
		displayName: '限制使用范围',
		name: 'set_range',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['add'] } },
		default: false,
		description: '关闭时默认全公司可用',
	},
	{
		displayName: '可用成员UserID',
		name: 'range_user_list',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['add'], set_range: [true] } },
		default: '',
		description: '最多 1000 个；与下方选择合并；支持逗号、中文逗号、竖线或换行分隔',
	},
	{
		displayName: '可用成员(选择)',
		name: 'range_user_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: { ...showOnly, action: ['add'], set_range: [true] } },
		default: [],
		description: '与上方成员列表合并去重',
	},
	{
		displayName: '可用成员 JSON',
		name: 'rangeUserListJson',
		type: 'json',
		displayOptions: { show: { ...showOnly, action: ['add'], set_range: [true] } },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '可用部门ID',
		name: 'range_department_list',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['add'], set_range: [true] } },
		default: '',
		description: '最多 1000 个；与下方选择合并；支持逗号、中文逗号、竖线或换行分隔',
	},
	{
		displayName: '可用部门(选择)',
		name: 'range_department_list_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getDepartments' },
		displayOptions: { show: { ...showOnly, action: ['add'], set_range: [true] } },
		default: [],
		description: '与上方部门列表合并去重',
	},
	{
		displayName: '修改名称',
		name: 'update_name',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['edit'] } },
		default: false,
	},
	{
		displayName: '新会议室名称',
		name: 'name_edit',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['edit'], update_name: [true] } },
		default: '',
		description: '最多 30 个字符',
	},
	{
		displayName: '修改容纳人数',
		name: 'update_capacity',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['edit'] } },
		default: false,
	},
	{
		displayName: '新容纳人数',
		name: 'capacity_edit',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['edit'], update_capacity: [true] } },
		default: 10,
		typeOptions: { minValue: 1 },
	},
	{
		displayName: '修改位置',
		name: 'update_location',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['edit'] } },
		default: false,
		description: '启用后必须同时填写城市、楼宇和楼层',
	},
	{
		displayName: '新所在城市',
		name: 'city_edit',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['edit'], update_location: [true] } },
		default: '',
	},
	{
		displayName: '新所在楼宇',
		name: 'building_edit',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['edit'], update_location: [true] } },
		default: '',
	},
	{
		displayName: '新所在楼层',
		name: 'floor_edit',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['edit'], update_location: [true] } },
		default: '',
	},
	{
		displayName: '修改设备',
		name: 'update_equipment',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['edit'] } },
		default: false,
		description: '启用后会覆盖设备列表；留空表示清空',
	},
	{
		displayName: '新设备类型',
		name: 'equipment_edit',
		type: 'multiOptions',
		displayOptions: { show: { ...showOnly, action: ['edit'], update_equipment: [true] } },
		options: equipmentOptions,
		default: [],
	},
	{
		displayName: '修改坐标',
		name: 'update_coordinate',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['edit'] } },
		default: false,
		description: '已有建筑的经纬度可能无法修改，请按企业微信接口限制使用',
	},
	{
		displayName: '新纬度',
		name: 'latitude_edit',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['edit'], update_coordinate: [true] } },
		default: '',
	},
	{
		displayName: '新经度',
		name: 'longitude_edit',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['edit'], update_coordinate: [true] } },
		default: '',
	},
	{
		displayName: '覆盖使用范围',
		name: 'update_range',
		type: 'boolean',
		displayOptions: { show: { ...showOnly, action: ['edit'] } },
		default: false,
		description: '启用后覆盖整个使用范围；成员和部门都留空表示恢复全公司可用',
	},
	{
		displayName: '新可用成员UserID',
		name: 'range_user_list_edit',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['edit'], update_range: [true] } },
		default: '',
		description: '最多 1000 个；与下方选择合并；支持逗号、中文逗号、竖线或换行分隔',
	},
	{
		displayName: '新可用成员(选择)',
		name: 'range_user_list_edit_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAllUsers' },
		displayOptions: { show: { ...showOnly, action: ['edit'], update_range: [true] } },
		default: [],
		description: '与上方成员列表合并去重',
	},
	{
		displayName: '新可用成员 JSON',
		name: 'rangeUserListEditJson',
		type: 'json',
		displayOptions: { show: { ...showOnly, action: ['edit'], update_range: [true] } },
		default: '[]',
		description:
			'可选。非空数组时与上方列表/选择合并去重。支持 ["userid1"] 或 [{"userid":"userid1"}]',
	},
	{
		displayName: '新可用部门ID',
		name: 'range_department_list_edit',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['edit'], update_range: [true] } },
		default: '',
		description: '最多 1000 个；与下方选择合并；支持逗号、中文逗号、竖线或换行分隔',
	},
	{
		displayName: '新可用部门(选择)',
		name: 'range_department_list_edit_selected',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getDepartments' },
		displayOptions: { show: { ...showOnly, action: ['edit'], update_range: [true] } },
		default: [],
		description: '与上方部门列表合并去重',
	},
];
